apps/namada-interface/src/App/App.tsx, apps/namada-interface/src/App/TopNavigation/topNavigation.tsx, apps/namada-interface/src/App/TopNavigation/topNavigationLoggedIn.tsx, apps/namada-interface/src/App/types.ts, apps/namada-interface/src/utils/theme/index.ts, apps/namada-interface/src/utils/theme/theme.ts
=> fix(theme, colors): theme changes to dark after refreshing the app

apps/namada-interface/src/App/Login/Login.tsx, apps/namada-interface/src/components/Button/button.components.ts, apps/namada-interface/src/components/Button/button.tsx
Relates to #69 
This adds spinner button!
You can test it on locked screen.
In the next PR I will add loading state to redux.
=> feat(button): create button with spinner

.github/workflows/deploy-wallet-at-merge-to-main.yml, .github/workflows/deploy-wallet-at-pr.yml
See #155 
This PR is simply to point our development environments to the current testnet.
=> feat/155 - Updating CI workflows to point app to current testnet

apps/namada-interface/src/services/integrations.tsx, apps/namada-interface/src/slices/accounts.ts, packages/chains/src/chains/ethereum.ts, packages/chains/src/index.ts, packages/integrations/package.json, packages/integrations/src/Metamask.ts, packages/integrations/src/index.ts, yarn.lock
Allows you to load accounts from Eth Goerli test network into interface.
It loads accounts into state but It won't show balances as rpc calls are not working.
We should most likely try to unify the signers for all the extensions.
=> feat: load accounts from metamask

apps/extension/src/App/Accounts/AddAccount.components.ts, apps/extension/src/App/Accounts/AddAccount.tsx
=> feat: add validation for address alias

.github/workflows/deploy-wallet-at-merge-to-main.yml, .github/workflows/deploy-wallet-at-pr.yml
See #155 
This is an ongoing task to update CI as needed. This is updated for our current internal devnet.
=> feat/155 - Updating CI to point to devnet

apps/namada-interface/src/App/AccountOverview/DerivedAccounts/DerivedAccounts.tsx, apps/namada-interface/src/App/App.tsx, apps/namada-interface/src/App/Staking/NewBondingPosition/NewBondingPosition.tsx, apps/namada-interface/src/App/Staking/Staking.tsx, apps/namada-interface/src/App/Staking/StakingOverview/StakingOverview.tsx, apps/namada-interface/src/App/StakingAndGovernance/StakingAndGovernance.tsx, apps/namada-interface/src/App/Token/IBCTransfer/IBCTransfer.tsx, apps/namada-interface/src/App/Token/TokenDetails.tsx, apps/namada-interface/src/App/Token/TokenReceive/TokenReceive.tsx, apps/namada-interface/src/App/Token/TokenSend/TokenSend.tsx, apps/namada-interface/src/App/Token/TokenSend/TokenSendForm.tsx, apps/namada-interface/src/App/Token/Transfers/Transfers.tsx, apps/namada-interface/src/slices/StakingAndGovernance/actions.ts, apps/namada-interface/src/slices/accounts.ts, apps/namada-interface/src/store/mocks.ts
=> refactor: accounts naming

apps/namada-interface/src/App/AccountOverview/DerivedAccounts/DerivedAccounts.tsx
Fixes expanding account address on account click in the interface.
Should also fix expanding on chain switch.
=> fix: accounts do not expand on click

apps/namada-interface/src/App/AccountOverview/DerivedAccounts/DerivedAccounts.tsx
=> bug: conversion rates do not update for specific accounts

apps/extension/src/App/App.tsx, apps/extension/src/App/Requester.tsx, apps/extension/src/App/index.tsx, apps/extension/src/Setup/Setup.tsx, apps/extension/src/Setup/index.tsx, apps/extension/src/background/index.ts, apps/extension/src/background/offscreen/offscreen.ts, apps/extension/src/background/web-workers/index.ts, apps/extension/src/content/index.ts, apps/extension/src/extension/ExtensionRequester.ts, apps/extension/src/test/init.ts
To make it a little bit more straightforward,
=> feat: pass routerId directly to the requester

packages/shared/lib/src/query.rs, packages/shared/lib/src/rpc_client.rs, packages/shared/lib/src/sdk/mod.rs, packages/shared/lib/src/sdk/tx.rs, packages/shared/lib/src/sdk/wallet.rs, specs/packages/sdk.md
Resolves #178 
Initial docs for the Sdk.
Let me know if some things are missing or maybe something can be phrased better :)
=> docs: initial sdk docs

README.md
=> docs: add dependency install instructions to README

README.md
See #222 
Update dependency requirements for macOS, as well as environment variables in `README.md`
=> docs: Updating README for building interface on macOS

apps/extension/src/App/App.tsx, apps/extension/src/App/Settings/ExtraSettings/ExtraSettings.components.ts, apps/extension/src/App/Settings/ExtraSettings/ExtraSettings.tsx, apps/extension/src/App/Settings/ExtraSettings/ResetPassword/ResetPassword.components.ts, apps/extension/src/App/Settings/ExtraSettings/ResetPassword/ResetPassword.tsx, apps/extension/src/App/Settings/ExtraSettings/ResetPassword/index.ts, apps/extension/src/App/Settings/ExtraSettings/index.ts, apps/extension/src/App/Settings/ExtraSettings/types.ts, apps/extension/src/App/Settings/Settings.components.tsx, apps/extension/src/App/Settings/Settings.tsx, apps/extension/src/background/keyring/handler.ts, apps/extension/src/background/keyring/init.ts, apps/extension/src/background/keyring/keyring.ts, apps/extension/src/background/keyring/messages.ts, apps/extension/src/background/keyring/service.ts, apps/extension/src/background/keyring/types.ts, packages/utils/src/helpers/index.ts
=> feat: Allow user to change account password

apps/extension/src/App/Settings/ExtraSettings/DeleteAccount/DeleteAccount.components.ts, apps/extension/src/App/Settings/ExtraSettings/DeleteAccount/DeleteAccount.tsx, apps/extension/src/App/Settings/ExtraSettings/DeleteAccount/index.ts, apps/extension/src/App/Settings/ExtraSettings/ExtraSettings.tsx, apps/extension/src/App/Settings/ExtraSettings/types.ts, apps/extension/src/App/Settings/Settings.tsx, apps/extension/src/background/keyring/handler.ts, apps/extension/src/background/keyring/init.ts, apps/extension/src/background/keyring/keyring.ts, apps/extension/src/background/keyring/messages.ts, apps/extension/src/background/keyring/service.ts, apps/extension/src/background/keyring/types.ts
=> feat: allow user to delete account

apps/extension/src/background/keyring/keyring.ts
For now we will just parse strings to int. In Future we would probably construct BigInt out of the string.
=> bug: amounts as strings

apps/extension/src/App/App.components.ts, apps/extension/src/App/App.tsx, apps/extension/src/App/Loading/Loading.components.ts, apps/extension/src/App/Loading/Loading.tsx, apps/extension/src/Approvals/ApproveTransfer/ConfirmTransfer.components.ts, apps/extension/src/Approvals/ApproveTransfer/ConfirmTransfer.tsx, apps/extension/src/background/keyring/handler.ts, apps/extension/src/background/keyring/init.ts, apps/extension/src/background/keyring/service.ts, apps/extension/src/provider/Anoma.ts, apps/extension/src/provider/messages.ts, apps/namada-interface/src/App/Token/TokenSend/TokenSendForm.tsx, packages/shared/lib/src/sdk/mod.js, packages/shared/lib/src/sdk/mod.rs
Resolves #304
We are loading params in two cases:
- when opening extension- non blocking fetch
- when submitting a transfer - blocking fetch
=> feat: async masp params loading

packages/shared/lib/Cargo.lock, packages/shared/lib/Cargo.toml
Make sure to:
- Install [CometBFT](https://github.com/cometbft/cometbft/releases/tag/v0.37.1)
- Recreate whole chain as usual - do not forget to change chain id in the envs like me :laughing:. Otherwise you might be able to query data, but submitting tx will fail.
- It looks like CORS issue is not an issue anymore :crossed_fingers:
=> feat: update namada to 0.17.3

apps/extension/src/background/keyring/keyring.ts
Added functionality to scan for shielded addresses when importing accounts
=> feat: scan shielded addresses

apps/extension/src/background/keyring/keyring.ts
Because of the changes  to amounts
=> bug: can't import accounts

README.md, apps/extension/README.md, packages/crypto/README.md, packages/shared/README.md
=> Updating README.md for macOS

apps/extension/src/Approvals/ApproveTx/ConfirmTx.tsx
Does not close for non-ledger txs
=> fix: confirm tx window not closing

e2e/src/index.test.ts, e2e/src/partial/setup.ts, e2e/src/utils/helpers.ts, e2e/src/utils/values.ts
Added tests for deriving addresses
=> test: derive transparent and derive shielded address e2e tests

e2e/genesis.toml, e2e/setup-namada.sh, e2e/src/index.test.ts, e2e/src/partial/setup.ts, packages/shared/lib/Cargo.lock, packages/shared/lib/Cargo.toml, packages/shared/lib/src/query.rs, packages/shared/lib/src/sdk/masp.rs, packages/shared/lib/src/sdk/mod.rs, packages/shared/lib/src/sdk/tx.rs, packages/shared/lib/src/sdk/wallet.rs
For now I've used  DefaultIo struct  which does nothing for us.
We can replace it with our IO  to print some logs to the console.
FIxed e2e tests
=> chore: update namada to 0.23.0

packages/crypto/lib/rust-toolchain.toml, packages/shared/lib/rust-toolchain.toml, packages/shared/lib/src/query.rs, packages/shared/lib/src/sdk/io.rs, packages/shared/lib/src/sdk/mod.rs
Implementation of IO trait for web.
It does not implement the write,writeln or flush functions.
You can test it by doing some kind of transaction, like staking.
You should see something like this in  service worker logs:
```
The provided gas price 0.000000 is less than the minimum amount required 0.000001, changing it to match the minimum
background.namada.js:28684 Transaction added to mempool: Response { code: Ok, data: Data([]), log: Log("Mempool validation passed"), hash: transaction::Hash(2F88CEB21A35A9BE0EE11A127227479389203BA0A507F6D24307D6AAAA134B00) }
background.namada.js:28684 Wrapper transaction hash: "895D1DA16E4BDCEF4C578833BB288A9DE3C7EC87982A83B6447FA39E3B4779A7"
background.namada.js:28684 Inner transaction hash: "D5B6D4A3FC465D9F52BB789AB7F4D34DBBA1C489FE8591728038D2371DEE84 …
```
=> feat: implement web io

.github/workflows/release-wallet.yml, packages/types/src/chain.ts
=> feat/410 - Update release action

README.md
I've just ran the installation process on my end and noticed a few missing bits in the README file. Updating it for future reference.
=> Updating README with a few missing steps

apps/extension/src/App/App.tsx, apps/extension/src/App/Common/GlobalStyles/GlobalStyles.tsx, apps/extension/src/App/index.tsx, apps/extension/src/public/app.css, packages/components/src/Container/Container.components.ts
Adding a simple entrance animation and styling scrollbars
=> Styling a few elements

apps/extension/src/Approvals/Approvals.components.tsx, apps/extension/src/Approvals/Approvals.tsx, apps/extension/src/Approvals/ApproveConnection/ApproveConnection.tsx, apps/extension/src/Approvals/ApproveTx/ApproveTx.tsx, apps/extension/src/Approvals/ApproveTx/ConfirmLedgerTx.tsx, apps/extension/src/Approvals/ApproveTx/ConfirmTx.tsx, apps/extension/src/Approvals/index.tsx, apps/extension/src/background/approvals/service.ts
=> feat/465 - Updates to Approve Connection

apps/airdrop/src/App/eligibilityMap.ts
=> feat(airdrops website): add ethresarch category

apps/airdrop/src/App/Layouts/SidebarPage/SidebarPage.tsx, apps/airdrop/src/App/Main.tsx
Resolves #494 
Have in mind that there is nothing under the link yet.
=> feat: add annoucement link

apps/airdrop/src/App/AirdropConfirmation.tsx, apps/airdrop/src/App/AnotherWays.tsx, apps/airdrop/src/App/App.components.ts, apps/airdrop/src/App/TrustedSetup.tsx
This is not the transition we've initially intended to make, but it looks ok and we can move forward with other things
=> feat: airdrop confirmed transition

apps/airdrop/src/App/AirdropConfirmation.tsx, apps/airdrop/src/App/App.tsx, apps/airdrop/src/App/Claim/ClaimConfirmation/ClaimConfirmation.tsx, apps/airdrop/src/App/NonEligible.tsx, apps/airdrop/src/App/utils.ts
- tos capitalization
- retrigger animation in non-eligible view
- change confirmation path
- display amount in correct format - two decimal places rounded down
=> Airdrop Fixes

apps/extension/src/background/keyring/keyring.ts, apps/extension/src/background/web-workers/submit-transfer-web-worker.ts, apps/namada-interface/src/App/Token/TokenSend/TokenSendForm.tsx, apps/namada-interface/src/App/Token/types.ts, packages/shared/lib/src/sdk/mod.rs, packages/shared/lib/src/sdk/tx.rs, packages/shared/src/index.ts, packages/types/src/tx/schema/tx.ts
Resolves #524
We have to use disposable key for the privacy reasons.
=> feat: masp with disposable key

apps/faucet/src/App/Faucet.tsx, apps/namada-interface/src/App/Token/TokenSend/TokenSendForm.tsx, packages/components/src/AmountInput.tsx, packages/components/src/index.ts
Fixes input amount bugs in faucet and interface send token form.
Fixes #536.
=> Add amount input component to fix input bugs

apps/namada-interface/src/App/Token/TokenSend/TokenSend.tsx, apps/namada-interface/src/App/Token/TokenSend/TokenSendForm.components.ts, apps/namada-interface/src/App/Token/TokenSend/TokenSendForm.tsx, packages/shared/lib/src/query.rs
- Replace gas fee buttons with minimum gas price
- Calculate gas fee based on minimum gas price and whether reveal PK transaction is needed
- Add max button to use all available funds in account
- Remove unused QR reader code
=> feat: calculate gas fees in token send form

apps/extension/src/background/keyring/keyring.ts
=> fix: make signing with imported secret key work

apps/namada-interface/src/slices/accounts.ts
=> fix: query account balances individually

apps/extension/src/Setup/AccountCreation/SeedPhraseConfirmation.tsx
Fixes #584.
- Show seed phrase confirmation words in ascending order
=> fix: seed phrase confirmation in ascending order

.github/workflows/deploy-wallet-at-pr.yml, packages/components/src/RadioGroup.tsx
Fixes bug where pasting a 24 word seed phrase doesn't move the toggle to "24 words".
Also includes a fix to make the CI run for changes in any package, as the CI wasn't running for this PR beforehand.
=> fix: make RadioGroup react to value change

apps/faucet/package.json, apps/faucet/postcss.config.js, apps/faucet/src/App/App.tsx, apps/faucet/src/App/CallToActionCard.tsx, apps/faucet/src/App/Faq.components.tsx, apps/faucet/src/App/Faq.tsx, apps/faucet/src/App/FaqDropdown.tsx, apps/faucet/src/App/Faucet.tsx, apps/faucet/src/index.tsx, apps/faucet/src/tailwind.css, apps/faucet/tailwind.config.js, apps/faucet/tsconfig.json, apps/faucet/tsconfig.webpack.json, apps/faucet/webpack.config.js, yarn.lock
New with tailwind changes vs old
=> chore: update faucet with tailwind

apps/extension/src/Setup/AccountCreation/SeedPhraseWarning.tsx, apps/extension/src/Setup/Common/Completion.tsx, apps/extension/src/Setup/Common/Password.tsx, apps/extension/src/Setup/Common/SeedPhraseListItem.tsx, apps/extension/src/Setup/ImportAccount/SeedPhraseImport.tsx, apps/extension/src/Setup/Ledger/LedgerConfirmation.tsx, apps/extension/src/utils/index.ts, packages/components/src/FeedbackButton.tsx
This PR contains just a few small tweaks on extension UI, and also fixes a bug when changing from 12 to 24 words.
=> Few extension UI tweaks

apps/extension/src/Setup/AccountCreation/SeedPhrase.tsx, apps/extension/src/Setup/AccountCreation/SeedPhraseConfirmation.tsx, apps/extension/src/Setup/AccountCreation/SeedPhraseWarning.tsx, apps/extension/src/Setup/Common/CreateKeyForm.tsx, apps/extension/src/background/keyring/handler.ts, apps/extension/src/background/keyring/init.ts, apps/extension/src/background/keyring/service.ts, apps/extension/src/provider/InjectedNamada.ts, apps/extension/src/provider/Namada.ts, apps/extension/src/provider/messages.ts, apps/namada-interface/src/slices/accounts.ts, e2e/setup-namada.sh, e2e/src/partial/setup.ts, packages/components/src/FeedbackButton.tsx, packages/integrations/src/Keplr.ts, packages/integrations/src/Metamask.ts, packages/integrations/src/Namada.ts, packages/integrations/src/hooks/useIntegration.ts, packages/integrations/src/types/Integration.ts, packages/shared/lib/Cargo.lock, packages/shared/lib/Cargo.toml, packages/shared/lib/src/query.rs, packages/shared/lib/src/sdk/masp.rs, packages/shared/lib/src/sdk/mod.rs, packages/shared/lib/src/sdk/wallet.rs, packages/shared/src/index.ts, packages/types/src/namada.ts
Bump namada
Fix unshielding
Fix e2e tests(need to double check)
=> fix: unshiedling

apps/extension/src/background/approvals/handler.test.ts, apps/extension/src/background/approvals/service.test.ts, apps/extension/src/background/approvals/service.ts
Missing approvals service tests
=> test: approvals service remaining tests

apps/namada-interface/src/App/Token/IBCTransfer/IBCTransfer.tsx, packages/shared/lib/src/sdk/tx.rs, packages/types/src/tx/schema/ibcTransfer.ts
=> feat: support memo field in ibc transfer

apps/extension/src/App/Accounts/ParentAccounts.tsx, apps/extension/src/App/Settings/ConnectedSites.tsx
Closes #686.
Also capitalize "Add Keys".
=> feat: add button to disconnect all connected sites

apps/namada-interface/src/App/Common/ActiveAccount/ActiveAccount.tsx, apps/namada-interface/src/App/Common/CurrencySelector/CurrencySelector.tsx, apps/namada-interface/src/App/Common/CurrencySelector/index.ts, apps/namada-interface/src/App/Common/TopNavigation/TopNavigation.tsx, apps/namada-interface/src/currencies/index.ts, apps/namada-interface/src/slices/exchangeRates.ts, apps/namada-interface/src/slices/settings.ts, packages/components/src/CopyToClipboardControl.tsx, packages/components/src/StyledSelectBox.tsx, packages/components/src/ToggleButton.tsx
This PR implements "Private mode" toggle and fiat currency select box, as described in #710 . Also make some important tweaks in relative components.
=> Implementing currency selector and "hide currency" toggle on Top Navigation

apps/namadillo/src/App/AppRoutes.tsx, apps/namadillo/src/App/Common/TopNavigation.tsx, apps/namadillo/src/App/Settings/Advanced.tsx, apps/namadillo/src/App/Settings/CurrencySelector.tsx, apps/namadillo/src/App/Settings/CurrencySelectorEntry.tsx, apps/namadillo/src/App/Settings/SettingsMain.tsx, apps/namadillo/src/App/Settings/SettingsPanel.tsx, apps/namadillo/src/App/Settings/SettingsPanelMenuItem.tsx, apps/namadillo/src/App/Settings/routes.ts, apps/namadillo/src/slices/settings.ts, packages/components/src/ToggleButton.tsx
This PR implements Settings page and implements a modal navigation, keeping the background page active and blurred.
Closes #787 .
=> Creating Settings Page

apps/namadillo/src/App/AccountOverview/AccountOverview.tsx, apps/namadillo/src/App/Common/Container.tsx, apps/namadillo/src/App/Common/Footer.tsx, apps/namadillo/src/App/Common/PageWithSidebar.tsx, apps/namadillo/src/App/Governance/GovernanceOverview.tsx
Adding Namada footer and tweaking spacements.
Closes #785
=> Adding Namada Footer

apps/namadillo/src/hooks/useTransactionCallbacks.tsx, apps/namadillo/src/slices/validators.ts
In the last commit of #838 , a few files haven't been added. This PR fix this.
=> fix: updating references for shouldUpdateBalanceAmount

apps/namadillo/src/App/Sidebars/YourStakingDistribution.tsx, apps/namadillo/src/App/Staking/MyValidatorsTable.tsx, apps/namadillo/src/App/Staking/StakingOverview.tsx, apps/namadillo/src/App/Staking/UnbondingAmountsTable.tsx, apps/namadillo/src/App/Staking/WithdrawalButton.tsx, apps/namadillo/src/hooks/useTransactionNotifications.tsx, apps/namadillo/src/slices/staking.ts, apps/namadillo/src/slices/validators.ts
This PR adds the unbonding list to the Staking flow, also enabling the withdrawal process.
We still need a way to figure out how to display multiple unbonds (#845)
=> Namadillo: Staking > Withdraw

apps/namadillo/src/App/AppRoutes.tsx, apps/namadillo/src/App/Governance/Governance.tsx, apps/namadillo/src/App/Governance/ProposalAndVote.tsx, apps/namadillo/src/App/Governance/SubmitVote.tsx, apps/namadillo/src/App/Governance/ViewJson.tsx, apps/namadillo/src/App/Governance/routes.ts, apps/namadillo/src/hooks/index.ts, apps/namadillo/src/hooks/useProposalIdParam.ts
- Rename Governance overview route to "/" to match Staking
- Make Governance route wildcard to match Staking
- Reuse and fix up proposal ID query param logic
- Add scroll to top behaviour when changing page
- Fix back button not working on Governance page
Fixes #805. Fixes #811.
=> More Governance fixes

apps/namadillo/src/App/Common/TableWithPaginator.tsx, apps/namadillo/src/App/Governance/AllProposalsTable.tsx, apps/namadillo/src/App/Staking/ValidatorsTable.tsx
Also rename ValidatorsTable to TableWithPaginator and refactor to allow use with things other than validators.
Closes #843.
=> feat: add pagination to proposals table

.lintstagedrc.json, apps/namadillo/src/App/AccountOverview/AccountOverview.tsx, apps/namadillo/src/App/Common/Footer.tsx, apps/namadillo/src/App/Governance/AllProposalsTable.tsx, apps/namadillo/src/App/Governance/LiveGovernanceProposals.tsx
The main change here is making the proposals table columns have fixed widths so it doesn't move about when the data changes. I think my solution is a bit hacky so I'm not very happy with it, so if there is a better way then please let me know about it.
---
- Make proposals table columns fixed widths
- Fix more instances of wrong black color
- Remove vote button on live proposals list
- Fix lintstaged braces warning
=> Misc. UI fixes

apps/namadillo/src/App/Common/Container.tsx, apps/namadillo/src/App/Common/SmallScreenBlocking.tsx
=> Removing logo placeholder

apps/namadillo/src/App/Governance/AllProposalsTable.tsx, apps/namadillo/src/App/Governance/ProposalAndVote.tsx, apps/namadillo/src/App/Governance/ProposalHeader.tsx, apps/namadillo/src/App/Governance/ProposalStatusSummary.tsx, apps/namadillo/src/App/Governance/SubmitVote.tsx, apps/namadillo/src/hooks/useTransactionNotifications.tsx, apps/namadillo/src/slices/proposals/atoms.ts, apps/namadillo/src/slices/proposals/functions.ts, apps/namadillo/src/types/events.ts, packages/config/eslint/react.js
- Temporarily switch off proposal persistent cache
- Temporarily hide placeholder vote info text
- Default to highest vote in proposal summary
- Add success/failure notifications for voting
- Remove ProposalAndVote error handling code (can be done better elsewhere)
- Readd proposals table filter and search
- Use indexer to check if user voted on proposal
- Make the vote button read "Edit Vote" once the user has voted
- Fix some text in notifications
- Add footer to proposal page
- Fix panel gaps on proposal page
=> Governance pre-release final-ish touches

apps/namadillo/src/App/Common/NamInput.tsx, apps/namadillo/src/App/Staking/IncrementBondingTable.tsx, apps/namadillo/src/App/Staking/ReDelegateTable.tsx, apps/namadillo/src/App/Staking/UnstakeBondingTable.tsx, packages/components/src/StyledTable.tsx, packages/components/src/StyledTableHead.tsx
=> Small fixes 2024 06 17

apps/namadillo/src/App/AccountOverview/AccountOverview.tsx, apps/namadillo/src/App/Common/Container.tsx, apps/namadillo/src/App/Common/Navigation.tsx, apps/namadillo/src/App/Common/PageWithSidebar.tsx, apps/namadillo/src/App/Settings/SettingsMain.tsx, apps/namadillo/src/App/Settings/SettingsPanel.tsx, apps/namadillo/src/App/Settings/SettingsSignArbitrary.tsx, apps/namadillo/src/App/Settings/routes.ts, apps/namadillo/src/App/Sidebars/ValidatorDiversification.tsx, apps/namadillo/src/App/Staking/IncrementBonding.tsx, apps/namadillo/src/slices/accounts/services.ts, apps/namadillo/src/tailwind.css
Another batch of UI tweaks for Namadillo
Also fixes #876
=> UI Tweaks - Week 25.1

apps/namadillo/src/App/AccountOverview/AccountBalanceContainer.tsx, apps/namadillo/src/App/Staking/BondingAmountOverview.tsx, apps/namadillo/src/App/Staking/MyValidatorsTable.tsx, apps/namadillo/src/App/Staking/StakingSummary.tsx, apps/namadillo/src/App/Staking/UnbondingAmountsTable.tsx
Revert this once we have fiat currency data.
Closes #877.
=> temp: remove fiat currency display

apps/namadillo/package.json, apps/namadillo/src/App/Staking/UnbondingAmountsTable.tsx, apps/namadillo/src/App/Staking/ValidatorInfoPanel.tsx, apps/namadillo/src/App/Staking/WithdrawalButton.tsx, apps/namadillo/src/slices/chainParameters.ts, apps/namadillo/src/slices/fees.ts, apps/namadillo/src/slices/validators.ts, packages/utils/package.json, packages/utils/src/helpers/index.ts, yarn.lock
Also:
- real apr
- real unbonding time
- some fixes to unbonds table
=> feat: chain id from indexer

apps/namadillo/src/App/Governance/AllProposalsTable.tsx, apps/namadillo/src/App/Governance/GovernanceOverview.tsx, apps/namadillo/src/App/Governance/LiveGovernanceProposals.tsx, apps/namadillo/src/App/Governance/ProposalListPanel.tsx, apps/namadillo/src/App/Governance/UpcomingProposals.tsx, apps/namadillo/src/atoms/proposals/atoms.ts
This PR fixes some queries in the Governance overview, and also adds an "empty" message when there are no live or upcoming governance proposals.
=> Namadillo: Review Governance Queries

apps/namadillo/src/App/AppRoutes.tsx, apps/namadillo/src/App/Common/ModalContainer.tsx, apps/namadillo/src/App/Common/TopNavigation.tsx, apps/namadillo/src/App/Settings/SettingsPanel.tsx, apps/namadillo/src/App/SignMessages/SignMessages.tsx, apps/namadillo/src/App/SignMessages/routes.ts, apps/namadillo/src/atoms/arbitraryMessages.ts, apps/namadillo/src/hooks/useModalCloseEvent.ts
This PR enables arbitrary messages in Namadillo interface. To sign messages, you must enable this feature in the settings panel.
Fixes: #906
=> Namadillo: Sign Arbitrary Messages

README.md, e2e/setup-frontend.sh, e2e/setup-namada.sh
Rename `apps/namada-interface` to `apps/namadillo`
=> chore: update references of namada-interface to namadillo

apps/extension/src/App/index.tsx, apps/extension/src/background/approvals/service.ts, packages/components/src/Checkbox.tsx, packages/components/src/Container.tsx, packages/components/src/KeyListItem.tsx
This PR fixes the following issues:
- Closes #831 
- Closes #782 
- Closes #857
=> Extension: General fixes

README.md, apps/namadillo/README.md
This PR updates the instructions to set up Namadillo locally and also adds a section on how to host it.
Closes #772
=> Namadillo: Updating Docs

apps/namadillo/src/App/Governance/AllProposalsTable.tsx, apps/namadillo/src/App/Governance/LiveGovernanceProposals.tsx, apps/namadillo/src/App/Governance/ProposalHeader.tsx, apps/namadillo/src/App/Governance/ProposalLabels.tsx, apps/namadillo/src/App/Governance/VoteInfoCards.tsx, apps/namadillo/src/utils/index.ts, packages/utils/src/helpers/index.ts
- Show real dates/times for proposals instead of epochs
- Show the time remaining for ongoing proposals
=> feat: show real times, time remaining for proposals

apps/namadillo/package.json, apps/namadillo/src/atoms/proposals/atoms.ts, apps/namadillo/src/atoms/proposals/functions.ts, apps/namadillo/src/atoms/validators/services.ts, yarn.lock
Just simple rename and client bump 🙏
=> refactor: rename data.data to data.results

apps/extension/package.json
Bump the Extension version to 0.3.0
=> chore: bump extension to 0.3.0

apps/namadillo/src/App/AppSetup.tsx, apps/namadillo/src/App/Common/ErrorBox.tsx
Resolves https://github.com/anoma/namada-interface/issues/970 adding the link to update the Indexer Url
=> feat: allow to change the indexer url on error

apps/namadillo/src/App/Sidebars/ValidatorDiversification.tsx
=> fix: make "Learn about CPoS" link open in new tab

apps/namadillo/src/App/Common/Container.tsx, apps/namadillo/src/App/Common/Intro.tsx, apps/namadillo/src/App/Common/Navigation.tsx, apps/namadillo/src/App/Common/PageWithSidebar.tsx, apps/namadillo/src/App/Common/Setup.tsx, apps/namadillo/src/App/Sidebars/ProposalDiscord.tsx
Closes https://github.com/anoma/namada-interface/issues/965
Closes https://github.com/anoma/namada-interface/issues/966
Visual tweaks on connect extension page
=> feat: visual tweaks on connect extension page

apps/extension/src/Approvals/Commitment.tsx, apps/namadillo/src/App/Governance/GovernanceOverview.tsx, apps/namadillo/src/App/Settings/Advanced.tsx, apps/namadillo/src/App/Settings/SettingsSignArbitrary.tsx, apps/namadillo/src/App/Sidebars/ProposalDiscord.tsx, apps/namadillo/src/App/Sidebars/ValidatorDiversification.tsx, apps/namadillo/src/App/Staking/AllValidatorsTable.tsx, apps/namadillo/src/App/Staking/BondingAmountOverview.tsx, apps/namadillo/src/App/Staking/IncrementBonding.tsx, apps/namadillo/src/App/Staking/IncrementBondingTable.tsx, apps/namadillo/src/App/Staking/MyValidatorsTable.tsx, apps/namadillo/src/App/Staking/ReDelegate.tsx, apps/namadillo/src/App/Staking/ReDelegateAssignStake.tsx, apps/namadillo/src/App/Staking/ReDelegateRemoveStake.tsx, apps/namadillo/src/App/Staking/ReDelegateTable.tsx, apps/namadillo/src/App/Staking/UnbondingAmountsTable.tsx, apps/namadillo/src/App/Staking/Unstake.tsx, apps/namadillo/src/App/Staking/UnstakeBondingTable.tsx, apps/namadillo/src/App/Staking/ValidatorFilterNav.tsx, apps/namadillo/src/hooks/useTransactionNotifications.tsx, storybook/src/stories/StyledTable.stories.tsx
=> fix: fix up Namadillo text spelling/grammar

apps/namadillo/src/App/Settings/SettingsPanel.tsx
Render the version number on the Settings page
=> feat: render the version number

apps/namadillo/src/App/App.tsx, apps/namadillo/src/App/Common/AppContainer.tsx, apps/namadillo/src/App/Common/Container.tsx, apps/namadillo/src/App/Common/SyncIndicator.tsx, apps/namadillo/src/App/Common/TopNavigation.tsx, apps/namadillo/src/App/Common/WalletAddress.tsx, apps/namadillo/src/App/Staking/UnbondingAmountsTable.tsx, apps/namadillo/src/atoms/syncStatus/atoms.ts, packages/components/src/Tooltip.tsx
Add the Sync Indicator
Closes #991
=> feat: add the sync indicator

apps/extension/src/manifest/v2/_base.json
=> fix: remove unused Firefox extension permissions

apps/faucet/src/utils/api.ts, apps/namadillo/src/App/Common/AppContainer.tsx, apps/namadillo/src/App/Common/FiatCurrency.tsx, apps/namadillo/src/App/Common/NamCurrency.tsx, apps/namadillo/src/App/Common/TopNavigation.tsx, apps/namadillo/src/atoms/settings/atoms.ts, apps/namadillo/src/types.d.ts
=> feat/1009 - Namadillo: Remove hide balances feature

apps/namadillo/src/App/Settings/SettingsMain.tsx, apps/namadillo/src/App/Settings/SettingsPanel.tsx
Render Chain ID on Settings page
=> feat: render chain id

apps/namadillo/src/App/Common/ActiveAccount.tsx, apps/namadillo/src/App/Common/SyncIndicator.tsx, apps/namadillo/src/App/Common/WalletAddress.tsx, packages/components/src/Tooltip.tsx
=> feat: add account address tooltip

packages/components/src/StyledTableHead.tsx
Removes selection from table headers and fixes #1031
=> Namadillo: removing selection from table header

apps/extension/src/App/App.tsx, apps/extension/src/context/AccountContext.tsx, apps/extension/src/context/VaultContext.tsx
This fixes a Firefox bug where the saved password prompt pops up when opening the unlocked extension.
Fixes #968.
=> fix: don't flash lock screen when opening extension

apps/namadillo/src/App/Common/SyncIndicator.tsx, apps/namadillo/src/hooks/useChainStatus.tsx, packages/hooks/src/index.ts, packages/hooks/src/useSSE.ts
Added height and epoch to the sync status tooltip just for a sake of displaying it somewhere
Test with [this](https://github.com/anoma/namada-indexer/pull/107) or wait for it to merge :)
https://github.com/user-attachments/assets/4413bcec-9f59-407e-aa1c-39537f63957a
=> feat: chain status hook

apps/extension/package.json
=> chore: bump extension to 0.3.1

apps/namadillo/src/App/Governance/GovernanceOverview.tsx, apps/namadillo/src/App/Governance/LiveGovernanceProposals.tsx, apps/namadillo/src/App/Governance/ProposalHeader.tsx, apps/namadillo/src/App/Governance/ProposalLabels.tsx, apps/namadillo/src/atoms/proposals/atoms.ts, apps/namadillo/src/atoms/proposals/functions.ts, apps/namadillo/src/atoms/syncStatus/atoms.ts, packages/components/src/theme.ts
Closes #1054.
Example of the different labels:
=> feat: add vote type to voted label

.github/workflows/release-wallet.yml
Fix CI due to extension name change
=> fix - CI should reflect extension name change

.github/workflows/deploy-wallet-at-merge-to-main.yml
=> fix: Merge to main should point to correct extension assets

apps/namadillo/src/App/Common/NamInput.tsx, apps/namadillo/src/App/Staking/AllValidatorsTable.tsx, apps/namadillo/src/App/Staking/AmountField.tsx, apps/namadillo/src/App/Staking/IncrementBonding.tsx, apps/namadillo/src/App/Staking/IncrementBondingTable.tsx, apps/namadillo/src/App/Staking/MyValidatorsFilter.tsx, apps/namadillo/src/App/Staking/ReDelegateAssignStake.tsx, apps/namadillo/src/App/Staking/ReDelegateRemoveStake.tsx, apps/namadillo/src/App/Staking/ReDelegateTable.tsx, apps/namadillo/src/App/Staking/UnstakeBondingTable.tsx, apps/namadillo/src/App/Staking/ValidatorCard.tsx, apps/namadillo/src/App/Staking/ValidatorFilterNav.tsx, apps/namadillo/src/App/Staking/ValidatorThumb.tsx, apps/namadillo/src/App/Staking/__tests__/AmountField.test.tsx, apps/namadillo/src/App/Staking/__tests__/MyValidatorsFilters.test.tsx, apps/namadillo/src/App/Staking/__tests__/ValidatorCard.test.tsx, apps/namadillo/src/App/Staking/__tests__/ValidatorRank.test.tsx, apps/namadillo/src/hooks/__tests__/useValidatorFilter.test.ts, apps/namadillo/src/hooks/useValidatorFilter.tsx, apps/namadillo/src/test-utils.tsx, apps/namadillo/src/types.d.ts, packages/components/src/StyledSelectBox.tsx
This PR adds validator status to staking tables, removes the "randomize" button, and adds different warnings and elements depending on validator status.
Fixes #1040 .
=> Namadillo: Adding Staking filters and different states

apps/namadillo/src/App/AccountOverview/AccountOverview.tsx, apps/namadillo/src/App/AppRoutes.tsx, apps/namadillo/src/App/Sidebars/MainnetRoadmap.tsx, apps/namadillo/src/App/Sidebars/ShieldAllBanner.tsx, apps/namadillo/src/App/Transfer/ShieldAll.tsx, apps/namadillo/src/App/Transfer/Transfer.tsx, apps/namadillo/src/App/Transfer/index.ts, apps/namadillo/src/App/Transfer/routes.ts
Create the shield all banner and page
=> feat: create the shield all banner and page

apps/namadillo/src/App/AccountOverview/AccountOverview.tsx, apps/namadillo/src/App/Governance/GovernanceOverview.tsx, apps/namadillo/src/App/Staking/AllValidatorsTable.tsx, apps/namadillo/src/App/Staking/StakingOverview.tsx, apps/namadillo/src/hooks/useUserHasAccount.ts, apps/namadillo/src/theme.ts
This PR fixes some errors when user is connected to the extension but doesn't have an account created.
These errors were happening in the Overview, Staking and Governance sections.
=> Namadillo: fixing general connection errors

apps/namadillo/src/App/Governance/SubmitVote.tsx
=> fix: add processing state to submit vote button

apps/namadillo/src/registry/index.ts
=> fix: registry index check

apps/namadillo/src/App/Transfer/CustomAddressForm.tsx, apps/namadillo/src/App/Transfer/Example.tsx, apps/namadillo/src/App/Transfer/ExampleFromNamada.tsx, apps/namadillo/src/App/Transfer/SelectedWallet.tsx, apps/namadillo/src/App/Transfer/TransferDestination.tsx, apps/namadillo/src/App/Transfer/TransferModule.tsx, apps/namadillo/src/App/Transfer/__tests__/TransferDestination.test.tsx, apps/namadillo/src/App/Transfer/common.ts
This is one more PR for transfer module. It refactors the props passed to the transfer module, adds another example of use, fix a few bugs, and adds custom address field.
=> Namadillo: Transfer Module - Part 3

apps/extension/src/manifest/v2/_base.json, apps/extension/src/public/approvals.html, apps/extension/src/public/popup.html, apps/extension/src/public/setup.html
Renamed in HTML page titles and Firefox manifest.json.
=> fix: rename remaining instances of Namada Extension

packages/sdk/README.md, packages/sdk/docs/classes/Crypto.md, packages/sdk/docs/classes/Ledger.md, packages/sdk/docs/classes/Masp.md, packages/sdk/docs/classes/Mnemonic.md, packages/sdk/docs/classes/Rpc.md, packages/sdk/docs/classes/Sdk.md, packages/sdk/docs/classes/Signing.md, packages/sdk/docs/classes/Tx.md, packages/sdk/docs/enums/KdfType.md, packages/sdk/docs/modules.md, packages/sdk/src/mnemonic.ts
- Update SDK `README.md`
- Removed `async` / `Promise` from `sdk.mnemonic.generate()` function
- Regenerated the docs
[README.md Preview](https://github.com/anoma/namada-interface/blob/0b53c6d81e9c2e0878b487b762f1840b46f9f28e/packages/sdk/README.md)
=> docs: Updating SDK README

packages/shared/lib/Cargo.lock, packages/shared/lib/Cargo.toml
Bumps to Namada 0.44.1. No other changes needed to build.
=> chore: bump to namada 0.44.1

packages/components/src/TabContainer.tsx, packages/components/src/index.ts, storybook/src/stories/TabContainer.stories.tsx
This PR creates a simple <TabContainer> component in order to manage tabs and their contents.
=> Components: create TabContainer component

apps/namadillo/package.json, apps/namadillo/src/atoms/chain/functions.ts, yarn.lock
Depends on https://github.com/anoma/namada-indexer/pull/131
=> feat: add cubic_slashing_window_length

packages/sdk/src/tx/tx.ts, packages/shared/lib/src/query.rs, packages/shared/lib/src/sdk/args.rs, packages/shared/lib/src/sdk/transaction.rs, packages/shared/lib/src/sdk/tx.rs
=> feat: support decoding ibc tx details in sdk

apps/namadillo/src/App/Common/InlineError.tsx, apps/namadillo/src/App/Ibc/IbcTransfer.tsx, apps/namadillo/src/App/Transfer/TransferModule.tsx
This PR adds some nice ways to handle errors on IBC Transfer and a warning on TransferModule showing why the submit button is disabled.
=> Namadillo: handling errors on IBC transfer form

apps/namadillo/package.json, apps/namadillo/src/atoms/fees/services.ts, yarn.lock
Gets the latest API for gas limit
=> chore: Bumping namada-indexer version

packages/components/src/ActionButton.tsx
=> fix: make blob URLs links to fix WASM button

apps/namadillo/src/App/Ibc/IbcTransfer.tsx, apps/namadillo/src/App/Ibc/IbcWithdraw.tsx, apps/namadillo/src/App/Transactions/TransferTransactionTimeline.tsx, apps/namadillo/src/atoms/integrations/functions.ts, apps/namadillo/src/hooks/useWalletManager.tsx, apps/namadillo/src/types.ts
Theta Cosmos Testnet will be [deprecated](https://forum.cosmos.network/t/theta-testnet-001-will-be-deprecated-as-of-dec-1-2024/14679) by 1st of December, so we're replacing it by Provider.
=> Namadillo: replacing Theta testnet by provider

apps/namadillo/src/App/NamadaTransfer/NamadaTransfer.tsx, apps/namadillo/src/App/NamadaTransfer/NamadaTransferTopHeader.tsx, apps/namadillo/src/hooks/useTransaction.tsx, apps/namadillo/src/utils/index.ts
This fixes #1288 and also make some tweaks on error handling and timeline stages. This is one more step forward on Transfer page development.
=> Namadillo: fixing amount conversion and timeline stage

apps/namadillo/src/App/Sidebars/MainnetRoadmap.tsx, apps/namadillo/src/App/Sidebars/RoadmapPhase.tsx
Uses the phases enabled in the registry to highlight the timeline
This fixes #1265
=> Namadillo: Conditionally highlight each phase on the roadmap

apps/namadillo/src/App/Ibc/IbcWithdraw.tsx, apps/namadillo/src/App/Transfer/TransferModule.tsx, apps/namadillo/src/types/events.ts
This adds a few different states and improvements to IBC Withdraw page.
This is one more step forward on #1179
=> Namadillo: Withdraw Tweaks

apps/namadillo/src/App/NamadaTransfer/NamadaTransfer.tsx, apps/namadillo/src/atoms/transfer/atoms.ts, apps/namadillo/src/atoms/transfer/services.ts, apps/namadillo/src/hooks/useTransaction.tsx, apps/namadillo/src/hooks/useTransactionActions.ts, apps/namadillo/src/hooks/useTransactionCallbacks.tsx, apps/namadillo/src/lib/query.ts, apps/namadillo/src/lib/transactions.ts, apps/namadillo/src/types.ts
This PR includes some fixes to Namada transfer page, and a bit of refactor.
Fixes #1307 
Fixes #1291
=> Namadillo: Transfer review and fixes

apps/namadillo/src/App/Staking/Unstake.tsx
Filter the zeroed unstaking entries on submit
Fixes #1313
=> fix(namadillo): filtering zero values in order to avoid errors

apps/namadillo/src/App/Common/BalanceChart.tsx, apps/namadillo/src/App/Staking/AllValidatorsTable.tsx, apps/namadillo/src/App/Staking/BondingAmountOverview.tsx, apps/namadillo/src/App/Staking/MyValidatorsTable.tsx, apps/namadillo/src/App/Staking/StakingOverview.tsx, apps/namadillo/src/App/Staking/StakingRewardsPanel.tsx, apps/namadillo/src/App/Staking/StakingSummary.tsx
Small tweaks on Staking:
- Fix scrollbar on overview
- Reduce number of decimal places in some areas
=> Namadillo: Few Staking Tweaks

apps/namadillo/src/App/Masp/ShieldedNamBalance.tsx
=> feat: update copy shielding

apps/extension/src/App/Accounts/DeleteAccount.tsx, apps/extension/src/App/Accounts/ViewMnemonic.tsx, apps/extension/src/App/Accounts/ViewingKey.tsx, apps/extension/src/App/AppContent.tsx, apps/extension/src/App/Settings/Warnings.tsx, apps/extension/src/Setup/Common/Bip44Form.tsx, apps/extension/src/Setup/Ledger/LedgerConnect.tsx, apps/extension/src/Setup/index.tsx, apps/extension/src/global.css
Resolves #1229 
- Viewing key padding
- Derivation Path number input - remove buttons
- Firefox - Viewing Key form width (certain elements cause the width to expand in FF - I set this on a higher-level element and removed individual overrides - This could perhaps be improved in the future, but gives us good results across browsers, and can now be changed in a single place!)
=> feat/1229: Extension style improvements - v0.3.3

apps/namadillo/src/App/Staking/ValidatorInfoPanel.tsx
=> feat: update copy approximate

apps/namadillo/src/App/Ibc/IbcTransfer.tsx, apps/namadillo/src/App/Ibc/IbcWithdraw.tsx, apps/namadillo/src/App/NamadaTransfer/NamadaTransfer.tsx, apps/namadillo/src/App/Transfer/AvailableAmountFooter.tsx, apps/namadillo/src/App/Transfer/TransferModule.tsx, apps/namadillo/src/atoms/integrations/functions.ts
- Simplifying `mapCoinsToAssets` code
- Checking for `baseDenom` on chain registry, so if we don't have the channel added to the registry, it might display everything correct
- Improvements on Namada transfer timeline
=> Namadillo: Reviewing transaction timelines and fixing a few things

apps/namadillo/src/App/Sidebars/ValidatorDiversification.tsx
This PR changes the url to namada.net/staking
=> Namadillo: preparing stake info with the correct url

apps/namadillo/package.json, package.json
Let's release Namadillo v1.0.0
=> chore: Namadillo -> 1.0.0

apps/extension/package.json, packages/sdk/package.json, packages/sdk/src/ledger.ts, yarn.lock
=> fix: SDK and extension should use the same ledger-namada package

apps/namadillo/package.json, apps/namadillo/src/lib/query.ts, packages/sdk/src/tx/tx.ts, packages/shared/lib/src/sdk/tx.rs, packages/types/src/tx/schema/txDetails.ts
=> BUG: SDK - Remove empty string memos

apps/namadillo/src/App/Transfer/TransferModule.tsx, apps/namadillo/src/atoms/transfer/atoms.ts, apps/namadillo/src/atoms/transfer/services.ts, apps/namadillo/src/lib/transactions.ts
=> fix: do not use empty string memos by default - in transfers

apps/extension/package.json, apps/extension/src/App/Accounts/ParentAccounts.tsx, apps/extension/src/App/Accounts/ParentAccountsFooter.tsx, apps/extension/src/App/AppContent.tsx, packages/components/src/ActionButton.tsx
=> feat/1383: Extension - Add apps link to accounts view

apps/namadillo/README.md
=> docs: fix typo on readme file

specs/browser-extension/integration.md
Updated [integration.md](https://github.com/anoma/namada-interface/blob/cadd4671c831810f4de87a0c98fc8ebdaf43b6af/specs/browser-extension/integration.md)
=> docs: Updating Namada Keychain specs

apps/namadillo/package.json, apps/namadillo/src/atoms/proposals/atoms.ts, yarn.lock
With this change we only query bonds that are active at certain epoch.
=> fix: query only relevant bonds to see if it's possible to vote

apps/extension/FIREFOX_README.md
Preview: https://github.com/anoma/namada-interface/blob/ecec95bfde747b8115ae3a398caf693ad6010201/apps/extension/FIREFOX_README.md
- Added note about architecture
- Clean-up
=> docs: Extension: Tweaks to Firefox Readme

apps/namadillo/package.json, packages/components/src/ActionButton.tsx
Fix outline on disabled button
=> fix: fix outline on disabled button

apps/namadillo/package.json, apps/namadillo/src/atoms/integrations/functions.ts, apps/namadillo/src/hooks/useRegistryFeatures.tsx, yarn.lock
See: https://github.com/anoma/namada-chain-registry/pull/26
See: https://testnet.housefire.tududes.com/
=> feat: Namadillo - Update for new housefire

apps/namadillo/src/App/Common/IconTooltip.tsx, apps/namadillo/src/App/Staking/IncrementBondingTable.tsx, apps/namadillo/src/lib/staking.ts
Adds a small tooltip warning. if the validator is on the top 10 list.
Closes #1445
=> Namadillo: Showing warning for top validators on staking

apps/namadillo/src/App/Ibc/IbcTransfer.tsx, apps/namadillo/src/App/Ibc/IbcWithdraw.tsx, apps/namadillo/src/hooks/useIbcTransaction.tsx
Redirects transfer and withdraw to timeline page, which will be refactored in a later PR
=> Namadillo: refactoring ibc transfer and withdraw to redirect to timeline page

apps/namadillo/src/App/Transfer/TransferModule.tsx
=> Namadillo: re-enable wallet popup

apps/namadillo/package.json, apps/namadillo/src/App/Masp/MaspShield.tsx, apps/namadillo/src/App/Masp/MaspUnshield.tsx, apps/namadillo/src/App/NamadaTransfer/NamadaTransfer.tsx
After signing a Namada transfer, redirects user to the transaction page.
This is mimicking the new implementation done on Ibc Transfers.
Please, notice this is not upgrading the timeline steps, neither the notifications. So existing issues are still happening. They will be addresses in the next PRs
=> feat: redirect to tx page

apps/namadillo/src/App/Common/Timeline.tsx, apps/namadillo/src/App/Ibc/IbcTransfersLayout.tsx, apps/namadillo/src/atoms/integrations/services.ts, apps/namadillo/src/atoms/notifications/functions.ts, apps/namadillo/src/hooks/useIbcTransaction.tsx, apps/namadillo/src/hooks/useTransactionNotifications.tsx, apps/namadillo/src/types/events.ts
Adding IBC notifications events when transaction gets confirmed or fails for any reason
=> Namadillo: adding ibc notifications

apps/namadillo/package.json, apps/namadillo/src/App/AccountOverview/AccountOverview.tsx, apps/namadillo/src/App/AccountOverview/BalanceOverviewChart.tsx, apps/namadillo/src/App/AccountOverview/NamBalanceContainer.tsx, apps/namadillo/src/App/Masp/ShieldedBalanceChart.tsx
Update balances disclaimer to be visible only before phase 5
Also, add the panel labels
closes #1463
**Phase 2**
**Phase 3**
=> feat: update balances disclaimer

packages/sdk/CHANGELOG.md, packages/sdk/package.json
Committing the changes from the SDK release
- `package.json`
- `CHANGELOG.md`
=> chore: SDK 0.14.0 release update

.github/workflows/release-wallet.yml
Fixes issue where Revision is blank in extension when built from workflow action.
=> fix: Update Extension Release workflow with correct var

apps/namadillo/src/App/Common/Timeline.tsx
Adding initial animation and also fixes centering on success animation
=> Namadillo: improving start animation

apps/namadillo/src/App/AccountOverview/NamBalanceContainer.tsx
Very simple PR to fix the height of the NamBalanceContainer
=> Namadillo: fixing nam balance container height overflow

apps/namadillo/src/App/Ibc/IbcTransfer.tsx, apps/namadillo/src/App/Transfer/TransferModule.tsx, apps/namadillo/src/atoms/integrations/atoms.ts, apps/namadillo/src/atoms/integrations/services.ts, apps/namadillo/src/hooks/useIbcTransaction.tsx, apps/namadillo/src/utils/address.ts, apps/namadillo/src/utils/ibc.ts
Describes better on which stage of the transaction is being processed
=> Namadillo: more stages to IBC transactions

apps/namadillo/src/App/Masp/MaspShield.tsx, apps/namadillo/src/App/Masp/MaspUnshield.tsx, apps/namadillo/src/App/Transfer/TransferModule.tsx
This PR adds the possibility of override default button texts to improve error readability
=> feat: add the possibility of overriding button error texts

apps/namadillo/src/App/Common/MaspContainer.tsx, apps/namadillo/src/App/Common/MaspSyncCover.tsx, apps/namadillo/src/App/Common/PulsingRing.tsx, apps/namadillo/src/App/Masp/MaspLayout.tsx, apps/namadillo/src/App/Masp/ShieldedBalanceChart.tsx, apps/namadillo/src/App/Masp/ShieldedNamBalance.tsx, apps/namadillo/src/App/Masp/ShieldedOverviewPanel.tsx, apps/namadillo/src/App/Settings/SettingsMASP.tsx, apps/namadillo/src/atoms/balance/atoms.ts, apps/namadillo/src/hooks/useRequiresNewShieldedSync.tsx, packages/components/src/ActionButton.tsx, packages/components/src/PieChart.tsx
This PR improves some MASP loading states, fixes errors and introduces a new animation for masp loading
=> feat: improving masp loading states

apps/namadillo/src/App/Common/TransactionReceipt.tsx, apps/namadillo/src/App/Common/WalletAddress.tsx, apps/namadillo/src/App/Ibc/IbcTransfer.tsx, apps/namadillo/src/App/Ibc/IbcWithdraw.tsx, apps/namadillo/src/App/Ibc/ShieldAllPanel.tsx, apps/namadillo/src/App/Masp/MaspShield.tsx, apps/namadillo/src/App/Masp/MaspUnshield.tsx, apps/namadillo/src/App/NamadaTransfer/NamadaTransfer.tsx, apps/namadillo/src/App/Transactions/TransactionDetails.tsx, apps/namadillo/src/App/Transfer/CurrentStatus.tsx, apps/namadillo/src/App/Transfer/SelectedWallet.tsx, apps/namadillo/src/App/Transfer/SuccessAnimation.tsx, apps/namadillo/src/App/Transfer/TokenAmountCard.tsx, apps/namadillo/src/App/Transfer/TransferArrow.tsx, apps/namadillo/src/App/Transfer/TransferDestination.tsx, apps/namadillo/src/App/Transfer/TransferModule.tsx, apps/namadillo/src/App/Transfer/TransferSource.tsx, apps/namadillo/src/App/Transfer/__tests__/SelectedWallet.test.tsx, apps/namadillo/src/App/Transfer/common.ts, apps/namadillo/src/atoms/integrations/functions.ts, apps/namadillo/src/hooks/useIbcTransaction.tsx, apps/namadillo/src/hooks/useSimulateIbcTransferFee.ts, apps/namadillo/src/hooks/useTransfer.ts, apps/namadillo/src/lib/transactions.ts, apps/namadillo/src/theme.ts, apps/namadillo/src/types.ts
This PR contains an improved version of the transfer module, separating the submit process into different steps and with a new success animation. It also adds a new structure for transaction receipt, when you check the history of transactions
=> feat: several improvements on Transfer Module and transaction receipts

apps/namadillo/src/App/Staking/StakingRewards.tsx
Render Claim Rewards error
closes #1447
=> feat: render claim error

apps/namadillo/src/atoms/transfer/atoms.ts
We need to do shielded sync before unshielding/shielded transfer.
Otherwise it might happen that between shielded sync(in namadillo) and transfer(in namadillo) someone will send another transfer using CLI(or some other way) and namadillo will end up with invalid shielded context and transfer will fail.
=> feat: shielded sync before masp tx

apps/faucet/src/index.css, packages/components/package.json, packages/components/src/base.css, yarn.lock
Loading Space Grotesk fonts from local build instead of Google servers
Fixes #1649
=> fix: loading Space Grotesk font from local build

packages/components/src/ActionButton.tsx
=> fix: fixing ActionButton z-index error

.github/ISSUE_TEMPLATE/namadillo.yml, apps/namadillo/src/App/Layout/Navigation.tsx, apps/namadillo/src/urls.ts
This PR adds a template form for Github issues and a visible link for bug report on the main navigation menu
=> feat: adding bug report button and template

apps/namadillo/src/App/Transfer/TransferModule.tsx
This PR sorts the available assets from the user wallet, so the fee tokens appear first according to cosmos chain-registry order.
=> feat: sorting assets on transfer module

apps/namadillo/src/atoms/integrations/services.ts, apps/namadillo/src/hooks/useTransactionCallbacks.tsx, apps/namadillo/src/hooks/useTransactionNotifications.tsx, apps/namadillo/src/hooks/useTransactionWatcher.tsx, apps/namadillo/src/types/events.ts, apps/namadillo/src/utils/http.ts
This PR fixes a few things that happen in Namadillo after a transfer is broadcasted.
=> refactor: refactoring transaction events and refreshing balance after IBC transfers

apps/namadillo/src/App/AccountOverview/TransparentOverviewPanel.tsx, apps/namadillo/src/App/Common/GasFeeModal.tsx, apps/namadillo/src/App/Masp/ShieldedFungibleTable.tsx
Add token address as html title to help debug and understand different balances from different channels
It could be a border case, but at least helps other users to identify if this is one of the reasons we insufficient balances to pay the fees
https://github.com/user-attachments/assets/1b75beaa-c92d-4bb6-a3bc-d1e68be6709e
https://github.com/user-attachments/assets/20ca3579-1a15-4b92-94df-a099595bcf48
=> feat: add token address as html title

apps/namadillo/package.json, apps/namadillo/src/atoms/balance/services.ts, apps/namadillo/src/atoms/transfer/atoms.ts, apps/namadillo/src/index.tsx, apps/namadillo/src/sw.ts, apps/namadillo/vite.config.mjs, packages/shared/lib/src/query.rs, yarn.lock
Best way to test this is probably by wrapping
```ts
console.time("fetchShieldedBalance");
const response = await fetchShieldedBalance(
viewingKey,
chainTokens,
chainId
);
console.timeEnd("fetchShieldedBalance");
```
and commenting out:
```ts
navigator.serviceWorker.register(
import.meta.env.MODE === "production" ? "/sw.js" : "/dev-sw.js?dev-sw",
{ type: import.meta.env.MODE === "production" ? "classic" : "module" }
);
```
**Service worker does not work in dev firefox, I've added a comment about it in the code.**
=> feat: service worker fetch cache

apps/namadillo/src/utils/dates.ts
Fix time remaining fraction digits
closes #1634
=> fix: fix time remaining fraction digits

apps/namadillo/src/compatibility.json, apps/namadillo/src/hooks/useCompatibilityErrors.tsx
=> fix: Bump keychain compatibility for Namadillo

apps/extension/src/background/keyring/keyring.ts
=> fix: pass proper path to deriveShieldedFromSeed

apps/namadillo/src/App/Governance/ProposalDescription.tsx
Remove trailing period on urls
This fixes the url on proposal like this one https://interface.namada.tududes.com/governance/proposal/8
=> fix: remove trailing period on urls

apps/namadillo/vite.config.mjs, docker/namadillo/nginx.conf
=> feat: credentialless header

apps/namadillo/src/App/Transfer/TransferModule.tsx, apps/namadillo/src/utils/assets.ts
With recent changes on indexer, a few zeroed assets are being returned from the balances endpoint. This PR filters those out.
=> feat: filtering assets with zero amount in it

packages/components/src/Modal.tsx
=> fix: reducing modal zindex to avoid conflicts with notification badges

apps/namadillo/src/App/AccountOverview/TransparentOverviewPanel.tsx
fix for accounts with all tokens with balance zero
=> fix: fix for accounts with all tokens with balance zero

apps/namadillo/package.json, apps/namadillo/src/App/Governance/ProposalHeader.tsx, apps/namadillo/src/App/Governance/ViewJson.tsx, apps/namadillo/src/App/Governance/VoteInfoCards.tsx, apps/namadillo/src/atoms/proposals/atoms.ts, apps/namadillo/src/atoms/proposals/functions.ts, packages/types/src/proposals.ts, yarn.lock
Indexer is already returning a hash and we have to use separate endpoint to get the data.
=> fix: proposals checksums and data download

apps/namadillo/src/App/Sidebars/ShieldAllBanner.tsx
Add shield assets modal on sidebar banner
Closes https://github.com/anoma/namada-interface/issues/1723
https://github.com/user-attachments/assets/b769f167-4387-4992-814e-2274186236a9
=> feat: add shield assets modal on sidebar banner

apps/namadillo/src/App/Common/AlphaVersionTopHeader.tsx
Small tweak on text for clarity
=> fix: updating alpha banner text

apps/namadillo/src/App/Staking/StakingRewards.tsx
Fix claim and stake fee inverted
=> fix: fix claim and stake fee inverted

apps/namadillo/src/App/Common/ConnectPanel.tsx
=> chore: fix up connect panel text hierarchy when not connected

apps/namadillo/src/App/Ibc/IbcWithdraw.tsx, apps/namadillo/src/App/Transfer/TransferModule.tsx
https://github.com/user-attachments/assets/555e0948-8edf-4480-b4cb-1e775967e012
Closes #1752
=> fix: cleanup Keplr connect button functionality in Withdraw module

apps/namadillo/src/App/AccountOverview/TransparentOverviewPanel.tsx
=> fix: move stake button when transfer's locked

apps/namadillo/src/compatibility.json
Adding a more flexible indexer compatibility range
=> chore: bumping indexer versioning

apps/extension/src/App/Accounts/UpdateRequired.tsx, apps/namadillo/src/App/Common/GasFeeModal.tsx, apps/namadillo/src/App/Common/SelectModal.tsx, apps/namadillo/src/App/Common/SelectOptionModal.tsx, apps/namadillo/src/App/Layout/KeplrAccount.tsx, apps/namadillo/src/App/Layout/NamadaAccount.tsx, apps/namadillo/src/App/Settings/SettingsPanel.tsx, apps/namadillo/src/App/Staking/StakingRewards.tsx, apps/namadillo/src/App/Staking/ValidatorInfoPanel.tsx, apps/namadillo/src/App/SwitchAccount/SwitchAccountPanel.tsx, packages/components/src/InsetLabel.tsx, packages/components/src/Modal.tsx, packages/components/src/Panel.tsx, packages/components/src/StyledSelectBox.tsx, packages/components/src/StyledTableRow.tsx, packages/components/src/ToggleButton.tsx, packages/components/src/Tooltip.tsx, packages/components/src/theme.ts, storybook/src/stories/AmountSummaryCard.stories.tsx
=> feat: tweaking black color on all apps

apps/namadillo/src/App/Staking/MyValidatorsFilter.tsx, apps/namadillo/src/App/Staking/ValidatorRank.tsx, apps/namadillo/src/App/Staking/__tests__/ValidatorRank.test.tsx
=> feat: add active below threshold trait

apps/namadillo/src/App/Masp/ShieldedFungibleTable.tsx, apps/namadillo/src/App/Masp/ShieldedNamBalance.tsx, apps/namadillo/src/App/Masp/ShieldedOverviewPanel.tsx, apps/namadillo/src/App/Masp/ShieldedRewardsBox.tsx, apps/namadillo/src/atoms/balance/atoms.ts, apps/namadillo/src/atoms/balance/services.ts, packages/sdk/src/rpc/rpc.ts, packages/shared/lib/src/sdk/mod.rs
Add shielded assets rewards
Closes #1745
=> feat: add rewards column

apps/namadillo/src/hooks/useIbcTransaction.tsx, apps/namadillo/src/lib/transactions.ts
Closes #1665 
@pedrorezende @euharrison
=> fix: Update IBC transfer message

.github/ISSUE_TEMPLATE/namadillo.yml, apps/namadillo/src/App/AppRoutes.tsx, apps/namadillo/src/App/Common/BugReport.tsx, apps/namadillo/src/App/Layout/Navigation.tsx, apps/namadillo/src/App/routes.ts, apps/namadillo/src/atoms/settings/atoms.ts, apps/namadillo/src/atoms/settings/services.ts
This PR opens a new page for bug report, where useful information could be parsed and added directly to bug report form on Github
Closes #1823
=> feat: improving bug report info gathering

apps/namadillo/src/App/Transfer/TransferDestination.tsx
=> fix: displaying on the loading panel the correct target address

apps/namadillo/src/App/Common/TransactionFee.tsx, apps/namadillo/src/App/Common/TransactionFeeButton.tsx, apps/namadillo/src/App/Transfer/__tests__/TransferDestination.test.tsx
Update transaction fee button to be more evident that user can change the token and the gas limit
Closes https://github.com/anoma/namada-interface/issues/1834
=> feat: update transaction fee button

apps/namadillo/src/atoms/fees/atoms.ts, apps/namadillo/src/utils/gas.ts
Closes https://github.com/anoma/namada-interface/issues/1848
=> feat: hide gas tokens without asset definition

apps/namadillo/src/App/Common/TransactionFeeButton.tsx, apps/namadillo/src/App/Transfer/TransferDestination.tsx
=> fix: fix transaction fee layout

apps/namadillo/src/hooks/useTransaction.tsx, apps/namadillo/src/hooks/useTransactionFee.ts
If the user doesn't have NAM tokens, we set other tokens as default token to pay for fees
Fixes #1787
=> feat: falling back to other fee tokens if user has no nams

apps/namadillo/src/App/Common/GasFeeModal.tsx, apps/namadillo/src/App/Staking/StakingWithdrawModal.tsx, packages/components/src/StyledSelectBox.tsx
=> feat: improving token selection modal

apps/namadillo/src/App/Ibc/IbcTransfersLayout.tsx, packages/components/src/TabContainer.tsx
Fixes #1850 and also some wrong rounded corners
=> feat: changing tab and text colors on TabContainer

apps/namadillo/src/App/AccountOverview/BalanceOverviewChart.tsx, apps/namadillo/src/App/Common/BalanceChart.tsx, apps/namadillo/src/App/Common/OpacitySlides.tsx, apps/namadillo/src/App/Sidebars/YourStakingDistribution.tsx, apps/namadillo/src/App/Staking/StakingSummary.tsx
Update Overview and Staking chart rollover state
Closes https://github.com/anoma/namada-interface/issues/1854
Closes https://github.com/anoma/namada-interface/issues/1404
https://github.com/user-attachments/assets/fdaa176d-cdf6-4089-bff2-97319b0267f6
https://github.com/user-attachments/assets/7387a48b-6c45-49c2-af2a-0a6fe6c5353d
=> feat: update overview and staking chart rollover state

apps/namadillo/src/App/Sidebars/MaspAssetRewards.tsx
=> feat: updating table for annual inflation rate

apps/namadillo/src/App/Settings/Advanced.tsx, apps/namadillo/src/App/Settings/SettingsMain.tsx
=> feat: adding pro-mode control and hiding advanced settings panel

apps/namadillo/src/hooks/useShouldInvalidateShieldedContext.ts
=> feat: set min masp version

apps/namadillo/src/App/AccountOverview/BalanceOverviewChart.tsx, apps/namadillo/src/App/Common/BalanceChart.tsx, apps/namadillo/src/App/Sidebars/YourStakingDistribution.tsx, apps/namadillo/src/atoms/settings/atoms.ts, apps/namadillo/src/hooks/useInvalidateShieldedContext.ts, apps/namadillo/src/hooks/useShouldInvalidateShieldedContext.ts
Check Namadillo version to invalidate shielded context
=> feat: check namadillo version to invalidate shielded context

.github/actions/release-project/action.yml
We now have a stable branch that must be up to date with the latest releases of namada-interface. It will help to automate a few things on CI
=> ci: making stable branch up to date on every release

apps/namadillo/src/App/Masp/MaspShield.tsx, apps/namadillo/src/App/Masp/MaspUnshield.tsx, apps/namadillo/src/App/NamadaTransfer/NamadaTransfer.tsx, apps/namadillo/src/hooks/useTransaction.tsx, apps/namadillo/src/hooks/useTransfer.ts
This PR fixes the conclusion on shielding, unshielding and other transactions.
This PR doesn't fix the notification hanging, cause it's being fixed on #1884
=> fix: fixing unshield, shield and other transactions

apps/namadillo/src/App/Common/TransactionReceipt.tsx, apps/namadillo/src/App/Transfer/common.ts, apps/namadillo/src/types.ts
=> fix: fixing transaction receipt details not appearing for shielding transfers

apps/namadillo/package.json, apps/namadillo/src/atoms/proposals/functions.ts, yarn.lock
This PR fixes the governance page breaking with new indexer versions
=> feat: handling new proposal types

.github/actions/release-project/action.yml
=> ci: adding missing bash property

apps/namadillo/src/App/Governance/AllProposalsTable.tsx, apps/namadillo/src/App/Governance/ProposalLabels.tsx, apps/namadillo/src/App/Governance/ProposalsSummary.tsx, apps/namadillo/src/atoms/proposals/functions.ts, apps/namadillo/src/utils/index.ts, packages/types/docs/modules.md, packages/types/src/proposals.ts
Closes https://github.com/anoma/namada-interface/issues/1719
=> Feat: update proposal statuses to include executed

apps/namadillo/package.json
=> fix: executedRejected proposals status

apps/namadillo/src/App/AccountOverview/NamBalanceContainer.tsx, apps/namadillo/src/App/Masp/ShieldedRewardsBox.tsx
=> feat: Only display unbond in the top overview when a user is unbonding #1743

apps/namadillo/src/App/Settings/SettingsMain.tsx
=> feat: update to links for all software versions in extension

build-webapp.sh
=> refactor: improve performance when building namadillo on Laconic

apps/namadillo/src/App/Common/BalanceChart.tsx
=> fix: update native balance to be 0 in staking panel

apps/extension/src/Setup/Common/Password.tsx
=> fix: update password checker when second input is used first

.github/actions/release-project/action.yml
Fetching branches before switching to stable
=> ci: fetching ci before checking to stable

apps/namadillo/src/App/Staking/StakingRewardsPanel.tsx
=> Feat: add Est. Rewards to staking dash

.github/workflows/docker.yml
=> ci: run docker ci on stable branch

apps/namadillo/src/hooks/useTransactionCallbacks.tsx
=> fix: refetch balances after all types of transfers

apps/namadillo/src/App/Layout/SyncIndicator.tsx
=> fix: Namadillo Status Indicator conflates RPC and Indexer status

apps/namadillo/src/App/Layout/AppLayout.tsx
=> fix: add burger menu close

apps/namadillo/src/App/Staking/IncrementBonding.tsx, apps/namadillo/src/App/Staking/IncrementBondingTable.tsx, apps/namadillo/src/App/Transfer/common.ts
=> feat: Allow validators to have an individual URL or share link

apps/namadillo/src/App/Layout/SyncIndicator.tsx, apps/namadillo/src/atoms/syncStatus/atoms.ts
=> Fix: update status syncing atom so its not perpetually syncing

apps/namadillo/src/atoms/fees/atoms.ts
=> fix: Add ceiling on gas estimates

apps/namadillo/src/App/Layout/AppHeader.tsx, apps/namadillo/src/App/Layout/AppLayout.tsx, apps/namadillo/src/App/Layout/Navigation.tsx, apps/namadillo/src/App/Staking/MyValidatorsTable.tsx, apps/namadillo/src/App/Transactions/TransactionHistory.tsx
Left nav is sticked, not scrolling with the content.
The header as well otherwise it'll be weird leaving a blank space on top of the left nav. We have the [Keplr](https://wallet.keplr.app/) as a reference
Closes #1395  
https://github.com/user-attachments/assets/e441288d-daf1-4c8e-8d03-4dfb0aba6f4c
=> feat: add sticky left nav

storybook/yarn.lock
Closes https://github.com/anoma/namada-interface/security/dependabot/216
=> chore: update storybook dependencies

apps/namadillo/src/App/AccountOverview/AccountOverview.tsx, apps/namadillo/src/App/AccountOverview/AssetsOverviewPanel.tsx, apps/namadillo/src/App/AccountOverview/EstimateShieldingRewardsCard.tsx, apps/namadillo/src/App/AccountOverview/ShieldedAssetsOverview.tsx, apps/namadillo/src/App/AccountOverview/TotalBalanceBanner.tsx, apps/namadillo/src/App/AccountOverview/TotalBalanceCard.tsx, apps/namadillo/src/App/Common/TableWithPaginator.tsx, apps/namadillo/src/App/Governance/ProposalAndVote.tsx, apps/namadillo/src/App/Layout/Navigation.tsx, apps/namadillo/src/App/Masp/ShieldedFungibleTable.tsx, apps/namadillo/src/App/Sidebars/JoinDiscord.tsx
=> feat: namadillo v2 feedback

apps/namadillo/src/App/AccountOverview/StakeSidebar.tsx, apps/namadillo/src/App/AccountOverview/UnshieldedAssetTable.tsx, apps/namadillo/src/App/Common/TableWithPaginator.tsx, apps/namadillo/src/App/Masp/ShieldedFungibleTable.tsx
=> fix: update apr and table height

apps/namadillo/src/App/AccountOverview/AccountOverview.tsx, apps/namadillo/src/App/AccountOverview/AssetsOverviewPanel.tsx, apps/namadillo/src/App/AccountOverview/ShieldedAssetsOverview.tsx, apps/namadillo/src/App/AccountOverview/TotalBalanceBanner.tsx, apps/namadillo/src/App/AccountOverview/UnshieldedAssetTable.tsx, apps/namadillo/src/App/AccountOverview/UnshieldedAssetsOverview.tsx, apps/namadillo/src/App/Common/TableWithPaginator.tsx, apps/namadillo/src/App/Masp/ShieldedAssetTable.tsx, apps/namadillo/src/App/Masp/ShieldedFungibleTable.tsx, apps/namadillo/src/App/Transactions/TransactionHistory.tsx, packages/components/src/TabContainer.tsx
=> fix: update all css for v2 transfer flow

apps/namadillo/src/App/Layout/AppLayout.tsx, apps/namadillo/src/atoms/balance/atoms.ts, apps/namadillo/src/atoms/balance/services.ts, apps/namadillo/src/workers/MaspTxMessages.ts, apps/namadillo/src/workers/MaspTxWorker.ts
- fixed infinite loop
- moved shielded rewards calls to worker
=> fix: infinite balance query loop

apps/namadillo/src/hooks/useTransaction.tsx
=> fix: Add await back to gas claiming and update indexer client

.github/workflows/docker.yml
=> ci: fix namadillo docker triggers

apps/namadillo/package.json, apps/namadillo/src/App/Ibc/IbcWithdraw.tsx, apps/namadillo/src/hooks/useWalletManager.tsx
Test this on mainnet
How to test:
- go to ibc deposit
- change chain to stride
- go to withdraw
- try to withdraw osmo/atoms and see if it works
=> fix: use correct destination chain and address for ibc withdraw

build-webapp.sh
=> feat: add lib for building file on Laconic

apps/namadillo/src/App/Settings/SettingsMain.tsx
=> fix: update sdk lnk to npmjs

apps/namadillo/src/App/AccountOverview/EstimateShieldingRewardsCard.tsx, apps/namadillo/src/App/AccountOverview/ShieldedAssetsOverview.tsx, apps/namadillo/src/App/Governance/AllProposalsTable.tsx, apps/namadillo/src/App/Governance/GovernanceOverview.tsx, apps/namadillo/src/App/Governance/ProposalListPanel.tsx, apps/namadillo/src/App/Masp/MaspShield.tsx, apps/namadillo/src/App/Masp/MaspUnshield.tsx, apps/namadillo/src/App/NamadaTransfer/NamadaTransfer.tsx, apps/namadillo/src/App/Staking/MyValidatorsTable.tsx, apps/namadillo/src/App/Staking/StakingOverview.tsx, packages/components/src/TabContainer.tsx
=> fix: namadillo v2 fixes

apps/namadillo/src/App/AccountOverview/StakeSidebar.tsx
=> fix: show Staking sidebar button even if there is 0 to claim

apps/namadillo/src/App/AppRoutes.tsx, apps/namadillo/src/App/Common/TransactionReceipt.tsx, apps/namadillo/src/App/Transactions/TransactionDetails.tsx, apps/namadillo/src/App/Transactions/TransactionNotFoundPanel.tsx, apps/namadillo/src/hooks/useTransactionActions.ts
=> fix: Restore transaction details page

apps/namadillo/src/App/Common/Toast.tsx, apps/namadillo/src/App/Staking/ClaimRewardsSubmitModalStage.tsx, apps/namadillo/src/App/Staking/IncrementBonding.tsx, apps/namadillo/src/App/Staking/ReDelegate.tsx, apps/namadillo/src/App/Staking/StakingRewards.tsx, apps/namadillo/src/App/Staking/StakingWithdrawModal.tsx, apps/namadillo/src/App/Staking/Unstake.tsx, apps/namadillo/src/hooks/useTransaction.tsx, apps/namadillo/src/hooks/useTransactionNotifications.tsx, apps/namadillo/src/lib/query.ts, apps/namadillo/src/types/events.ts, apps/namadillo/src/utils/index.ts, packages/shared/lib/src/sdk/mod.rs, packages/shared/lib/src/sdk/tx.rs, packages/types/src/errors.ts, packages/types/src/tx/schema/batchTxResult.ts
Cherry picked from maintnance
Original PR https://github.com/anoma/namada-interface/pull/2020
EDIT:
Added a commit on top of cherry picked one, so we handle partially successful claim rewards correctly
=> feat: improve error message on wasm errors

apps/namadillo/src/App/Transactions/PendingTransactionCard.tsx, apps/namadillo/src/App/Transactions/TransactionCard.tsx, apps/namadillo/src/App/Transactions/TransactionHistory.tsx
=> feat: add Stake transactions to History view

apps/namadillo/package.json, apps/namadillo/src/App/Common/Toast.tsx, apps/namadillo/src/utils/index.ts, packages/shared/lib/src/sdk/io.rs, packages/shared/lib/src/sdk/masp/masp_web.rs, packages/shared/lib/src/sdk/mod.rs, packages/shared/lib/src/sdk/tx.rs, packages/shared/lib/src/utils.rs
Port of https://github.com/anoma/namada-interface/pull/2034
PR so we have proper changelog
=> feat: change query tx status loop

apps/namadillo/src/App/Common/MaspContainer.tsx
=> fix: add relative to div on `/masp/shield`

apps/namadillo/src/App/AccountOverview/TotalBalanceBanner.tsx
=> fix: delete overflow hidden

apps/namadillo/src/App/Staking/UnclaimedRewardsCard.tsx
=> fix: update route for claiming on Claim NAM button

apps/namadillo/src/App/Layout/SyncIndicator.tsx
=> feat: fix sync indicator

apps/namadillo/src/App/Transactions/TransactionCard.tsx
=> chore: update history table icons

apps/namadillo/src/atoms/integrations/services.ts
=> fix: increase additional percentage for simulated ibc transfer gas fee

apps/namadillo/src/App/Common/PulsingRing.tsx, apps/namadillo/src/App/Layout/Sidebar.tsx, apps/namadillo/src/App/Layout/SyncIndicator.tsx, apps/namadillo/src/App/Masp/ShieldedSyncProgress.tsx, apps/namadillo/src/App/Transactions/TransactionCard.tsx
- Brings back syncing bar, gets rid of pulsing sync
- Updates syncing bar so that quick syncs are not shown
- Adds data to the Application sync (Heartbeat, Account Overview, Staking, Governance)
- Adds a container for errors to so that long errors dont overflow the container
=> feat: update syncing view

apps/namadillo/src/App/Transactions/LocalStorageTransactionCard.tsx, apps/namadillo/src/App/Transactions/TransactionHistory.tsx
=> fix: add warning on Transaction History table for MASP txns

packages/shared/lib/Cargo.lock, packages/shared/lib/Cargo.toml, packages/shared/lib/src/sdk/args.rs, packages/shared/lib/src/sdk/mod.rs, packages/shared/lib/src/sdk/tx.rs
This PR simply updates `namada_sdk` and `namada_tx` to `v0.150.1`, and accounts for these changes in `@namada/shared`
=> feat: Account for changes in SDK libs v0.150.1

apps/namadillo/src/atoms/chain/services.ts
=> fix: passing timestamp in millis instead of seconds to get block height

apps/namadillo/src/App/Sidebars/MaspAssetRewards.tsx, apps/namadillo/src/App/Sidebars/MaspRewardCalculator.tsx
We can't use base because we can have like 2 TIA assets
=> fix: react components keys using asset base

apps/namadillo/package.json, apps/namadillo/public/config.toml, apps/namadillo/src/App/App.tsx, apps/namadillo/src/App/Ibc/IbcTransfer.tsx, apps/namadillo/src/App/Ibc/IbcWithdraw.tsx, apps/namadillo/src/App/NamadaTransfer/NamadaTransfer.tsx, apps/namadillo/src/hooks/useCurrentRoute.tsx, apps/namadillo/src/hooks/useFathomTracker.tsx, apps/namadillo/src/types.ts, yarn.lock
We're adding the possibility of adding a [Fathom](https://app.usefathom.com/) tracker on Namadillo, so might an anonymous overview of the app usage.
=> feat: Fathom integration

apps/namadillo/src/App/Transactions/TransactionHistory.tsx
=> fix: update history browser alert

apps/namadillo/src/App/AccountOverview/UnshieldedAssetsOverview.tsx, apps/namadillo/src/App/Staking/StakingRewards.tsx, apps/namadillo/src/App/Staking/UnclaimedRewardsCard.tsx
This PR implements the new unclaimed rewards box, following the guidelines of the following Figma screenshot:
Closes #2106
=> feat: creating new unclaimed rewards box

apps/namadillo/src/App/Transfer/WalletCard.tsx, apps/namadillo/src/App/Transfer/__tests__/WalletCard.test.tsx
=> fix: Connect wallet larger click surface 

apps/namadillo/src/App/AccountOverview/TotalBalanceBanner.tsx, apps/namadillo/src/App/Transfer/TransferSource.tsx
=> fix: update total balance banner sync dot and transfer source masp sync info

apps/namadillo/src/App/Layout/AppLayout.tsx
=> fix: extend tables on Manage Tab

apps/namadillo/src/App/Masp/ShieldedFungibleTable.tsx
=> fix: update unshield button with proper route

apps/namadillo/src/App/AccountOverview/UnshieldedAssetTable.tsx, apps/namadillo/src/App/AccountOverview/common.ts, apps/namadillo/src/App/Masp/ShieldedFungibleTable.tsx
=> fix: update ranking on shielded fungible table and transparent table

apps/namadillo/src/App/AccountOverview/common.ts, apps/namadillo/src/App/Transfer/TransferDestination.tsx, apps/namadillo/src/atoms/integrations/atoms.ts
Small fixes after assets refactor merge
=> fix: housefire tokens and type import

apps/namadillo/src/atoms/integrations/functions.ts, apps/namadillo/src/atoms/prices/atoms.ts, apps/namadillo/src/atoms/prices/functions.ts
=> chore: convert nam to ibc assets for searching price on osmosis

apps/namadillo/src/App/AccountOverview/TotalStakeBanner.tsx, apps/namadillo/src/App/Transfer/TransferModule.tsx
Also fixes a problem in transfer tab with shielded transfers etc.
=> fix: bonded amount dollar value

apps/namadillo/src/App/Ibc/IbcTransfer.tsx, apps/namadillo/src/atoms/integrations/functions.ts
=> fix: use supported assets map

apps/namadillo/src/App/Ibc/IbcTransfer.tsx, apps/namadillo/src/atoms/integrations/functions.ts
=> fix: add usdc back to select chain modal

apps/namadillo/src/App/AccountOverview/UnshieldedAssetTable.tsx
=> fix: update proper staked balance

packages/shared/lib/Cargo.lock, packages/shared/lib/Cargo.toml, packages/shared/lib/src/query.rs, packages/shared/lib/src/sdk/masp/masp_node.rs, packages/shared/lib/src/sdk/masp/masp_web.rs, packages/shared/lib/src/sdk/mod.rs
Requires https://github.com/namada-net/namada/pull/4751
=> chore: update namada libs to v0.251.0

apps/namadillo/src/App/Masp/ShieldedFungibleTable.tsx
=> fix: threshold fix

.release-please-manifest.json, packages/shared/lib/Cargo.lock, packages/shared/lib/Cargo.toml
To include [this](https://github.com/namada-net/namada/pull/4763)
=> chore: update namada sdk libs-v0.251.1

apps/namadillo/package.json, apps/namadillo/src/App/Common/TransactionReceipt.tsx, apps/namadillo/src/App/Layout/KeplrAccount.tsx, yarn.lock
=> fix: Update keplr connect check and update to use latest SDK 

docker/namadillo/nginx.conf
Mirror's Harri's changes here except for Docker instead of a static host (Netlify): https://github.com/heliaxdev/namada.net/pull/167/files
=> fix: fix for clickjacking that mirrors namada.net
