packages/shared/lib/src/lib.rs

Adds back a dependency that had gone missing. It prevented building the extension as `Bond` is being used.

fix/175 Adding `bond` dependency that is being used

---

apps/extension/src/App/Accounts/AddAccount.tsx
apps/extension/src/App/App.tsx
apps/extension/src/App/Approvals/ApproveConnection.components.tsx
apps/extension/src/App/Approvals/ApproveConnection.tsx
apps/extension/src/App/Approvals/ApproveTx.components.tsx
apps/extension/src/App/Approvals/ApproveTx.tsx
apps/extension/src/App/Approvals/index.ts
apps/extension/src/App/LockWrapper/LockWrapper.tsx
apps/extension/src/App/Login/Login.tsx
apps/extension/src/App/types.ts
apps/extension/src/background/index.ts
apps/extension/src/hooks/index.ts
apps/extension/src/hooks/useAuth.tsx
apps/extension/src/hooks/useQuery.tsx
packages/chains/src/chains/namada.ts

See #141
This updates the extension web app with behavior similar to Polkadot extension, where public addresses are displayed by default, and features needing access to private keys in storage will first prompt for a password (if the keyring storage is locked - the issue here is that we currently require Chrome extension users to constantly authenticate due to Manifest 3 service workers)
__NOTE__ I've added some preliminary code for handle Tx approvals, but to keep this PR smaller, I'm moving the rest of it to another PR.
*TODO* (separate PR for #200):
__NOTE__ For approvals/unlocking from interface, we will need to trigger the opening of the extension web app from within `content-scripts` upon receiving the signing request from the interface, loading the app from the correct route. The …

feat/141 - Prompt for password only when needed

---

apps/namada-interface/src/App/AccountOverview/DerivedAccounts/DerivedAccounts.components.ts
apps/namada-interface/src/App/AccountOverview/DerivedAccounts/DerivedAccounts.tsx
apps/namada-interface/webpack.config.js
packages/chains/src/chains/cosmos.ts
packages/chains/src/chains/osmosis.ts
packages/integrations/package.json
packages/integrations/src/Anoma.ts
packages/integrations/src/Keplr.ts
packages/integrations/src/Metamask.ts
packages/integrations/src/types/Integration.ts
packages/types/src/tx/types.ts

This PR addresses parts of #205 
In this PR, we now show all accounts from the extension, even if it has a zero balance, and instead of listing by token balance, it lists all accounts, and the user can choose to view the breakdown of token balances underneath their account. An issue with loading accounts from Keplr has been resolved.
*NOTE* I've also patched up a couple small things in the `webpack.config` for `namada-interface`
TODO: Follow-up PR:
This PR introduces a `submitBridgeTransfer` function to `Integration` based classes, which can accept either `IbcTransferProps` or `BridgeTransferProps` (in the case of Metamask, which will use the Ethereum bridge). This will be implemented in a future PR.

Keplr Integration - Display All Accounts

---

apps/extension/src/config/argon2.ts

Based on `Issue A: Memory Parameter of Argon2 Is Too Low`
The Namada Interface uses an Argon2 memory parameter of 4 MiB, which is far below the
recommendations prescribed in [[BDK+21]](https://www.rfc-editor.org/rfc/rfc9106.html#name-recommendations).
> The Argon2id variant with t=1 and 2 GiB memory is the FIRST RECOMMENDED option and is suggested as a default setting for all environments. This setting is secure against side-channel attacks and maximizes adversarial costs on dedicated brute-force hardware. The Argon2id variant with t=3 and 64 MiB memory is the SECOND RECOMMENDED option and is suggested as a default setting for memory-constrained environments.

feat: increase memory param of argon2

---

apps/extension/package.json
apps/extension/src/Setup/AccountCreation/Steps/Password/Password.components.ts
apps/extension/src/Setup/AccountCreation/Steps/Password/Password.tsx
yarn.lock

Based on the Audit report:
Issue D: Usage of Strong Passwords Not Enforced
Added `zxcvbn` validation which allows passwords with strength of 3 or more, which usually means password at least 11 characters long. It also checks for other properties like most common passwords and usage of recursive words.
Validation is disabled for `NODE_ENV=development`, although feedback messages are still present.

feat: add zxcvbn validation

---

apps/namada-interface/src/App/Token/TokenSend/TokenSend.tsx

Part of the UI does not display for send token view after refreshing. 
This fixed it for scenario when we are connected to extension and we can query node for balances.

fix: send token view does not display ui after refresh

---

.github/workflows/deploy-wallet-at-pr.yml
apps/extension/package.json
apps/namada-interface/package.json
package.json
packages/components/package.json
packages/integrations/package.json
packages/rpc/package.json
packages/storage/package.json
packages/types/package.json
packages/utils/package.json

Resolves #245 
We run linter with `max-warnings 0`.
Unit tests depend on a lint action to succeed.
Build does not depend on lint as we might want to showcase some builds without linter or unit tests passing.

feat: add linter to the ci

---

apps/extension/src/background/content/handler.ts
apps/extension/src/background/content/init.ts
apps/extension/src/background/content/messages.ts
apps/extension/src/background/content/service.ts
apps/extension/src/background/index.ts
apps/extension/src/background/keyring/keyring.ts
apps/extension/src/background/keyring/messages.ts
apps/extension/src/background/keyring/service.ts
apps/extension/src/background/web-workers/index.ts
apps/extension/src/background/web-workers/types.ts
apps/extension/src/content/events.ts
apps/extension/src/router/types/enums.ts
apps/extension/src/test/init.ts
apps/namada-interface/src/App/App.tsx
apps/namada-interface/src/hooks/index.ts
apps/namada-interface/src/hooks/useEvent.ts
apps/namada-interface/src/index.tsx
apps/namada-interface/src/services/extension-events.tsx
apps/namada-interface/src/services/index.ts
apps/namada-interface/src/slices/transfers.ts

Resolves [#251](https://github.com/anoma/namada-interface/issues/251)
- Added TransferStartedEvent - sent by the background script, that informs content script that stuff is happening :)- 
Added custom "anoma_transfer_completed" event, which is being send from content script to the interface via `window.dispatchEvent`
- Added service which listens to the window events and handles them accordingly. In this case by displaying correct toasts.

feat: keep track of the transfer using msgId

---

apps/extension/src/background/content/handler.ts
apps/extension/src/background/content/messages.ts
apps/extension/src/background/content/service.ts
apps/extension/src/background/keyring/handler.ts
apps/extension/src/background/keyring/keyring.ts
apps/extension/src/background/keyring/service.ts
apps/extension/src/background/web-workers/index.ts
apps/extension/src/background/web-workers/types.ts
apps/extension/src/extension/utils.ts
apps/extension/src/router/types/router.ts
apps/extension/src/test/init.ts

Added `senderTabId` to identify to which tab we want to send message back. 
For now we only need it for a transfer msg. Maybe later on it will make more sense to store (msgId, tabId) pair in the DB so we do not have to pass it around everywhere. Also adding msgId to every kind of message might be some kind of abstraction :) Probably too soon to make that decision though.

feat: send event to the correct browser tab

---

apps/extension/package.json
apps/extension/src/background/index.ts
apps/extension/src/background/keyring/crypto.ts
apps/extension/src/background/keyring/keyring.ts
apps/extension/src/background/keyring/service.ts
apps/extension/src/test/init.ts
packages/crypto/lib/Cargo.lock
packages/crypto/lib/Cargo.toml
packages/crypto/lib/src/crypto/aes.rs
packages/crypto/lib/src/crypto/argon2.rs
packages/crypto/lib/src/crypto/bip32.rs
packages/crypto/lib/src/crypto/bip39.rs
packages/crypto/lib/src/crypto/mod.rs
packages/crypto/lib/src/crypto/pointer_types.rs
packages/crypto/lib/src/crypto/zip32.rs
packages/crypto/src/__tests__/crypto.test.ts
packages/crypto/src/utils.ts
specs/browser-extension/security.md

This PR adds more careful handling of sensitive data to try to guard against sensitive data being left in memory.
The strategy is:
1. Wrap sensitive values in structs.
a. Wrapped values will be automatically zeroized in memory when dropped.
b. Wrapped values can be passed to JS without loading the sensitive value into JS memory.
c. If required, the value can be read from JS by reading directly from WASM memory, which gets around wasm-bindgen making a temporary value in memory that we can't zeroize.
2. Local variables in Rust are zeroized after use if they hold sensitive data.
3. Use `#[wasm_bindgen(skip_typescript)]` to hide methods from JS that don't wrap sensitive data. (Ideally I would use `#[wasm_bindgen(skip)]` but it [doesn't currently …

feat: zeroize secrets in WASM memory

---

.github/workflows/deploy-wallet-at-pr.yml

When v0.2.85 was released, it broke the CI build because wasm-bindgen-cli versions are required to match, so this commit fixes the globally installed version to v0.2.84 as a temporary measure until we upgrade our packages to use v0.2.85.

chore: fix wasm-bindgen-cli version to v0.2.84 in CI

---

apps/extension/src/App/App.tsx
apps/extension/src/App/Loading/Loading.tsx
packages/hooks/src/useIntegration.ts
packages/hooks/src/useUntil.ts

Resolve #263 
This PR makes use of `useUntil`, where the predicate will return `true` when the requester is able to resolve a "fetch accounts" `sendMessage` promise to the extension, and once successful, will load those accounts into state.
__NOTE__ This method will cause many errors to be logged, and I have some ideas on how to address that in #271. The idea is to introduce better and more useful error handling within the messaging of the extension. Currently, we throw an exception in any case that the requester is unable to resolve a promise, and it would perhaps be much more useful to reject the promise and return data to whichever method requested it for better handling on the client end.

bug/263 - Fix for extension popup error

---

apps/extension/src/background/keyring/index.ts
apps/extension/src/background/keyring/service.ts
apps/extension/src/background/keyring/utils.ts
apps/extension/src/extension/ExtensionRequester.ts

Resolves #269 
This PR adds a utility to synchronize the tabs tracked within the `KeyRingService`. It compares what is stored against what is available via `browser.tabs.query`, and updates the storage, returning the updated _current_ tabs before attempting to broadcast to them. This prevents errors that occur in the requester when an attempt is made to communicate with a non-existent tab.

Extension: Update tab storage to account for closed tabs

---

apps/namada-interface/src/App/Staking/Staking.tsx
apps/namada-interface/src/App/StakingAndGovernance/StakingAndGovernance.tsx
apps/namada-interface/src/App/TopNavigation/topNavigation.tsx

This is a temporary fix for the introduction of `useSanitizedLocation` where its use is breaking on `namada-interface`, which was added as a part of #222. This PR reverts its usage in three areas as it is breaking the interface.
__TODO__ We need to figure out why that hook breaks in certain contexts. _Note:_ It does not have any issues on the extension as far as I can tell, but within `TopNavigation/topNavigation`, `Staking`, and `StakingAndGovernance`, it complains that `useLocation` must be used in the context of a `Router`, which it appears to be, but still breaks for some reason.

Interface: Bug - Fix for useLocation hook error

---

apps/extension/src/App/Accounts/AccountListing.tsx
apps/extension/src/Setup/AccountCreation/Steps/SeedPhrase/SeedPhrase.tsx
apps/extension/src/background/keyring/service.ts

Resolves #280 
__NOTE__ This still needs to be added to Ledger accounts once that service is implemented! This is simple enough to be handled in the PR that implements the Ledger service.

feat/280 - Implement events for new address & new mnemonics

---

apps/extension/package.json
apps/namada-interface/src/App/Staking/Staking.tsx
apps/namada-interface/src/App/StakingAndGovernance/StakingAndGovernance.tsx
apps/namada-interface/src/App/TopNavigation/topNavigation.tsx
yarn.lock

The hook broke when it was moved from namada-interface to packages/hooks. There were two versions of react-router-dom present, and the interface and the package were being built with different versions, which caused the Location context objects to not be equal, ultimately causing useLocation to fail.
This commit aligns the version of react-router-dom in the extension with the version in the interface, which ensures only one copy is installed by `yarn install`.

fix: fix useSanitizedLocation hook

---

apps/extension/src/App/App.tsx
apps/extension/src/App/Loading/Loading.components.ts
apps/extension/src/App/Loading/Loading.tsx
apps/extension/src/background/index.ts
apps/extension/src/background/keyring/handler.ts
apps/extension/src/background/keyring/init.ts
apps/extension/src/background/keyring/service.ts
apps/extension/src/background/web-workers/submit-transfer-web-worker.ts
apps/extension/src/provider/Anoma.ts
apps/extension/src/provider/messages.ts
packages/shared/lib/src/sdk/mod.js
packages/shared/lib/src/sdk/mod.rs

Resolves #293
Moved initialization of the masp params download into the extension app.
It should fix service worker initialization errors.
In the next PRs:
Preview:

feat: initialize masp params load from the extension

---

apps/extension/src/App/Accounts/AccountListing.tsx
apps/extension/src/Setup/AccountCreation/Steps/Completion/Completion.tsx
apps/extension/src/Setup/AccountCreation/Steps/SeedPhrase/SeedPhrase.tsx
packages/hooks/src/useUntil.ts
packages/utils/src/async/executeUntil.ts
packages/utils/src/async/index.ts

Partially resolves #282 
This PR adds the functionality from `useUntil` in several key places throughout the Account Creation setup process, where the app will break due to the service worker being inactive when the user request an action requiring the background scripts.

bug/282 - Fix all service worker-related errors in Create Account

---

apps/extension/package.json
apps/extension/scripts/build.sh
apps/extension/src/background/keyring/keyring.ts
apps/extension/src/provider/Anoma.test.ts
apps/extension/tsconfig.json
apps/namada-interface/package.json
packages/crypto/lib/Cargo.toml
packages/crypto/lib/src/utils.rs
packages/crypto/package.json
packages/crypto/scripts/build.sh
packages/crypto/tsconfig.json
packages/shared/lib/Cargo.toml
packages/shared/lib/src/query.rs
packages/shared/lib/src/sdk/mod.rs
packages/shared/lib/src/utils.rs
packages/shared/package.json
packages/shared/scripts/build.sh
packages/shared/src/index.ts
packages/shared/tsconfig.json
scripts/build-test.sh
scripts/build.sh

Context:
> So I found a pretty shitty workaround. So it seems like the only way to gc the memory is to free all the references to the WebAssembly instance exports/properties. We can't do it manually by accessing memory or sth.
> The problem tho is that because rust panics the js stops executing(just hangs there). Because of that extension service worker(which we use to run rust sdk code) can't get inactive(and drop the references to WebAssembly exports) :confused:
> So the shitty fix is to timeout calls to rust sdk, after certain amount of time. This way we can catch reject on timeout and handle it as a normal error. So we still have garbage in memory, but it will be freed after service worker goes inactive which is 30 seconds of no received messages. Unfortunately we can't stop the …

feat: cleanup memory on rust panic

---

apps/namada-interface/tsconfig.json

This fixes a bug introduced in #317 where `new Query` cannot be called because Query was transpiled to ES5 and relies on the class it extends to also be transpiled, but the parent class was generated from Rust and not transpiled.
PR #317 already fixed this for the extension; this commit just sets the target JS version for namada-interface too.

fix: use es2015 in interface

---

packages/shared/lib/Cargo.lock
packages/shared/lib/Cargo.toml
packages/shared/lib/src/sdk/mod.js

Should be "just" working. 
I've removed few unused dependencies and patches.
Had to export `get` and `set` functions for some reason. Not sure why, but it does not seem to break anything,

chore: update namada to 0.17.5

---

apps/namada-interface/src/services/extensionEvents/handlers/keplr.ts
apps/namada-interface/src/services/extensionEvents/handlers/metamask.ts
apps/namada-interface/src/services/extensionEvents/provider.tsx
packages/chains/src/index.ts
packages/hooks/src/useEvent.ts
packages/types/src/events.ts

Resolves #264 
- Add a second (or more) account(s) in Keplr
- In Namada interface, select "Cosmos Hub", and make sure extension is connected
- In Keplr, select a different account, and the interface should reflect this
- Make sure you have more than one account in Metamask
- In Namada Interface, select "Goerli Testnet"
- In Metamask, in the "accounts" menu (icon at top-right) select a different account (_NOTE_ If this is a _new_ account, you will need to first click "connect" on the account name) and the interface should update the address
- There is a display bug that has been introduced somewhere in the interface, where the listing of the Ethereum asset is broken (only the address displays) - This will be updated in a separate PR if I don't figure it out quickly

feat/264 - Handle third-party extension events

---

.github/workflows/deploy-wallet-at-pr.yml
apps/extension/src/background/approvals/service.ts
apps/extension/src/background/keyring/handler.ts
apps/extension/src/background/keyring/messages.ts
apps/extension/src/background/keyring/service.ts
apps/extension/src/background/offscreen/offscreen.ts
apps/extension/src/background/web-workers/index.ts
apps/extension/src/background/web-workers/submit-transfer-web-worker.ts
apps/extension/src/background/web-workers/types.ts
apps/namada-interface/src/slices/StakingAndGovernance/actions.ts
apps/namada-interface/src/slices/transfers.ts
packages/crypto/lib/Cargo.lock
packages/shared/lib/Cargo.lock
packages/shared/lib/Cargo.toml
packages/shared/lib/src/query.rs
packages/shared/lib/src/rpc_client.rs
packages/shared/lib/src/sdk/tx.rs

Update namada to 0.18
- propagate transfer error message correctly
- fix amounts
- fix RpcError

feat: update namada to 0.18.0

---

packages/crypto/lib/Cargo.toml
packages/crypto/scripts/build-test.sh
packages/crypto/scripts/build.sh
packages/shared/lib/Cargo.toml
packages/shared/scripts/build-test.sh
packages/shared/scripts/build.sh

`wasm-pack` has built in support for `wasm-opt`, so it makes sense to use it for builds
I've also changed:
- opt levels a bit, not sure if it helps with anything though :D 
- test build profile to `dev` as it does skip optimizations

refactor: use wasm-pack for builds

---

apps/namada-interface/src/services/extensionEvents/provider.tsx

Resolves #328 
This is a simple fix that resolves an issue where Event registration crashes the interface if the Metamask extension is not installed. This checks that `window.ehtereum` is present before attaching handlers.

bug - Fix for crash on event registration

---

packages/shared/lib/Cargo.lock
packages/shared/lib/Cargo.toml
packages/shared/lib/src/sdk/mod.rs
packages/shared/lib/src/sdk/tx.rs
packages/types/src/tx/schema/tx.ts
packages/types/src/tx/types.ts

This PR updates us to support `namada` `v0.18.1`, which contains the refactoring of the SDK calls.
__NOTE__ We can now pass an optional `publicKey` along with our transactions, so this has been added to the `tx` schema and `TxProps` type, but isn't yet being passed in. It is required to be there so tx can be deserialized in Rust.

chore - Update to SDK changes in namada v0.18.1

---

apps/extension/src/background/index.ts
apps/extension/src/background/keyring/crypto.ts
apps/extension/src/background/keyring/keyring.ts
apps/extension/src/background/keyring/service.ts
apps/extension/src/background/keyring/types.ts
apps/extension/src/background/web-workers/submit-transfer-web-worker.ts
apps/extension/src/provider/Anoma.test.ts
apps/extension/src/router/types/enums.ts
apps/extension/src/test/init.ts
packages/crypto/lib/Cargo.toml
packages/shared/lib/Cargo.toml
packages/storage/src/store/IndexedDBKVStore.ts
packages/storage/src/store/types.ts

feat: do not decrypt mnemonic for auth

---

apps/namada-interface/src/slices/transfers.ts

This fixes a problem where TypeScript was not throwing an error when getToast was called with the wrong arguments. The code calling getToast has been commented out for now.
~This PR is based on #325 since they both touch the same file, so this should be rebased to main after #325 is merged.~ Done.

fix: calculate toast props from toast type

---

.github/workflows/deploy-wallet-at-pr.yml
package.json

This PR adds some things to speed up the CI, most importantly caching of Rust and yarn dependencies.
---
- Run more CI jobs in parallel (1d3ea4a8)
- Run linting script in parallel (d70a1c31)
- Add yarn cache to CI (bb2b5f87)
- Add Rust caches to CI (44e1294f)
- Don't install wasm-bindgen-cli in CI (ceb79e76)

Speed up CI

---

apps/extension/src/extension/ExtensionMessenger.ts
apps/extension/src/extension/ExtensionRequester.ts
apps/extension/src/extension/ExtensionRouter.ts
apps/extension/src/manifest/v2/_devOnly.json
apps/extension/tsconfig.json
apps/extension/webpack.config.js

This PR fixes a bug where background errors were getting logged as `[Object, object]` in Chrome, and adds source maps for the extension on Firefox in development mode. These changes should make error reporting in the extension better.
I wanted to add source maps for Chrome, but the type of source map I chose uses `eval`, which is not supported in manifest v3. There are non-eval source maps, but these crashed webpack when I tried them.
---
- Print background errors properly on Chrome (83792a18)
- Add extension source maps on Firefox (8890336d)

Improve extension errors

---

apps/extension/src/App/Accounts/AccountListing.tsx
apps/extension/src/App/Accounts/AddAccount.tsx
apps/extension/src/App/Settings/ExtraSettings/DeleteAccount/DeleteAccount.tsx
apps/extension/src/App/Settings/ExtraSettings/ExtraSettings.tsx
apps/extension/src/App/Settings/ExtraSettings/types.ts
apps/extension/src/App/Settings/Settings.tsx
apps/extension/src/Approvals/ApproveTx/ApproveTx.tsx
apps/extension/src/Approvals/ApproveTx/ConfirmLedgerTx.tsx
apps/extension/src/Setup/Ledger/LedgerConfirmation.tsx
apps/extension/src/background/index.ts
apps/extension/src/background/keyring/keyring.ts
apps/extension/src/background/ledger/handler.ts
apps/extension/src/background/ledger/index.ts
apps/extension/src/background/ledger/init.ts
apps/extension/src/background/ledger/messages.ts
apps/extension/src/background/ledger/service.ts
apps/extension/src/test/init.ts
packages/shared/lib/Cargo.lock
packages/shared/lib/Cargo.toml

Resolves #342 
This PR enables address derivation from a user's Ledger hardware wallet. The initial account when connecting a Ledger uses path `/0'/0/0`, so the address form should start the user at `/0'/0/1`, otherwise behavior is the same as deriving from a mnemonic account. _Note_ that paths such as `m/44'/877'/0'/0` are not supported on Ledger, i.e., the path should always contain the `index` of the path as well.

feat/342 - Ledger - support for additional addresses

---

apps/extension/src/background/keyring/service.ts
apps/extension/src/background/offscreen/offscreen.ts
apps/extension/src/background/web-workers/index.ts
apps/extension/src/background/web-workers/submit-transfer-web-worker.ts
apps/extension/src/background/web-workers/types.ts

This PR make sure errors thrown in web workers running the submit-transfer-web-worker.js script are logged properly in the extension console. The errors are passed from the web worker to the offscreen document and then to the background script where they are logged to the console. This fix should only affect Chrome.

fix: show web worker errors in extension console

---

apps/extension/src/App/Accounts/AddAccount.tsx
apps/extension/src/Approvals/Approvals.components.tsx
apps/extension/src/Approvals/ApproveTx/ConfirmLedgerTx.tsx
apps/extension/src/Setup/Ledger/Ledger.components.ts
apps/extension/src/Setup/Ledger/Ledger.tsx
apps/extension/src/Setup/Ledger/LedgerConfirmation.tsx
apps/extension/src/background/ledger/ledger.ts
packages/shared/lib/src/sdk/mod.rs

Resolves #353 
Any time an error is encountered with the Ledger device, the extensions should always allow the user to correct the issue and proceed. A locked device or unloaded app should not force the user to refresh! Also, the appropriate error should be reported to user in each case!
- Connect Ledger
- Add Account
- Reveal PK
- Submit Tx (Reveal PK, Bond, Unbond, Withdraw, Transfer)

bug/353 - Ledger error-handling improvments

---

apps/extension/src/Approvals/ApproveTx/ApproveTx.tsx
apps/extension/src/Setup/AccountCreation/Steps/SeedPhrase/SeedPhrase.tsx
apps/extension/src/Setup/AccountCreation/Steps/SeedPhraseConfirmation/SeedPhraseConfirmation.tsx
apps/extension/src/Setup/Common/Completion/Completion.tsx
apps/extension/src/background/index.ts
apps/extension/src/background/keyring/service.ts
apps/extension/src/content/index.ts
apps/extension/src/extension/ExtensionRouter.ts
apps/extension/src/router/Router.ts
apps/extension/src/test/init.ts
packages/shared/lib/src/sdk/mod.rs

Resolves #356 
This PR is to resolve the issues we're seeing with the service worker being unable to start up correctly and handle messages after being shut down.

feat/356 - Fix service worker event registration

---

apps/extension/src/Approvals/ApproveTx/ConfirmLedgerTx.tsx
apps/extension/src/background/index.ts
apps/extension/src/background/keyring/types.ts
apps/extension/src/background/ledger/handler.ts
apps/extension/src/background/ledger/init.ts
apps/extension/src/background/ledger/messages.ts
apps/extension/src/background/ledger/service.ts
apps/extension/src/router/types/enums.ts
apps/extension/src/test/init.ts
apps/namada-interface/src/App/AccountOverview/AccountOverview.components.ts
apps/namada-interface/src/App/AccountOverview/AccountOverview.tsx

feat/364 - Track revealed Ledger PKs

---

apps/extension/src/background/approvals/service.ts
apps/extension/src/background/keyring/service.ts
apps/extension/src/background/ledger/service.ts
apps/extension/src/content/events.ts

Resolves #354 
For all Ledger Tx, the interface should update balances and staking positions after each successful transaction.

feat/354 - Ledger tx updated balances & staking

---

apps/extension/src/App/Accounts/AddAccount.tsx
apps/extension/src/App/App.tsx
apps/extension/src/App/Login/Login.tsx
apps/extension/src/hooks/useAuth.tsx

Resolves #366 
When deriving an address (from a mnemonic account), if the service worker goes inactive while the user is entering data in the form, the flow would break, as the password goes out of scope, and an error would be thrown. In this case, we should redirect the user to authenticate, where they can try again to derive the address. This prevents us from needing to keep the password in application state, as we have done before, but also allows a user to continue if the password is removed due to a service worker restart.
1. In Chrome, open the Extensions tab (so you can monitor Service Worker status)
2. Launch the extension (we'll assume that you've already set up a mnemonic account)
3. Click the `+` icon to add an account
4. Authenticate the extension, then enter an account …

feat/366 - Redirect user to authorize if service worker goes inactive (Chrome)

---

apps/extension/src/Approvals/ApproveTx/ApproveTx.tsx
apps/extension/src/Approvals/ApproveTx/ConfirmLedgerTx.tsx
apps/extension/src/Approvals/ApproveTx/ConfirmTx.tsx
apps/extension/src/Approvals/types.ts
apps/extension/src/background/index.ts
apps/extension/src/background/keyring/service.ts
apps/extension/src/background/ledger/service.ts
apps/extension/src/content/events.ts
apps/extension/src/extension/ExtensionBroadcaster.ts
apps/extension/src/extension/index.ts
apps/extension/src/test/init.ts
apps/namada-interface/src/services/extensionEvents/handlers/namada.ts
apps/namada-interface/src/services/extensionEvents/provider.tsx
apps/namada-interface/src/slices/notifications/reducers.ts
apps/namada-interface/src/slices/transfers.ts
packages/shared/src/index.ts
packages/shared/src/types.ts
packages/types/src/events.ts
packages/types/src/tx/types.ts

Resolves #358 
Optional may have implications and possibly should be skipped on this PR):

feat/358 - Implement notifications for all tx types

---

.github/workflows/deploy-wallet-at-merge-to-main.yml
.github/workflows/release-wallet.yml
specs/DEVELOPMENT.md

This PR adds a CI workflow that can be manually run to deploy the interface to namada.me and create a GitHub release of the extension with given parameters (e.g. Namada chain ID).
I haven't been able to test the Netlify deploy part since the workflow can only be run when it is in main, so this might need fixed up after it is merged.
#352 can probably be closed when this is merged.
---
Add deploy and release workflow to CI. Closes #357.
Remove deploy to namada.me on merge to main

Add deploy and release workflow to CI

---

apps/extension/src/App/Settings/ExtraSettings/ConnectedSites/ConnectedSites.components.ts
apps/extension/src/App/Settings/ExtraSettings/ConnectedSites/ConnectedSites.tsx
apps/extension/src/App/Settings/ExtraSettings/ConnectedSites/index.ts
apps/extension/src/App/Settings/ExtraSettings/ExtraSettings.tsx
apps/extension/src/App/Settings/ExtraSettings/types.ts
apps/extension/src/App/Settings/Settings.tsx
apps/extension/src/Approvals/ApproveConnection/ApproveConnection.tsx
apps/extension/src/background/approvals/handler.ts
apps/extension/src/background/approvals/index.ts
apps/extension/src/background/approvals/init.ts
apps/extension/src/background/approvals/messages.ts
apps/extension/src/background/approvals/service.ts
apps/extension/src/background/approvals/types.ts
apps/extension/src/background/approvals/utils.ts
apps/extension/src/background/index.ts
apps/extension/src/background/keyring/handler.ts
apps/extension/src/background/keyring/init.ts
apps/extension/src/content/index.ts
apps/extension/src/content/injected.ts
apps/extension/src/provider/Namada.ts
apps/extension/src/provider/Proxy.ts
apps/extension/src/provider/messages.ts
apps/extension/src/test/init.ts
packages/eslint-config/index.js
packages/integrations/src/Namada.ts

Closes #200.
Expected behaviour
------------------
1. When the interface loads at first nothing happens.
2. When the user clicks on the connect button, an approval pop-up appears in the extension. The interface connect button starts spinning.
a. If the reject button is clicked, the interface connect button stops spinning and the approval window closes. The extension cannot make any extension requests other than trying to connect again.
3. If the approve button is clicked, the interface account overview is loaded and the approval window closes.
4. The approved origin now exists in the extension local storage and the interface can make any extension requests normally.
1. Open the extension and click the settings icon.
2. Click the 'Connected sites' link.
3. The list of approved origins is …

feat: add ability to approve and revoke connections

---

packages/types/src/events.ts
specs/browser-extension/integration.md
specs/packages/examples.md
specs/packages/sdk.md

Provide developers with better examples of SDK usage from within a TypeScript application.

specs - Add SDK examples

---

apps/extension/src/App/App.components.ts
apps/extension/src/App/App.tsx
apps/extension/src/background/index.ts
apps/extension/src/background/keyring/handler.ts
apps/extension/src/background/keyring/init.ts
apps/extension/src/background/keyring/service.ts
apps/extension/src/background/keyring/types.ts
apps/extension/src/provider/Namada.ts
apps/extension/src/provider/messages.ts
packages/storage/src/store/IndexedDBKVStore.ts

Resolves #349
- we set transaction durability option to "strict"
- for firefox we use "readwriteflush" mode if possible. if not we display info icon with warning
In chrome storage should be durable by default,  so there should be no visible info icon
In firefox you should see yellow info icon with information about storage durability. Follow the steps from the icon title. Open extension popup again - info should be gone.
- this solution checks durability every time user opens the popup
- it sets durability options globally(for every storage we use),  we might want to change this in the future if it turns out to be slow

feat: strict storage durablity

---

e2e/src/index.test.ts
e2e/src/partial/index.ts
e2e/src/partial/transfer.ts
e2e/src/utils/index.ts
e2e/src/utils/values.ts

How to run tests:
- go to e2e
- just in case go to `e2e/.namada` and change `.version` file to v0.22.0 - this will retrigger all the downloads during first run
- `./setup-frontend.sh` and wait for both extension and interface  to start
- `yarn test` or` yarn test:watch` - first run will be slow as it will download bunch of stuff like: namada binaries, wasms, masp params
- wait for tests to finish(hopefully successfully :))
I've tested it on WSL/ubuntu. Pretty sure it should work on Mac too.

test(e2e): transfer from transparent to shielded address

---

apps/namada-interface/src/App/Token/EthereumBridge/EthereumBridge.tsx
e2e/genesis.toml
e2e/setup-frontend.sh
e2e/setup-namada.sh
e2e/src/index.test.ts
e2e/src/partial/approvals.ts
e2e/src/partial/index.ts
e2e/src/partial/setup.ts
e2e/src/partial/transfer.ts
e2e/src/utils/helpers.ts
e2e/src/utils/index.ts
e2e/src/utils/values.ts
packages/shared/lib/src/sdk/mod.js

How to run tests:
- go to e2e
- just in case go to `e2e/.namada` and change `.version` file to v0.22.0 - this will retrigger all the downloads during first run
- `./setup-frontend.sh` and wait for both extension and interface  to start
- `yarn test` or` yarn test:watch` - first run will be slow as it will download bunch of stuff like: namada binaries, wasms, masp params
- wait for tests to finish(hopefully successfully :))
I've tested it on WSL/ubuntu. Pretty sure it should work on Mac too.

test(e2e): bond, unbond, withdraw, add to bridge pool

---

.github/workflows/release-wallet.yml

Fix typo that made it into release script (duplicate `env:`)

feat/410 - Release script - fixed typo

---

.github/workflows/release-wallet.yml
packages/types/src/chain.ts

resolves #410 
I did a test deployment from this branch to here: https://652e6081e80443191bd26347--wallet-preview-heliax-dev.netlify.app/
If you load this in a browser _without_ the extension, it should link you to the assets, both of which you can install (in development mode on Chrome or temporarily if on FF).
1. Go to `namada-interface` repo, click on `Actions`, then `Deploy Interface and Release Extension`
2. Click the arrow on `Run Workflow`, then `Use Workflow from`, and enter `feat/410-update-download-link`
3. You should see the `REF` field, also paste `feat/410-update-download-link` into that (FYI, this can take a branch, tag, or commit hash)
4. Use the following values:
```
REACT_APP_NAMADA_CHAIN_ID=public-testnet-14.5d79b6958580 …
```

feat/410 - Auto generate build URL for setting download link

---

apps/namada-interface/README.md

Relates to #1 
The `namada-interface` app still contains a horribly out-of-date `README.md` file. Most of it was removed in this PR, with instructions to refer to the `README.md` at the root of the repo, which details the entire environment installation & setup for the interface+extension integration.

docs/1 - Remove out-of-date, inaccurate documentation for interface

---

apps/extension/src/background/keyring/keyring.ts
apps/extension/src/provider/data.mock.ts
packages/crypto/lib/Cargo.lock
packages/crypto/lib/Cargo.toml
packages/crypto/lib/src/crypto/bip32.rs
packages/crypto/lib/src/crypto/bip39.rs
packages/crypto/src/__tests__/crypto.test.ts
packages/crypto/src/index.ts
packages/shared/lib/Cargo.lock
packages/shared/lib/Cargo.toml
packages/shared/lib/src/types/address.rs
packages/shared/src/index.ts
packages/types/src/account.ts
packages/utils/src/helpers/index.ts

resolves #182 
This PR is to make use of Namada types & functions for key gen to align with process used in SDK.
__NOTES__
- `publicKey` is now being used from the `Address` type, and removed from the Key returned in `HDWallet`
- `HDWallet.derive()` now returns a `Key` type, and not `Keypair` (only private key)
- Updated to Namada v0.25.0
- BIP44 Path now requires `index` - type updated. To align with CLI, we derive using all path components including `index`. As `slip10_ed25519` derivation requires an array of path indices, there is a new helper to create this array from a `coinType` and `path`.

feat/182 - Private key derivation updates

---

apps/extension/src/App/Settings/ChangePassword/ChangePassword.tsx
apps/extension/src/Setup/Common/Password/Password.tsx
packages/components/src/Input/types.ts

Password fields were displaying `zxcvbnFeedback.suggestions` only as a hint, but they're being caught by validation. This PR shows these suggestions as errors instead.

Properly displaying validation messages on Password form

---

apps/extension/src/Setup/Common/ContainerHeader/ContainerHeader.tsx
apps/extension/src/Setup/Setup.tsx

When users reached the end of the Setup flow (confirmation), they could return to the previous step. This PR removes this possibility and also ensures that the seedPhrase gets deleted before moving forward to the next step.

Setup: Removing return button from last step

---

apps/extension/src/Setup/Common/Completion/Completion.tsx
apps/extension/src/Setup/ImportAccount/Steps/SeedPhraseImport/SeedPhraseImport.tsx
apps/extension/src/Setup/ImportAccount/Steps/SeedPhraseSetup/SeedPhraseSetup.tsx
apps/extension/src/Setup/Setup.tsx
apps/extension/src/background/keyring/handler.ts
apps/extension/src/background/keyring/init.ts
apps/extension/src/background/keyring/keyring.ts
apps/extension/src/background/keyring/messages.ts
apps/extension/src/background/keyring/service.ts
apps/extension/src/background/keyring/types.ts
apps/extension/src/utils/index.ts

Notes:
- Private key validation currently checks that the key is not more than 64 characters. I'm not sure if that should be *exactly* 64 characters.
- I'm not 100% sure I'm doing the right thing in the replacement of `selectedSeedPhrase` which is supposed to be used to allow deleting the seed phrase from `seedPhrase ` in `Setup.tsx`.

feat: Add ability to import an account from a private key

---

apps/extension/src/Setup/ImportAccount/Steps/SeedPhraseImport/SeedPhraseImport.tsx
apps/extension/src/background/keyring/keyring.ts
apps/extension/src/background/keyring/messages.ts
apps/extension/src/background/keyring/service.ts
apps/extension/src/background/keyring/types.ts
packages/crypto/lib/src/crypto/bip39.rs

feat/449 - Return Mnemonic errors to user

---

apps/extension/src/Setup/ImportAccount/Steps/SeedPhraseImport/SeedPhraseImport.tsx
apps/extension/src/utils/index.ts

feat/457 - Extension: Filter private key prefix if present

---

apps/extension/src/Setup/Ledger/Steps/LedgerConnect/LedgerConnect.tsx
apps/extension/src/background/ledger/ledger.ts

resolves #460 
Adds Ledger approval & rejection handling for connecting to wallet.

feat/460 - Add Ledger approval/rejection handling

---

apps/extension/src/background/keyring/handler.ts
apps/extension/src/background/keyring/init.ts
apps/extension/src/background/keyring/keyring.ts
apps/extension/src/background/keyring/service.ts
apps/extension/src/provider/InjectedNamada.ts
apps/extension/src/provider/Namada.ts
apps/extension/src/provider/Signer.ts
apps/extension/src/provider/messages.ts
packages/integrations/src/Namada.ts
packages/types/src/namada.ts
packages/types/src/signer.ts

resolves #455 
1 - Install this version of the extension
2 - Launch `namada-interface`:
```bash
yarn dev:local
```
3 - Create/Import at least 2 accounts in extension (to test that default account gets updated)
4 - In `namada-interface`, connect to extension, then open the console, and enter the following:
```
await namada.defaultAccount()
```
This should give you a result like:
```
{
"id": "9f318429-3627-50e2-b5f5-26f861b00d13",
"alias": "tester",
"address": "tnam1qz4sdx5jlh909j44uz46pf29ty0ztftfzc98s8dx",
"owner": "tnam1qz4sdx5jlh909j44uz46pf29ty0ztftfzc98s8dx",
"chainId": "localnet.aa8b11f87ddde352c2-0",
"path": {
"account": 0,
"change": 0,
"index": 0
},
"publicKey": "tpknam1qptrn64myunqr4847yq4cn0uwek5ecwc7eeexjfc5npmd5kmg6ex563n5as",
"type": "mnemonic"
}
```
You can switch the …

feat/455 - Extension: API to return default account

---

.github/workflows/deploy-wallet-at-merge-to-main.yml

Fixes main CI workflow that I broke in #456.
CI run on my fork to show that the fix works (fails at Slack notification as expected since it's a fork):
https://github.com/emccorson/namada-interface/actions/runs/6924320288
---
- Rename main CI workflow
- Fix main CI workflow broken by yarn file not being present

chore: fix main CI workflow broken by #456 and rename

---

apps/extension/src/Setup/Common/Completion/Completion.tsx
apps/extension/src/background/keyring/keyring.ts
apps/extension/src/background/keyring/service.ts

resolves #470 
__NOTE__ I needed to remove and add some `try`/`catch` to get the errors to propagate up to the Setup interface

feat/470 - Prevent duplicate keys from being added

---

packages/shared/lib/Cargo.lock
packages/shared/lib/Cargo.toml

Super simple PR to bump version of Namada to 0.27.0. Tested with no issues.

chore - Update to Namada 0.27.0

---

apps/extension/src/manifest/v3/_base.json

This PR undoes the hard-coding of the airdrop website URL in the Chrome extension manifest.
---
- Allow all URLs to interact with the extension

feat: allow all URLs to interact with extension

---

.gitattributes
apps/extension/package.json
apps/extension/src/content/index.ts
apps/extension/src/content/injected.ts
apps/extension/src/manifest/_base.json
apps/extension/webpack.config.js
yarn.lock

- Generate the manifest.json version field from package.json
- Make the injected and content scripts read the version from package.json
- Mark Cargo.lock and yarn.lock files as binary in git

Generate manifest extension version from package.json

---

apps/extension/src/provider/Namada.ts
packages/integrations/src/Namada.ts
packages/types/src/namada.ts

bug/480 - Make chainId optional to support released extension

---

apps/extension/src/provider/Namada.ts
packages/integrations/src/Namada.ts
packages/types/src/namada.ts
packages/types/src/signer.ts

bug/480 - Add optional chainId to accounts

---

apps/airdrop/src/App/AirdropConfirmation.tsx
apps/airdrop/src/App/App.components.ts
apps/airdrop/src/App/App.tsx
apps/airdrop/src/App/Common/AcceptTermsCheckbox/AcceptTermsCheckbox.tsx
apps/airdrop/src/App/Common/PageHeader/PageHeader.tsx
apps/airdrop/src/App/Layouts/SidebarPage/SidebarPage.tsx
apps/airdrop/src/App/Main.tsx

- claim confirmation copy
- terms of service -> terms and conditions + always opens in new tab
- redirect for "/" for unknown routes
- fix images links

feat: airdrop website copies and stuff

---

apps/extension/src/background/keyring/keyring.ts
apps/namada-interface/src/App/AccountOverview/DerivedAccounts/DerivedAccounts.tsx
apps/namada-interface/src/App/Token/IBCTransfer/IBCTransfer.tsx
apps/namada-interface/src/App/Token/TokenSend/TokenSend.tsx
apps/namada-interface/src/store/mocks.ts
packages/shared/lib/src/query.rs
packages/types/src/chain.ts
packages/types/src/tx/tokens/types/index.ts

Resolves #510 
_NOTE_ I also updated `AccountOverview` to only display tokens that have a balance, as there are many now.
Balances (every testnet token enabled)

feat/520 - Hook up additional testnet tokens

---

apps/extension/src/Approvals/ApproveTx/ConfirmTx.tsx
apps/extension/src/background/approvals/handler.ts
apps/extension/src/background/approvals/messages.ts
apps/extension/src/background/approvals/service.ts
apps/extension/src/manifest/v3/_base.json

This PR simply updates the following:
- Chrome `manifest.json` permissions removed for `identity` and `notifications`, as they are not used
- Approve Tx form was not properly authenticating users, this is fixed:
- Removed `password` as a parameter to `SubmitApprovedTxMsg`, and instead am using `UnlockVaultMsg` to validate user credentials - User will now see `Invalid password!` if authentication fails, and will be allowed to try again

Fix extension manifest permissions, fix approve Tx form

---

package.json
packages/crypto/package.json
packages/shared/.release-it.json
packages/shared/package.json
packages/shared/scripts/build.js
packages/shared/src/borsh-schemas.ts
packages/types/.release-it.json
packages/types/package.json
yarn.lock

- added release-it package
For now, to simplify things, I've added two separate dependencies and publish scripts to two separate packages.
You can test it with:
`yarn release:dry-run` inside `shared` and `types` packages

feat: yarn publish

---

apps/extension/src/background/index.ts
apps/extension/src/background/sdk/service.ts
apps/extension/src/test/init.ts

It was failing because there was no chain config present in the store.
Fixes #575.

fix: fix balances not displaying on initial connection

---

apps/extension/src/Approvals/Approvals.tsx
apps/extension/src/Approvals/ApproveSignature.tsx
apps/extension/src/Approvals/ConfirmSignature.tsx
apps/extension/src/Approvals/types.ts
apps/extension/src/background/approvals/handler.ts
apps/extension/src/background/approvals/init.ts
apps/extension/src/background/approvals/messages.ts
apps/extension/src/background/approvals/service.ts
apps/extension/src/background/index.ts
apps/extension/src/background/keyring/handler.ts
apps/extension/src/background/keyring/init.ts
apps/extension/src/background/keyring/keyring.ts
apps/extension/src/background/keyring/service.ts
apps/extension/src/provider/InjectedNamada.ts
apps/extension/src/provider/Namada.ts
apps/extension/src/provider/Signer.ts
apps/extension/src/provider/messages.ts
apps/extension/src/test/init.ts
packages/shared/lib/src/sdk/mod.rs
packages/types/src/namada.ts
packages/types/src/signer.ts

Adding functionality to extension to sign arbitrary data with the extension.
- Added a `.sign(address, data)` function to to `namada.getSigner()` to produce signatures for arbitrary data with our keys. This promise resolves when the user has both approved the signature and successfully authenticated, and is rejected if the user clicks `Reject`
- As the `data` can be of arbitrary size, similar to the Tx approvals, this gets added to a temporary in-memory key store, referenced by `msgId` passed to the approval window. There is a limit to the number of characters we can provide to the Approval popup via query-strings
- Install the extension, setup accounts, and copy one of the addresses (make sure it is unlocked before next step)
- In the browser console, do the following (replacing the …

Extension: Sign Arbitrary Data

---

apps/extension/src/Approvals/ApproveConnection.tsx

This should fix connections to the extension from intermittently failing when the approval window closes before the connection message has sent.

fix: await connect message send before closing tab

---

apps/extension/src/App/Settings/Network.tsx
apps/namada-interface/src/App/Token/EthereumBridge/EthereumBridge.tsx
apps/namada-interface/src/slices/StakingAndGovernance/actions.ts
apps/namada-interface/src/slices/channels.ts

resolves #591 
Fixes an issue where `chainId` was not using the updated configuration from extension for all staking requests.
Also fixed validation message on extension `Network` form (was incorrectly referencing "URL" in the Chain ID field)
- Similar to the original testing process for Network settings: Build the extension with one chain ID / RPC url (which will set default), then change them in the extension. Staking (and all other Tx) should succeed. 
- Alternatively, just change it to something other than what is already there (pointing to a node that is working and has balances for these accounts) - should contain correct `chainId` in Tx

bug/591 - Staking should use correct chain ID

---

apps/extension/src/background/keyring/handler.ts
apps/extension/src/background/keyring/init.ts
apps/extension/src/background/keyring/keyring.ts
apps/extension/src/background/keyring/service.ts
apps/extension/src/provider/InjectedNamada.ts
apps/extension/src/provider/Namada.ts
apps/extension/src/provider/Signer.ts
apps/extension/src/provider/messages.ts
packages/shared/lib/Cargo.lock
packages/shared/lib/Cargo.toml
packages/shared/lib/src/query.rs
packages/shared/lib/src/sdk/masp.rs
packages/shared/lib/src/sdk/mod.rs
packages/shared/lib/src/sdk/signature.rs
packages/shared/lib/src/sdk/tx.rs
packages/shared/lib/src/types/address.rs
packages/shared/lib/src/types/masp.rs
packages/shared/lib/src/types/query.rs
packages/types/src/namada.ts
packages/types/src/signer.ts

Updating Rust imports in `@namada/shared`
- Moved `BorshSerialize` `BorshDeserialize` and `BorshSerializeExt` to `namada::core::borsh`
- Fix spots where `SecretKey` was importing from `pos::common`. Switched to `namada::types::key::common`
- Also, import `SigScheme` & `Signature` from `namada::types::key::common`
- Hooked up `verify_arbitrary` to Extension API
```
// Change `signer` to address from your wallet:
await namada.sign({ signer: "tnam1qry3lnk03j965y92np6e25jvadk3kw9u7cvwjclp", data: "Arbitrary Data!" });
// Change these to match public key in your wallet for that account, and the hash and signature from the previous response
await namada.verify({
publicKey: "tpknam1qrxzmeyka3v43jnrhep9stnj3jhtgzq96ku3u6lk8hy8xqmjqgjtw8qu274",
hash: …
```

Update imports, fix signing

---

apps/namada-interface/package.json
apps/namada-interface/src/App/AccountOverview/AccountOverview.tsx
apps/namada-interface/src/App/AccountOverview/DerivedAccounts/DerivedAccounts.tsx
apps/namada-interface/src/App/App.tsx
apps/namada-interface/src/services/extensionEvents/handlers/namada.ts
apps/namada-interface/src/services/extensionEvents/provider.tsx
apps/namada-interface/src/slices/accounts.ts
apps/namada-interface/src/slices/chain.ts
apps/namada-interface/src/slices/coins.ts
apps/namada-interface/src/slices/index.ts
apps/namada-interface/src/slices/settings.ts
apps/namada-interface/src/store/index.ts
apps/namada-interface/src/store/mocks.ts
apps/namada-interface/src/store/store.ts
yarn.lock

This PR is the first part of replacing redux with jotai in the interface. There are different ways we could handle the data fetching depending on the UI requirements, but it should be easy to change and overall I'm happy enough with how jotai is to use compared to redux.
Currently redux has only been removed for the coins slice, so everywhere else jotai has been added, the existing redux code is still there. Data being fetched through jotai is still being fetched for redux too, so the work is duplicated but I'll fix that in a later PR.
---
- Fetch accounts, balances etc. for jotai as well as redux (currently duplicating fetching work but will be fixed later)
- Use jotai instead of redux for displaying data in DerivedAccounts
- Calculate total balance in AccountOverview instead of …

feat: begin replacing redux with jotai

---

apps/extension/src/Setup/ImportAccount/SeedPhraseImport.tsx

When clicking on Private Key we do not want to display: "Import with BIP39 Paassphrase" as it's being ignored anyway.

fix: do not display import with passphrase in pk flow

---

apps/faucet/package.json
apps/faucet/src/App/App.components.ts
apps/faucet/src/App/App.tsx
apps/faucet/src/App/Faucet.tsx
apps/faucet/src/utils/index.ts
yarn.lock

resolves #614 
Also addresses some of https://github.com/anoma/namada-interface/issues/607, but we need more information to finish this, and there may be some style updates we can incorporate later.

feat/614 - Faucet extension integration

---

apps/faucet/webpack.config.js

Use `https://faucet.heliax.click/` for assets when publishing to production

feat: Faucet - set URL to absolute when in production

---

apps/extension/src/background/chains/service.ts

The logic for query native token was a bit incorrect in the `ChainsService` - this has been fixed! The goal of this feature is that the native token will always match the chain that the extension is pointed to, assuming that chain is up and responding, and users should be able to remedy any issue related to this without restarting or upgrading the extension.
- Build the extension & interface with pointed to a local node (if you have balances, even better, as it's easier to see it working)
- If your node requires proxying, point the extension to `http://localhost:8010/proxy`
- You should see balances, and you can also inspect the Redux state to confirm the token address, which should be: `tnam1qxgfw7myv4dh0qna4hq0xdg6lx77fzl7dcem8h7e`
- In the Extension, in `Network`, set the values to …

fix: Chain service improvements for token

---

apps/faucet/src/utils/api.ts
apps/faucet/src/utils/types.ts

Resolves #634 
- Added specific message to display in the case of rate limiting errors (code `429`)
**NOTE** When deploying, set the faucet limit to 10 (instead of the default 1000) as it has been changed!

feat/634: Faucet - Catch rate limiting error code, provide specific message

---

apps/namada-interface/src/App/App.tsx
apps/namada-interface/src/App/Staking/NewBondingPosition/NewBondingPosition.tsx
apps/namada-interface/src/App/Staking/Staking.tsx
apps/namada-interface/src/App/Staking/UnbondPosition/UnbondPosition.tsx
apps/namada-interface/src/App/Staking/ValidatorDetails/ValidatorDetails.tsx
apps/namada-interface/src/App/Token/TokenSend/TokenSend.tsx
apps/namada-interface/src/App/Token/TokenSend/TokenSendForm.tsx
apps/namada-interface/src/slices/StakingAndGovernance/actions.ts
apps/namada-interface/src/slices/StakingAndGovernance/types.ts
apps/namada-interface/src/slices/fees.ts
apps/namada-interface/src/slices/notifications/reducers.ts
packages/components/src/AmountInput.tsx

Fixes bond, unbond and withdraw in #597.
---
- Use minimum gas price instead of hardcoded price for bond, unbond and withdraw
- Account for fees in maximum valid amount in bonding
- Warn the user when bonding too much to allow for future unbonding and withdrawal
- Refresh balances when a transaction completes (specifically when the toasts atom changes)
- Add max button to new bonding form
- Display gas fee in bonding and unbonding
- Sum all staking positions when calculating total staked amount
- Allow BigNumber for AmountInput min and max props
- Minor styling fixes

feat: staking gas fee improvements

---

apps/extension/src/background/approvals/handler.ts
apps/extension/src/background/approvals/init.ts
apps/extension/src/background/approvals/service.test.ts
apps/extension/src/background/approvals/service.ts
apps/extension/src/background/index.ts
apps/extension/src/content/events.ts
apps/extension/src/extension/ExtensionBroadcaster.ts
apps/extension/src/provider/InjectedNamada.ts
apps/extension/src/provider/Namada.ts
apps/extension/src/provider/Proxy.ts
apps/extension/src/provider/messages.ts
apps/extension/src/test/init.ts
apps/namada-interface/src/App/AccountOverview/AccountOverview.tsx
apps/namada-interface/src/App/App.tsx
apps/namada-interface/src/App/fetchEffects.ts
apps/namada-interface/src/index.tsx
apps/namada-interface/src/services/extensionEvents/handlers/namada.ts
apps/namada-interface/src/services/extensionEvents/provider.tsx
apps/namada-interface/src/slices/accounts.ts
apps/namada-interface/src/slices/fees.ts
apps/namada-interface/src/slices/settings.ts
packages/hooks/src/index.ts
packages/hooks/src/useEffectSkipFirstRender.ts
packages/integrations/src/Namada.ts
packages/integrations/src/hooks/useIntegration.ts
packages/types/src/events.ts
packages/types/src/namada.ts

- Use setter for fetching public keys to allow more control over when the fetch happens
- Add isConnected method and revoke event
- Add effects to handle accounts changed, chain changed, extension attached, and extension connected. Replaces fetches interspersed in App and AccountOverview
- Fix balances race condition
- Refresh public keys on Tx completed instead of toast change
- Wait for shared to init before rendering app
- Check for native token early in minimum gas price fetch
- Remove unneeded optional chaining in useIntegration

Data fetching fixes

---

apps/extension/src/Setup/AccountCreation/SeedPhraseConfirmation.tsx
apps/extension/src/Setup/AccountCreation/SeedPhraseWarning.tsx
apps/extension/src/Setup/ImportAccount/SeedPhraseImport.tsx
packages/components/src/ProgressIndicator.tsx

- Make enter key submit form on import keys page
- Stop yellow leaking in progress indicator
- Capitalize seed phrase confirmation message
- Make seed phrase warning fast in development
---
Progress indicator before:
After:

Minor extension UI fixes

---

.github/workflows/release-wallet.yml
apps/extension/package.json
apps/namada-interface/webpack.config.js

fix: Extension release version should read from extension package.json

---

apps/extension/src/Setup/Common/SeedPhraseList.tsx
apps/extension/src/Setup/Common/SeedPhraseListItem.tsx
apps/extension/src/Setup/ImportAccount/SeedPhraseImport.tsx
packages/crypto/lib/Cargo.lock
packages/crypto/lib/Cargo.toml
packages/crypto/lib/src/crypto/bip39.rs

Resolves #721 
NOTE: Checked with Chris Holt - we'll be keeping this design for now.
In addition to returning the error message containing the invalid index, the word input is highlighted for the user to fix:

feat/721: Return and display invalid word in mnemonic phrase

---

apps/extension/src/Approvals/Approvals.tsx
apps/extension/src/Approvals/ApproveTx/ApproveTx.tsx
apps/extension/src/Approvals/ApproveTx/ConfirmLedgerTx.tsx
apps/extension/src/Approvals/ApproveTx/ConfirmTx.tsx
apps/extension/src/background/approvals/handler.test.ts
apps/extension/src/background/approvals/handler.ts
apps/extension/src/background/approvals/init.ts
apps/extension/src/background/approvals/messages.ts
apps/extension/src/background/approvals/service.test.ts
apps/extension/src/background/approvals/service.ts
apps/extension/src/background/approvals/types.ts
apps/extension/src/background/ledger/handler.ts
apps/extension/src/background/ledger/messages.ts
apps/extension/src/background/ledger/service.ts
apps/extension/src/provider/Namada.ts
apps/extension/src/provider/Signer.ts
apps/extension/src/provider/messages.ts
apps/extension/src/utils/index.ts
apps/namada-interface/src/App/Proposals/ProposalDetails.tsx
apps/namada-interface/src/App/Token/TokenSend/TokenSendForm.tsx
apps/namada-interface/src/slices/StakingAndGovernance/actions.ts
packages/integrations/src/Namada.ts
packages/types/src/namada.ts
packages/types/src/signer.ts

Relates to #677 
_NOTE_ A follow-up PR will provide the interface changes to submit multiple Staking Tx
_NOTE_ Approval styles are still a bit wonky, this will be addressed in the follow-up PR to match designs
Testing this PR is simple: We need to ensure all Tx approvals/submission/events works as expected, as there isn't a way currently in the interface to invoke multiple Tx (will address in a separate PR).

feat/677 - Support querying pending Tx within extension

---

apps/extension/src/Approvals/ApproveTx/ApproveTx.tsx
apps/extension/src/background/approvals/service.ts
apps/extension/src/background/keyring/keyring.ts
apps/extension/src/background/keyring/service.ts
apps/extension/src/provider/Signer.ts
packages/sdk/docs/classes/Crypto.md
packages/sdk/docs/classes/EncodedTx.md
packages/sdk/docs/classes/Ledger.md
packages/sdk/docs/classes/Masp.md
packages/sdk/docs/classes/Mnemonic.md
packages/sdk/docs/classes/Rpc.md
packages/sdk/docs/classes/Sdk.md
packages/sdk/docs/classes/SignedTx.md
packages/sdk/docs/classes/Signing.md
packages/sdk/docs/classes/Tx.md
packages/sdk/docs/enums/KdfType.md
packages/sdk/docs/enums/TxType.md
packages/sdk/docs/modules.md
packages/sdk/src/tx/tx.ts
packages/shared/lib/src/sdk/mod.rs
packages/shared/lib/src/sdk/tx.rs
packages/shared/src/types.ts
packages/types/src/tx/schema/index.ts
packages/types/src/tx/schema/redelegate.ts
packages/types/src/tx/types.ts

Partially addresses #750 (_TODO_: Add any additional Tx needed by interface!)

feat/750: Add Redelegate Tx to SDK shared & js packages

---

packages/sdk/docs/classes/Crypto.md
packages/sdk/docs/classes/EncodedTx.md
packages/sdk/docs/classes/Ledger.md
packages/sdk/docs/classes/Masp.md
packages/sdk/docs/classes/Mnemonic.md
packages/sdk/docs/classes/Rpc.md
packages/sdk/docs/classes/Sdk.md
packages/sdk/docs/classes/SignedTx.md
packages/sdk/docs/classes/Signing.md
packages/sdk/docs/classes/Tx.md
packages/sdk/docs/enums/KdfType.md
packages/sdk/docs/modules.md
packages/sdk/src/tx/types.ts
packages/shared/lib/src/sdk/mod.rs

Resolves #752 
```ts
// make sure to yarn wasm:build
import { getSdk } from "@heliax/namada-sdk/web";
import initWasm from "@heliax/namada-sdk/initWeb";
(async () => {
// Init SDK
const { cryptoMemory } = await initWasm();
const { tx } = getSdk(cryptoMemory, rpcUrl, "", "");
// Build transfer Tx
const builtTx = tx.buildTransfer(wrapperTxProps, transferProps);
// Access inner Tx hash
const hash = builtTx.hash();
})()
```

feat/752: Return Tx hash when building transactions

---

.lintstagedrc.json
apps/namadillo/src/slices/validators.ts

Me and @jurevans were talking about paying a drink (alcoholic or not) for the interface team for every `console.log` left behind in the code.
Because I'm in clearly disadvantage of this, I've opened this PR to check for missing `console.log` during `husky` routine, and also fixed the one I've left behind in `myValidatorsAtom`.

Checking for console.log

---

apps/namadillo/package.json
apps/namadillo/src/App/Governance/ProposalAndVote.tsx
apps/namadillo/src/App/Governance/ProposalDescription.tsx
apps/namadillo/src/App/Governance/ProposalHeader.tsx
apps/namadillo/src/App/Governance/ProposalStatusSummary.tsx
apps/namadillo/src/App/Governance/VoteInfoCards.tsx
apps/namadillo/src/index.tsx
apps/namadillo/src/slices/proposals/atoms.ts
apps/namadillo/src/store/index.tsx
apps/namadillo/src/store/utils.ts
apps/namadillo/src/utils/index.ts
package.json
yarn.lock

Adds persistent cache for react query.
- Persist proposal data and show in proposal info components
- Refactor proposal info page components
- Move dependencies from root to namadillo
To test this, open a proposal page such as `http://localhost:5173/governance/proposal/0`. The first time the page loads, the data will be fetched from the RPC. Refresh the page and you should see that the data loads faster since it has been persisted in the browser. You can also see there is an entry in Indexed DB.
I still need to figure out how to use the persisted data to speed up the proposals table, so for the moment the proposals table does not use the cached data. This will be done in a later PR.

Namadillo persist cache

---

packages/sdk/docs/classes/Crypto.md
packages/sdk/docs/classes/EncodedTx.md
packages/sdk/docs/classes/Ledger.md
packages/sdk/docs/classes/Masp.md
packages/sdk/docs/classes/Mnemonic.md
packages/sdk/docs/classes/Rpc.md
packages/sdk/docs/classes/Sdk.md
packages/sdk/docs/classes/SignedTx.md
packages/sdk/docs/classes/Signing.md
packages/sdk/docs/classes/Tx.md
packages/sdk/docs/enums/KdfType.md
packages/sdk/docs/enums/TxType.md
packages/sdk/docs/modules.md
packages/sdk/examples/submitTransfer.ts
packages/sdk/src/tests/tx.test.ts
packages/sdk/src/tx/tx.ts
packages/shared/lib/Cargo.lock
packages/shared/lib/Cargo.toml
packages/shared/lib/src/query.rs
packages/shared/lib/src/sdk/mod.rs
packages/shared/lib/src/sdk/tx.rs
packages/shared/src/types.ts
packages/types/src/tx/schema/index.ts
packages/types/src/tx/schema/transparentTransfer.ts
packages/types/src/tx/schema/wrapperTx.ts
packages/types/src/tx/types.ts

This PR includes the changes to support Namada `v0.39.0`, and makes some changes to our SDK package and types to indicate `Transparent Transfer` instead of simply `Transfer`
- Future PRs will implement the other transfer types: `ShieldingTransfer`, `UnshieldingTransfer`, and `ShieldedTransfer`
- Confirm that Namadillo and the extension behave properly with this update

feat: bump to Namada 0.39.0, update transparent transfer

---

packages/sdk/docs/classes/Crypto.md
packages/sdk/docs/classes/EncodedTx.md
packages/sdk/docs/classes/Ledger.md
packages/sdk/docs/classes/Masp.md
packages/sdk/docs/classes/Mnemonic.md
packages/sdk/docs/classes/Rpc.md
packages/sdk/docs/classes/Sdk.md
packages/sdk/docs/classes/SignedTx.md
packages/sdk/docs/classes/Signing.md
packages/sdk/docs/classes/Tx.md
packages/sdk/docs/enums/KdfType.md
packages/sdk/docs/modules.md
packages/sdk/src/sdk.ts

feat/860 - Update Sdk instance with new settings

---

apps/namadillo/src/App/Settings/Advanced.tsx
apps/namadillo/src/App/Staking/AllValidatorsTable.tsx
apps/namadillo/src/App/Staking/IncrementBondingTable.tsx
apps/namadillo/src/App/Staking/MyValidatorsTable.tsx
apps/namadillo/src/App/Staking/ReDelegateTable.tsx
apps/namadillo/src/App/Staking/UnbondingAmountsTable.tsx
apps/namadillo/src/App/Staking/UnstakeBondingTable.tsx
apps/namadillo/src/App/Staking/ValidatorAlias.tsx
apps/namadillo/src/App/Staking/ValidatorAliasPlaceholder.tsx
apps/namadillo/src/App/Staking/ValidatorCard.tsx
apps/namadillo/src/App/Staking/ValidatorInfoPanel.tsx
apps/namadillo/src/App/Staking/ValidatorThumb.tsx
packages/utils/src/helpers/index.ts

This PR introduces a few UI tweaks on validators cards, displaying empty aliases and an avatar placeholder. This is a first attempt to define the UI, pinging @ChrisHoltDesign to give a hand on that o/
Fixes #865 
Fixes #866

Namadillo: Few UI tweaks

---

apps/extension/src/provider/InjectedProxy.ts
apps/namadillo/src/App/Common/TextLink.tsx
apps/namadillo/src/App/Common/ToastErrorDescription.tsx
apps/namadillo/src/App/Common/TransactionFees.tsx
apps/namadillo/src/App/Governance/SubmitVote.tsx
apps/namadillo/src/App/Staking/IncrementBonding.tsx
apps/namadillo/src/App/Staking/ReDelegate.tsx
apps/namadillo/src/App/Staking/Unstake.tsx
apps/namadillo/src/App/Staking/WithdrawalButton.tsx
apps/namadillo/src/hooks/useTransactionNotifications.tsx
apps/namadillo/src/lib/query.ts

I'm guessing with the styling/layout of these toasts with error messages, so UX comments especially welcome!
---
- Stop error toasts from auto-closing on timeout
- Add error messages in toasts
- Show error toast when signing fails
- Remove "Error:" prefix from extension error messages
- Fix success toasts showing for stake/redelegate errors

feat: add error messages in toasts

---

apps/extension/src/background/approvals/handler.test.ts
apps/extension/src/background/approvals/handler.ts
apps/extension/src/background/approvals/service.test.ts
apps/extension/src/background/approvals/service.ts

Fixes an issue where approval promise was not being resolved when the transaction was rejected.
- Updated to resolve promise on reject sign tx
- Moved `rejectSignature` -> `rejectSignArbitrary` to avoid confusion
- Updated tests
- Create a transaction, and submit
- In the first view in the popup, click `Reject` -_NOTE_ the interface does not currently display a response, but (in the case of Bond) the `Stake` button will be available again. You can see the error message in the console

bug: Approve sign promise should resolve when rejected

---

apps/namadillo/src/hooks/useExtensionEvents.tsx

Before this PR, Namadillo was disconnected after removing any origin in the extension. Now we verify if it is still connected.
Fixes #898

Namadillo: disconnecting only if the respective origin access was revoked

---

.github/workflows/release-namadillo.yml
apps/namadillo/.release-it.cjs
apps/namadillo/CHANGELOG.md
apps/namadillo/README-dist.md
apps/namadillo/RELEASE.md
apps/namadillo/package.json
apps/namadillo/scripts/package.sh
apps/namadillo/src/index.tsx
yarn.lock

This PR adds scripts and documentation for releasing Namadillo.
I have created a temporary release on my fork to show what a real release will look like:
https://github.com/emccorson/namada-interface/actions/runs/9656944071
https://github.com/emccorson/namada-interface/releases/tag/namadillo-1.0.0
There needs to be some follow-up work to define a process for adding changelog entries. For now, I have loosely based this PR on how the main namada team does changelog entries and created #893 for changelog discussion.
---
- Add scripts to release namadillo
- Add release process documentation
- Add changelog
- Add README for distribution
- Remove web vitals from namadillo

Namadillo release configuration

---

apps/namadillo/src/App/Staking/ReDelegateRemoveStake.tsx
packages/components/src/AmountInput.tsx

- Don't overwrite user's input string
- Clear error message when bad input is cleared
- Throw error on too many zeroes after decimal point
- Make re-delegate clear button clear input instead of setting it to 0
Fixes #905.

fix: fix AmountInput bugs

---

apps/namadillo/src/App/Governance/ProposalHeader.tsx
apps/namadillo/src/App/Sidebars/ProposalDiscord.tsx
packages/components/src/ActionButton.tsx

Fix the Mainnet Phases link using `<a>` instead of `<button>`
Also, update the default value for `as` prop on `<ActionButton>` to observe the presence of the `href` prop

fix: mainnet phases link

---

packages/shared/lib/src/sdk/mod.rs
packages/types/src/tx/schema/batchTxResult.ts
packages/types/src/tx/schema/txResponse.ts

Resolves #891 
This adds the remaining details in the `ProcessTxResponse::Applied(resp)`, so the result of `rpc.broadcastTx()` can return this data to the client.
- In `apps/namadillo/src/lib/query.ts`, when invoking `rpc.broadcastTx()`, assign response to a variable and log it (the interface currently doesn't do anything with this data, but we will likely want to, at least to display `gasUsed` & `height`)

feat/891: Adding info to broadcast Tx response

---

apps/namadillo/src/App/AppSetup.tsx
apps/namadillo/src/App/Common/Container.tsx
apps/namadillo/src/App/Common/Search.tsx

Several small bug fixes for Namadillo.
With the fix about reducing the menu height to stop the scroll, I was only able to reproduce this on Firefox and not Chrome, and I'm not entirely sure why the heights are different. I think we could have a better solution for this by calculating the panel heights based on the viewport height, but it will potentially be tricky to do this nicely, so for now I've just reduced the pixel height.
---
- Add missing space in indexer error message. Fixes #911.
- Fix padding in search input on Firefox. Fixes #802.
- Reduce menu height to stop small scroll. Fixes #912.
- ~Don't open menu when changing to small screen. Fixes #914.~ Dropped.
- Make side menu viewport height on mobile.

Small fixes 2024-07-08

---

packages/types/README.md
packages/types/docs/.nojekyll
packages/types/docs/classes/BatchTxResultMsgValue.md
packages/types/docs/classes/BondMsgValue.md
packages/types/docs/classes/EthBridgeTransferMsgValue.md
packages/types/docs/classes/IbcTransferMsgValue.md
packages/types/docs/classes/Message.md
packages/types/docs/classes/RedelegateMsgValue.md
packages/types/docs/classes/SignatureMsgValue.md
packages/types/docs/classes/TransparentTransferMsgValue.md
packages/types/docs/classes/TxResponseMsgValue.md
packages/types/docs/classes/UnbondMsgValue.md
packages/types/docs/classes/VoteProposalMsgValue.md
packages/types/docs/classes/WithdrawMsgValue.md
packages/types/docs/classes/WrapperTxMsgValue.md
packages/types/docs/enums/AccountType.md
packages/types/docs/enums/BridgeType.md
packages/types/docs/enums/Events.md
packages/types/docs/enums/KeplrEvents.md
packages/types/docs/enums/MetamaskEvents.md
packages/types/docs/interfaces/IMessage.md
packages/types/docs/interfaces/Namada.md
packages/types/docs/interfaces/Signer.md
packages/types/docs/modules.md
packages/types/package.json
yarn.lock

feat/917: Add docs build to types package

---

package.json
yarn.lock

This super low priority PR bumps the version of git-commit-msg-linter to get the fix for:
https://github.com/legend80s/git-commit-msg-linter/issues/48

chore: bump git-commit-msg-linter to get shebang fix

---

apps/namadillo/package.json
apps/namadillo/src/App/Common/TableWithPaginator.tsx
apps/namadillo/src/App/Governance/AllProposalsTable.tsx
apps/namadillo/src/App/Staking/ValidatorsTable.tsx
apps/namadillo/src/atoms/proposals/atoms.ts
apps/namadillo/src/atoms/proposals/functions.ts
apps/namadillo/src/atoms/validators/services.ts
yarn.lock

Note for testing: Needs the latest version of namada-indexer including https://github.com/anoma/namada-indexer/pull/75.
---
- Bump indexer to 0.0.17 to get the all proposals endpoint.
- Refactor TableWithPaginator to not create its own pages. It now just receives pages of items and lets its parent handle creating pages.
- Add pagination to the All Proposals table.
- Fix proposal count by counting all proposals, not just one page of proposals. These numbers are shown on the right panel of the Governance page under "Total Proposals", "Proposals in Voting Period" etc.
- Fetch all validators, not just the first page.

Namadillo: Add proposals table pagination, fix pagination bugs

---

packages/components/src/ActionButton.tsx

This was throwing a React error in the console.

fix: stop passing ActionButton props to DOM element

---

apps/namadillo/src/App/Governance/ProposalDescription.tsx
apps/namadillo/src/App/Governance/ProposalHeader.tsx
apps/namadillo/src/App/Governance/ProposalStatusSummary.tsx
apps/namadillo/src/App/Governance/VoteInfoCards.tsx
apps/namadillo/src/atoms/proposals/atoms.ts
apps/namadillo/src/atoms/proposals/functions.ts
packages/types/src/proposals.ts

- Show proposal activation time instead of activation epoch
- Remove unused IndexedDB proposal caching
- This could be added again later if we need it, but it was complicating the proposal code a bit so I removed it. The ability to cache queries in IndexedDB is still present though.

Show proposal activation time, remove cached proposals

---

packages/shared/lib/src/sdk/transaction.rs
packages/shared/lib/src/sdk/tx.rs

Resolves #946 
Currently, the denomination displayed in the extension approvals is inconsistent. Should be in `NAM`.

feat/946: Consistent denom in Tx Details

---

apps/extension/webpack.config.js
apps/namadillo/src/App/Common/ToastErrorDescription.tsx
apps/namadillo/src/App/Governance/GovernanceOverview.tsx
apps/namadillo/src/App/Governance/ProposalDescription.tsx
apps/namadillo/src/App/Governance/ProposalStatusSummary.tsx
apps/namadillo/src/App/Staking/AllValidatorsTable.tsx
apps/namadillo/src/App/Staking/IncrementBondingTable.tsx
apps/namadillo/src/App/Staking/MyValidatorsTable.tsx
apps/namadillo/src/App/Staking/ReDelegateTable.tsx
apps/namadillo/src/App/Staking/UnstakeBondingTable.tsx
apps/namadillo/src/hooks/useTransactionNotifications.tsx
packages/components/src/Currency.tsx

- Separate long NAM values with commas. Fixes #942.
- Don't show all proposals as upcoming proposals
- This bug will show up if there are both upcoming and non-upcoming proposals and causes all proposals to be listed as upcoming. If there are no upcoming proposals, the bug will not appear. 
- Hide redundant title in proposal description. Fixes #951.
- Use "-" in show less proposal description link
- Use correct .env to get chain ID in extension
- The webpack config was still pointing to app/namada-inteface/.env.

Separate NAM with commas + other Namadillo fixes

---

apps/namadillo/src/App/Staking/ReDelegate.tsx
apps/namadillo/src/lib/query.ts
apps/namadillo/src/lib/staking.ts

This PR contains the following fixes:
- When Public Key was not revealed, the server was returning 404 and the app was throwing an unhandled exception
- After submitting re-delegate first form, nothing was happening. Now it goes to the next form
- Fixed a reference issue after deleting an object property on re-delegate

Namadillo: fixing some errors on re-delegate flow

---

apps/faucet/package.json
apps/faucet/src/App/App.tsx
apps/faucet/src/App/Faucet.tsx
apps/faucet/src/index.tsx
apps/faucet/src/utils/api.ts
apps/faucet/src/utils/types.ts
apps/faucet/webpack.config.js
yarn.lock

This PR takes the current faucet app (last updated for SE) and makes it work again
- Edit `apps/faucet/.env` with the following:
(Not sure if all of these are necessary, but the URL definitely is)
```bash
NAMADA_INTERFACE_FAUCET_API_URL=https://faucet.public.heliax.work/internal-devnet-it.14814a0e13c
NAMADA_INTERFACE_FAUCET_API_ENDPOINT=/api/v1/faucet
NAMADA_INTERFACE_FAUCET_LIMIT=1000
```
- It would be useful to also connect the Namadillo to this indexer so you can see and user your funds:
- Set namadillo indexer to: `https://indexer.public.heliax.work/internal-devnet-it.14814a0e13c`
- Set RPC to `https://proxy.public.heliax.work/internal-devnet-it.14814a0e13c` (the RPC returned by this indexer is incorrect, so override it)
- Set `Network` to `internal-devnet-it.14814a0e13c` in extension …

fix - Update faucet app

---

apps/extension/src/extension/ExtensionRequester.ts
apps/extension/src/extension/ExtensionRouter.ts

This fixes NAM amounts showing as NaN when approving a tx in Firefox.
Fixes #952.
Before:
After:

fix: support sending BigNumber messages in Firefox

---

apps/namadillo/src/hooks/useTransactionCallbacks.tsx
apps/namadillo/src/hooks/useTransactionNotifications.tsx
apps/namadillo/src/types/events.ts
apps/namadillo/src/utils/index.ts

Fix the notifications were not being removed when deploying the Namadillo
The issue was caused because the transaction event listeners weren't initialized due to the hook `useEffectSkipFirstRender`, which skips the listener creation on first render.
I'm not aware why it was implemented like this in the past, maybe it was to fix another issue of a concurrency listener creation.
Anyway, I created the individual hook listener `useTransactionEventListener` that handle the subscribe and also the unsubscribe with `useEffect`, which allow us to reinvoke the method anytime we want and it's more a "react oriented" solution

fix: fix notifications were not being removed

---

.github/actions/rust-cache/action.yml
.github/actions/yarn-cache/action.yml
.github/workflows/deploy-wallet-at-merge-to-main.yml
.github/workflows/deploy-wallet-at-pr.yml

Various CI improvements, mainly to speed up CI runs and hopefully fix the yarn install timeouts.
Currently the CI is running for PRs at around 20 minutes, but once this is merged into main PRs should take less than 10 minutes to run in the CI.
Example yarn install timeout:
https://github.com/anoma/namada-interface/actions/runs/10198828123/job/28214547488
I'm not 100% sure why the yarn install is sometimes timing out. I think it could be to do with how puppeteer is downloaded to the home directory and then linked by yarn, so I've added puppeteer to the yarn cache. If the problem comes up again after this PR, I'll look into it further.
---
- Cache puppeteer to speed up yarn install and hopefully fix timeouts
- Use a different Rust cache action (seems faster)
- Run yarn without hardened mode …

CI yarn install timeout fix + various CI improvements

---

apps/namadillo/src/App/Staking/MyValidatorsTable.tsx

Move voting power column so we always have the `user's NAMs` first, then later the `Voting Power` and finishing with the `Commision`

feat: move voting power column

---

apps/extension/src/App/Accounts/DeleteAccount.tsx

fix: fix broken "Back Up My Wallet" extension link

---

apps/namadillo/package.json
apps/namadillo/src/atoms/validators/functions.ts
yarn.lock

From slack:
> Small update regarding withdraw button. So I changed code a bit, now we compare current epoch to withdraw epoch to determine if withdraw is possible(before we were comparing time left to current time). Also if time left is obviously incorrect(this might happen if the genesis parameters are wrong) we will display "N/A". But note that  this is only a fallback. For live version we should never see "N/A" as genesis parameters have to be correct  :smile: So this is only for testing in case someone gets confused because withdraws are not working.
Use branch from this [PR](https://github.com/anoma/namada-indexer/pull/95) or wait for merge :) 🙏

feat: improve canWithdraw logic

---

apps/namadillo/public/config.toml
apps/namadillo/src/App/Staking/AllValidatorsTable.tsx
apps/namadillo/src/App/Staking/IncrementBondingTable.tsx
apps/namadillo/src/App/Staking/MyValidatorsTable.tsx
apps/namadillo/src/App/Staking/ReDelegateTable.tsx
apps/namadillo/src/App/Staking/UnstakeBondingTable.tsx
apps/namadillo/src/hooks/useValidatorTableSorting.tsx
apps/namadillo/src/types.d.ts
apps/namadillo/src/utils/sorting.ts
packages/components/src/StyledTable.tsx
packages/components/src/StyledTableHead.tsx
storybook/src/stories/StyledTable.stories.tsx

This PR introduces a way to add sortable headers to tables, and implement the functionality to the staking tables.
Closes #786

Namadillo: Adding sortable headers to tables

---

apps/namadillo/src/App/Sidebars/ValidatorDiversification.tsx
packages/shared/lib/src/sdk/tx.rs

Closes #972.
- Show tx detail gas limit in gas units, not NAM
- Show gas price, not total fees, in tx details
- This field is still named `feeAmount`, but I was wondering about changing it to `gasPrice`, which would match what Namada CLI calls it and I think is a less confusing name. I can add it to this PR or do it later if we decide to change the name.
---
Example transaction with gas price 0.00001 NAM and gas limit 1000000:

Fix gas price and gas limit in tx details

---

apps/namadillo/src/App/Common/ActiveAccount.tsx

Simple PR to allow clicking to copy address instead of public key in Namadillo
- In Namadillo, click upper-right-most button with selected account name, then check the copied value - this should be the account's address, not the public key

bug: Namadillo - Click to copy address should copy address, not public key

---

apps/namadillo/src/App/Common/QueryProvider.tsx
apps/namadillo/src/index.tsx

We don't need to refetch if the server responds with a client / request error (HTTP 4xx).
This PR adds this implementation, based on this section of jotai-react-query docs https://github.com/jotaijs/jotai-tanstack-query?tab=readme-ov-file#referencing-the-same-instance-of-query-client-in-your-project .

feat(namadillo): avoid retrying for 4xx errors

---

apps/namadillo/src/App/Staking/Unstake.tsx
apps/namadillo/src/App/Staking/UnstakeBondingTable.tsx

This PR won't let users to unbond more than what they have in a validator, causing an error. Displays a simple "Invalid amount" message and changes the color to red for the invalid amounts.

feat(namadillo): adding validation to unstake amounts

---

apps/namadillo/src/App/Common/QueryProvider.tsx

We've introduced some different default settings for the store in a preview commit, however `getDefaultStore` in some other places started to refer to a store different than the one used by jotai-tanstack-query, leading to some unexpected behaviours. This PR simply adds this reference to the query provider.

Namadillo: fixing error on loading token

---

apps/extension/src/Approvals/Commitment.tsx
apps/extension/src/Approvals/index.tsx
apps/namadillo/src/App/Governance/ProposalHeader.tsx
apps/namadillo/src/utils/index.ts

- Namadillo: fix uncaught error in proposal time remaining
- Extension: show proposal id and vote tx details in Firefox
- This is another case of a Firefox bug due to the difference in how Firefox and Chrome serialize messages passed between the background and content scripts. Firefox uses the structured clone algorithm but Chrome uses JSON serialization.

Fix vote tx details on Firefox + uncaught error

---

apps/namadillo/vite.config.mjs

Start the checker UI minimized, to make it less intrusive during development

feat: start the checker ui minimized

---

packages/shared/lib/Cargo.lock
packages/shared/lib/Cargo.toml
packages/shared/lib/src/query.rs
packages/shared/lib/src/rpc_client.rs
packages/shared/lib/src/sdk/args.rs
packages/shared/lib/src/sdk/io.rs
packages/shared/lib/src/sdk/masp/masp_node.rs
packages/shared/lib/src/sdk/masp/masp_web.rs
packages/shared/lib/src/sdk/mod.rs
packages/shared/lib/src/sdk/signature.rs
packages/shared/lib/src/sdk/transaction.rs
packages/shared/lib/src/sdk/tx.rs
packages/shared/lib/src/sdk/wallet/mod.rs
packages/shared/lib/src/sdk/wallet/wallet_node.rs
packages/shared/lib/src/sdk/wallet/wallet_web.rs
packages/shared/lib/src/types/address.rs
packages/shared/lib/src/types/masp.rs
packages/shared/lib/src/types/query.rs

In https://github.com/anoma/namada/pull/3402 we're removing the `namada` crate that contained various unrelated stuff. This PR switches to use `namada_sdk` that will provide the same modules instead (note that this will not compile until https://github.com/anoma/namada/pull/3402 is released, hopefully in v0.40.0, but I did check it against a local path)

chore: switch to use namada_sdk instead of namada

---

apps/extension/src/App/Accounts/ViewAccount.tsx
apps/extension/src/Setup/Common/Completion.tsx
apps/namadillo/src/atoms/chain/atoms.ts
packages/components/src/ViewKeys.tsx

Resolves #1015 
Lengthen keys in Setup view:
Lengthen keys in `View Keys` view:

Extension - address feedback

---

.github/workflows/release-wallet.yml
apps/extension/.env.sample
apps/extension/.gitignore
apps/extension/README.md
apps/extension/webpack.config.js

This PR simply updates the CI script to release the extension. This will build the Chrome & Firefox extensions with the chain ID set in `apps/extension/.env` and publish the assets to Github.
**NOTE** I removed all but one `.env` var, though in the near future we may be adding a `NAMADA_INTERFACE_LEDGER_TRANSPORT` option, if it is needed to use extension with an emulated Ledger (this is being investigated in https://github.com/anoma/namada-interface/issues/1006) - If so, I will document transport options then.
1. Navigate to `Actions` in Github
2. Click `Deploy interface and release Extension` (__NOTE__: This has been renamed, but will appear with the old label until this is merged to `main`)
3. In the options for `Run workflow`, specify `chore/update-extension-ci` in `Use workflow …

chore: Extension - Update release CI script

---

apps/namadillo/src/App/Common/NamCurrency.tsx
apps/namadillo/src/App/Common/TransactionFees.tsx
apps/namadillo/src/App/Governance/ProposalStatusSummary.tsx
apps/namadillo/src/App/Governance/VoteInfoCards.tsx
apps/namadillo/src/App/Staking/AllValidatorsTable.tsx
apps/namadillo/src/App/Staking/IncrementBondingTable.tsx
apps/namadillo/src/App/Staking/MyValidatorsTable.tsx
apps/namadillo/src/App/Staking/ReDelegateTable.tsx
apps/namadillo/src/App/Staking/UnstakeBondingTable.tsx
packages/config/eslint/react.js

Resolve `forceBalanceDisplay` warning
Also, enable the `ignoreRestSiblings: true` which is great for removing one prop from `props` to pass to children and could help on future issues similar to this one:
```tsx
({ forceBalanceDisplay, ...props })  => <div {...props} />
```

feat: resolve forceBalanceDisplay warning

---

apps/namadillo/src/App/Common/TransactionFees.tsx
apps/namadillo/src/App/Governance/SubmitVote.tsx
apps/namadillo/src/App/Staking/IncrementBonding.tsx
apps/namadillo/src/App/Staking/ReDelegate.tsx
apps/namadillo/src/App/Staking/ReDelegateAssignStake.tsx
apps/namadillo/src/App/Staking/Unstake.tsx
apps/namadillo/src/atoms/fees/atoms.ts
apps/namadillo/src/lib/query.ts
apps/namadillo/src/types.d.ts

- Add default gas config and use it to display correct transaction fees
- Disallow redelegating when it would result in no transactions (e.g. redelegating to the same validator)
- Refactor redelegate validation and display clearer error message in submit button
Fixes #975.

fix: fix fees and redelegating to same validator

---

apps/namadillo/src/App/Staking/MyValidatorsTable.tsx
apps/namadillo/src/App/Staking/StakingOverview.tsx
apps/namadillo/src/App/Staking/StakingSummary.tsx
apps/namadillo/src/App/Staking/UnbondingAmountsTable.tsx
apps/namadillo/src/App/Staking/UnstakeBondingTable.tsx
apps/namadillo/src/App/Staking/WithdrawalButton.tsx
apps/namadillo/src/atoms/syncStatus/atoms.ts
apps/namadillo/src/atoms/validators/atoms.ts
apps/namadillo/src/atoms/validators/functions.ts
apps/namadillo/src/atoms/validators/services.ts
apps/namadillo/src/types.d.ts

This PR refactors all the withdraw and unbonding data to be available inside MyValidator type. This will also fix #1023 .

Namadillo: Refactoring Unbonding and Withdraw, moving them to MyValidator type

---

apps/namadillo/src/App/Common/Toast.tsx
apps/namadillo/src/App/Staking/IncrementBonding.tsx
apps/namadillo/src/App/Staking/ReDelegate.tsx
apps/namadillo/src/hooks/useTransactionNotifications.tsx

- Start toast timeout when toast type changes
- This fixes toasts not automatically closing when a pending toast turns into a success/failure toast
- Set default timeout for success/error toasts
- This fixes some toasts missing the timeout property e.g. the success toast in SubmitVote

Toast fixes 🍞

---

apps/namadillo/package.json
apps/namadillo/src/App/Governance/ProposalHeader.tsx
apps/namadillo/src/App/Governance/ProposalStatusSummary.tsx
apps/namadillo/src/App/Governance/SubmitVote.tsx
apps/namadillo/src/atoms/api.ts
apps/namadillo/src/atoms/chain/services.ts
apps/namadillo/src/atoms/etc.ts
apps/namadillo/src/atoms/proposals/atoms.ts
apps/namadillo/src/atoms/proposals/functions.ts
apps/namadillo/src/atoms/settings/services.ts
apps/namadillo/src/atoms/validators/functions.ts
apps/namadillo/src/hooks/useTransactionCallbacks.tsx
apps/namadillo/src/types.d.ts
yarn.lock

- fixed epoch estimations
- fix for vote button - now disabled if address did not have active bonds before proposal stared
- added polling for proposal view after sending vote tx
- small changes due to using new indexer client generation library
Test it with 0.43.0 and [this ](https://github.com/anoma/namada-indexer/pull/94) indexer

bug: governance and unbonding fixes

---

apps/extension/src/manifest/v3/_base.json

Removes the `offscreen` permission, this caused our extension to be rejected.

fix: Extension - Remove unused Chrome permission

---

apps/extension/package.json
apps/extension/src/App/Accounts/DeleteAccount.tsx
apps/extension/src/App/Accounts/ViewMnemonic.tsx
apps/extension/src/App/App.tsx
apps/extension/src/App/AppContent.tsx
apps/extension/src/App/Common/AppHeader.tsx
apps/extension/src/App/Common/AppHeaderNavigation.tsx
apps/extension/src/App/Settings/Warnings.tsx
apps/extension/src/App/routes.ts
apps/extension/src/Setup/Start.tsx
apps/extension/src/utils/index.ts
yarn.lock

Resolves #1061 
This PR moves the indexedDB durability warning out of the main view, and fixes the width. What I did is add a alert icon to the Settings menu, which will appear in Firefox if the DB is determined to not be durable. This navigates to a general `Warnings` page that shows any warnings (in this case, just the indexed DB warning)
**NOTE** I also applied some similar styles to fix width issues in certain views. Checked these again in Chrome to ensure that it didn't introduce any issues.
- Install add-on in Firefox, then navigate to `about:config`
- Set `dom.indexedDB.experimental` to `false` (if it isn't already), and the alert icon should be available in the Settings menu
- Set `dom.indexedDB.experimental` to `true`, then this alert will go away
Menu when store is _not_ durable …

feat/1061: Firefox - Move durability warning out of main App view

---

apps/namadillo/src/App/Common/Setup.tsx
apps/namadillo/src/App/Settings/Advanced.tsx

This PR fixes an error introduced in #1067 where Advanced panel starts to display a wrong "null" string.

Namadillo: fixing message appearing due to wrong string cast

---

.github/workflows/release-faucet.yml
apps/faucet/.env.sample
apps/faucet/README.md
apps/faucet/src/App/App.tsx
apps/faucet/src/App/Faucet.tsx
apps/faucet/src/App/SettingsForm.tsx
apps/faucet/src/App/index.ts
apps/faucet/src/utils/api.ts
apps/faucet/src/utils/types.ts
apps/faucet/src/workers/index.ts
apps/faucet/src/workers/powWorker.ts

Resolves #1060 
When the Faucet API returns a high `difficulty` (e.g., 3) the `computePowSolution` method causes the tab to hang, which can issue warnings to the user. This PR moves that computation into a web-worker.
- Load the faucet app and connect to extension
- Ensure that on submit, it displays `Computing POW Solution`, followed by `Processing Faucet Transfer` (Not sure if there's a better way to inspect what is going on while computing
**NOTE**
Testing against our API should finish very quickly, as `difficulty` is set at zero: https://faucet.public.heliax.work/internal-devnet-431.4e30980eee
Testing against the Housefire API will likely take several minutes, with the `difficulty` set at 3 (hence this PR): https://api.faucet.knowable.run

feat/1060 - Faucet: Move computePowSolution into web worker

---

apps/faucet/webpack.config.js

Fixes an issue where the asset URL was set to `https://faucet.heliax.click`. Note that this has introduced a 404 on the `apple-touch-icon.png`, I will see if I can resolve that error, but it's not critical
Update this app to Vite!

fix: Faucet - Use relative path for assets in Webpack config

---

apps/extension/package.json
apps/extension/src/manifest/_base.json

This PR simply renames the extension the base manifest file. This should now apply to both extension (FF & Chrome)
- Rename extension
- Bump minor version so this can be submitted

Rename Extension in manifest

---

apps/namadillo/src/App/Settings/EnableFeatures.tsx
apps/namadillo/src/App/Settings/FeaturesCheckbox.tsx
apps/namadillo/src/App/Settings/SettingsPanel.tsx
apps/namadillo/src/App/Settings/routes.ts
apps/namadillo/src/atoms/settings/atoms.ts

This is the first draft on how we could handle the next phases features on Namadillo. 
A new route (`/settings/features`) was added, where users can enable features individually

Namadillo: proposal on how to handle features on Namadillo

---

apps/namadillo/src/App/Common/Toast.tsx
apps/namadillo/src/hooks/useTransactionNotifications.tsx
apps/namadillo/src/lib/query.ts
apps/namadillo/src/types.d.ts
apps/namadillo/src/types/events.ts
packages/sdk/src/tx/tx.ts
packages/shared/lib/src/sdk/mod.rs
packages/shared/lib/src/sdk/tx.rs

Resolves #1081 
Using the response from `rpc.broadcastTx()`, check the `isApplied` value for each commitment, raise error if any are not applied.
This makes use of the `ProcessTxResponse` from the SDK's `rpc.broadcastTx()`. Example:
```json
{
"code": "0",
"commitments": [
{
"hash": "DE979B02CC9014068E09DEFCB26592FB2A992D43B35B57C1CC9643BAE4F392CE",
"isApplied": true
},
{
"hash": "C91EED4782248D482517AE5C37AEA9895E1469439C42C059789C334FB9F8031C",
"isApplied": true
}
],
"gasUsed": "210",
"hash": "BC99E787272BDD15468E3F5C86EEC2FBAE752C568983086805EDB5286F5BDB95",
"height": "16602",
"info": "Check batch for result.",
"log": ""
}
```
Each commitment in this response has a boolean indicating whether that commitment has been accepted by all VPs and applied on chain.
Testing this PR is a bit …

feat./1081 - Namadillo: Check Tx applied status when broadcasting

---

apps/extension/src/App/Accounts/DeleteAccount.tsx

Resolves #1096 
A user reported an issue where attempting to Delete Account would redirect to View Mnemonic. This is because the "Backup My Wallet" link is suddenly being treated as a Submit button.
- In the extension, attempt to `Delete Account` using the Enter/Return key to submit
- This should now work. In the previous version on `main`, this was redirecting to `View Mnemonic`

fix/1096: Extension - Fix issue on Delete Accounts with form submit

---

apps/extension/src/Approvals/Approvals.tsx
apps/extension/src/Approvals/ApproveConnection.tsx
apps/extension/src/Approvals/ApproveDisconnect.tsx
apps/extension/src/Approvals/ApproveDisconnection.tsx
apps/extension/src/Approvals/types.ts
apps/extension/src/background/approvals/handler.test.ts
apps/extension/src/background/approvals/handler.ts
apps/extension/src/background/approvals/init.ts
apps/extension/src/background/approvals/messages.test.ts
apps/extension/src/background/approvals/messages.ts
apps/extension/src/background/approvals/service.test.ts
apps/extension/src/background/approvals/service.ts
apps/extension/src/provider/Namada.test.ts
apps/extension/src/provider/Namada.ts
apps/extension/src/provider/messages.ts
apps/namadillo/src/App/AppRoutes.tsx
apps/namadillo/src/App/SwitchAccount/SwitchAccountPanel.tsx

Add the disconnection account approval step
This PR also combine e create some methods for the Approvals service to manage the popup easier, the main one is `launchApprovalPopup` which takes a typed route and custom params. And it'll remove the popup resolver from the map once they are resolved or rejected, or when the popup is removed/closed by the user
https://github.com/user-attachments/assets/285a3a6f-aef3-4e8a-8c08-ea47e1cdc988

feat: add disconnect account approval step

---

apps/extension/src/App/Settings/ConnectedSites.tsx
packages/components/src/KeyListItem.tsx

Trim long strings on extension list items and add the `title` attribute for it as a last user resource

fix: trim long strings on extension list items

---

apps/faucet/src/App/App.tsx
apps/faucet/src/App/Faucet.tsx

Users of the faucet app have had issues using it when the accounts they need to fund are generate in the CLI.
This update removes the need to connect the extension to access your accounts, but it is still an option.

feat: Faucet - Make extension connection optional

---

apps/extension/src/Approvals/Approvals.tsx
apps/extension/src/Approvals/ApproveUpdateDefaultAccount.tsx
apps/extension/src/Approvals/types.ts
apps/extension/src/background/approvals/handler.ts
apps/extension/src/background/approvals/init.ts
apps/extension/src/background/approvals/messages.ts
apps/extension/src/background/approvals/service.ts
apps/extension/src/background/keyring/handler.ts
apps/extension/src/background/keyring/init.ts
apps/extension/src/background/keyring/keyring.ts
apps/extension/src/provider/Namada.ts
apps/extension/src/provider/messages.ts
apps/namadillo/src/App/SwitchAccount/SwitchAccountPanel.tsx

Add switching account approval step

feat: add switching account approval step

---

apps/namadillo/src/App/Common/ConnectExtensionButton.tsx
apps/namadillo/src/App/Common/Intro.tsx
apps/namadillo/src/App/Common/Navigation.tsx
apps/namadillo/src/App/Settings/Advanced.tsx
apps/namadillo/src/App/Settings/SettingsMain.tsx
apps/namadillo/src/App/Sidebars/MainnetRoadmap.tsx
apps/namadillo/src/App/Sidebars/ValidatorDiversification.tsx
apps/namadillo/src/App/Sidebars/YourStakingDistribution.tsx

Few content updates throughout the system

Namadillo: general content tweaks

---

apps/faucet/package.json
apps/namadillo/package.json
packages/integrations/package.json
yarn.lock

Moved dependency to `packages/integrations`, re-ran `yarn`. This was breaking Namadillo in dev mode
- Confirm that all apps should run in dev mode! Previously we were getting a runtime error in Namadillo
- Confirm that all apps build (production mode)
- Docker actions in CI are successful

fix: Ethers dependency should be listed for integrations only

---

apps/namadillo/src/App/Governance/ProposalHeader.tsx
apps/namadillo/src/atoms/proposals/atoms.ts

This was caused by returning undefined from react query to signal that the user has no existing vote, but returning undefined is disallowed by react query.

fix: fix vote button being incorrectly disabled

---

apps/namadillo/src/App/AppRoutes.tsx
apps/namadillo/src/App/Common/Navigation.tsx
apps/namadillo/src/App/Ibc/Ibc.tsx
apps/namadillo/src/App/Ibc/index.ts
apps/namadillo/src/App/Ibc/routes.ts
packages/integrations/package.json
yarn.lock

This PR adds a very basic form for IBC transfers into Namada. It is a rough first draft intended to be used as a base for building further IBC features and is definitely not production-quality code. It only works for transfers from the main Cosmos testnet (`theta-testnet-001`).
I've not used our existing `Keplr` class from the integrations package for this because I wanted to see how we need to use Keplr for IBC before building any abstractions. I was thinking I might end up refactoring the integrations in the end anyway because the existing integrations abstraction was written with the old interface in mind, which had a very different design.
To test you will need gaiad and hermes set up locally. I can help anyone reviewing this PR set up what is needed.
---
- Add basic form for IBC …

IBC basic form

---

apps/namadillo/vite.config.mjs

Environment variables are not used anymore in Namadillo. Recently, due to some package updates we've introduced a very unlikely error entitled as `Uncaught TypeError: process.version is undefined` . This PR removes this unused configuration and also fixes this error.

Namadillo: removing unused .env injection on Vite config

---

apps/namadillo/src/atoms/accounts/atoms.ts
apps/namadillo/src/atoms/accounts/services.ts
apps/namadillo/src/atoms/chain/atoms.ts
apps/namadillo/src/registry/cosmoshub.json
apps/namadillo/src/registry/index.ts
apps/namadillo/src/registry/namada.json

The most basic stuff.
We can move registry to separate package also

feat: add  static chains config

---

packages/crypto/lib/src/crypto/bip39.rs
packages/crypto/lib/src/crypto/zip32.rs
packages/sdk/src/tests/data.ts
packages/sdk/src/tests/keys.test.ts
packages/sdk/src/utils.ts

Someone on Discord has reported that when testing import of the same mnemonic in the extension, sometimes their Payment Address is different. I'm not sure how this could be possible, and we have existing tests that ensure that the keys must match for any given mnemonic.
So, I propose:
- Add additional tests to the `@namada/crypto` lib (Rust & Jest)
- Imported mnemonic generates the same seed
- Payment Address & Viewing Key match expected when deriving from seed
- Add additional tests to `@heliax/namada-sdk` package (we currently have one test mnemonic, will add more)
- Ensure these tests are being run in CI each time
- `packages/crypto`
- `yarn test-wasm:ci`
- `yarn test`
- `packages/sdk`
- `yarn test`

packages: Additional tests around shielded keys

---

apps/namadillo/package.json
apps/namadillo/scripts/proxies.json
apps/namadillo/scripts/startProxies.js
apps/namadillo/src/hooks/useSdk.tsx
packages/sdk/src/masp.ts
packages/shared/lib/src/sdk/mod.rs
packages/shared/lib/src/sdk/mod.ts

Relates to #1098 (for building shielded Tx)
- In Namadillo: `yarn dev:proxy`
- **NOTE** In local dev mode, you only need to run the proxy once when to fetch the params. Once it's downloaded, the `masp.hasMaspParams()` check should always return true, as it is now persisted in IndexedDB!
- You'll probably need to just monitor the network requests the first time you load it, ensure the MASP param requests runs the first time, then on future runs it should not request anything. I didn't want to leave any `console.log` :D

feat/1098: Namadillo: Fetch, Store, and Load MASP params in SDK

---

apps/namadillo/src/App/AccountOverview/NavigationFooter.tsx
apps/namadillo/src/App/Governance/ProposalHeader.tsx
apps/namadillo/src/App/Staking/AllValidatorsTable.tsx
apps/namadillo/src/App/Staking/MyValidatorsTable.tsx
apps/namadillo/src/App/Staking/ReDelegate.tsx
apps/namadillo/src/App/Staking/StakingSummary.tsx
packages/components/src/ActionButton.tsx

Expand `ActionButton` to use react-router `Link` for internal navigation
This improves accessibility transforming the `<button onClick={() => navigate(...)}>` into `<a href={...}>` but not breaking the SPA
To test, you can navigate on any button, like the ones on TopNavigation and observe they are regular `<a>` that don't break the SPA

feat: expand ActionButton to use react-router Link for internal navigation

---

apps/namadillo/src/hooks/useSdk.tsx
packages/shared/lib/src/sdk/mod.ts

Resolves #592 
This PR validates the fetched MASP param before storing it. This will reject the promise and prevent an invalid param from being stored should length or checksum not match.
- In `packages/shared/lib/src/sdk/mod.ts` https://github.com/anoma/namada-interface/blob/e160a31a23a259e9e7a4ed205b7d15fcbfa596e9/packages/shared/lib/src/sdk/mod.ts#L21-L40 modify these values to invalidate them (either length or hash, length is checked first!)
- Rebuild the shared package: `yarn wasm:build` (Even though these changes are 100% TS, they are a part of `shared` lib and will not auto-reload in dev mode)
- Start Namadillo with `yarn dev:proxy` (bypasses CORS issue with localhost)
- If you have already successfully downloaded MASP params, just comment out the lines below in `useSdk` to force a …

feat/592: Validate length and checksum of fetched masp param

---

apps/extension/src/background/sdk/service.ts
apps/namadillo/src/App/Settings/Advanced.tsx
apps/namadillo/src/atoms/settings/atoms.ts
apps/namadillo/src/atoms/settings/services.ts
apps/namadillo/src/hooks/useSdk.tsx
apps/namadillo/src/types.d.ts
packages/crypto/lib/Cargo.lock
packages/crypto/lib/rust-toolchain.toml
packages/crypto/lib/src/crypto/bip39.rs
packages/crypto/lib/src/crypto/zip32.rs
packages/sdk/src/indexWeb.ts
packages/sdk/src/tests/signing.test.ts
packages/shared/lib/Cargo.lock
packages/shared/lib/Cargo.toml
packages/shared/lib/rust-toolchain.toml
packages/shared/lib/src/query.rs
packages/shared/lib/src/rpc_client.rs
packages/shared/lib/src/sdk/args.rs
packages/shared/lib/src/sdk/masp/masp_node.rs
packages/shared/lib/src/sdk/masp/masp_web.rs
packages/shared/lib/src/sdk/masp/mod.rs
packages/shared/lib/src/sdk/masp/sync.rs
packages/shared/lib/src/sdk/mod.rs
packages/shared/lib/src/sdk/wallet/mod.rs
packages/shared/lib/src/types/masp.rs

I don't think there is an easy way to test this for now :/ But I think as long as this does not break other features we can merge it.
Okay!
**Make sure you test against 0.44.0**
So to test shielded sync w/o masp indexer you can:
- shield some nam using CLI(localnet example)
```sh
target/debug/namada wallet gen --shielded --alias albert-shielded --base-dir .namada/validator-0
target/debug/namada wallet gen-payment-addr --alias albert-pa1 --key albert-shielded --base-dir .namada/validator-0
target/debug/namada client shield --source albert --target albert-pa1 --token nam --amount 1000  --base-dir .namada/validator-0
target/debug/namada wallet find --alias albert-shielded --base-dir .namada/validator-0
```
- Add this to `App.tsx` in namadillo(with missing imports)
```ts
useEffect(() => { …
```

MASP indexer integration

---

apps/extension/FIREFOX_README.md
apps/extension/package.json

According to the results of our Firefox submission, the testers were using an `arm64` version of Ubuntu Desktop 22. As such:
- In macos (arm64) I installed the Ubuntu 22.04.5 LTS (Jammy Jellyfish) Daily build from https://cdimage.ubuntu.com/jammy/daily-live/current/ into VirtualBox
- Ran through testing instructions in `apps/extension/FIREFOX_README.md`, and added any commands that were needed along the way to get `yarn wasm:build` and `yarn build:firefox` to work
See the `Default Reviewer Build Environment` info at https://extensionworkshop.com/documentation/publish/source-code-submission/

Firefox - 0.3.3 updates

---

apps/namadillo/src/hooks/useSdk.tsx
packages/shared/lib/src/sdk/mod.ts

Relates to #592 
This PR allows us to fetch the MASP params directly from Namadillo assets, which would eliminate the need to handle potential CORS issues.
Adding this here as an option to dealing with the CORS issues seen on `https://interface.knowable.run`. There are a couple alternatives though:
- Keep the Github URL, but ensure the all hosts are configured with the correct CORS allow origins header
- Host these params elsewhere

bug/592: Provide MASP Params as local asset

---

apps/namadillo/src/App/Ibc/IbcWithdraw.tsx

This PR adds another very rough IBC prototype, this time for IBC transfers from Namada to Cosmos.
Note: The tx details are not dislaying properly in the extension, but as far as I know we need to get the IBC WASM hash from the indexer to do this, which it is currently not sending. anoma/namada-indexer#120
1. Set up hermes as in https://hackmd.io/a95Q2m6TRM-ntjFSSPzKTA (make sure to use `theta-testnet-001` as the Cosmos testnet)
2. Send some NAM to using the form
3. Check you received the NAM on the Cosmos side with `gaiad query bank balances <cosmos address> --node https://rpc-t.cosmos.nodestake.top/`

feat: add rough form for IBC withdrawals

---

packages/sdk/CHANGELOG.md
packages/sdk/package.json

With the initial release of the SDK, the version has been bump, and the first `CHANGELOG` added.

feat: sdk version bump 0.10.0, CHANGELOG

---

apps/namadillo/src/App/AccountOverview/AccountOverview.tsx
apps/namadillo/src/App/AccountOverview/NamBalanceContainer.tsx
apps/namadillo/src/App/Common/BalanceChart.tsx
apps/namadillo/src/App/Masp/MaspOverview.tsx
apps/namadillo/src/App/Masp/ShieldedBalanceChart.tsx
apps/namadillo/src/App/Masp/ShieldedNamBalance.tsx
apps/namadillo/src/App/Staking/StakingSummary.tsx
apps/namadillo/src/atoms/masp/atoms.ts
apps/namadillo/src/hooks/useBalances.ts
packages/components/src/PieChart.tsx

Improve pie chart responsiveness

feat: improve pie chart responsiveness

---

apps/namadillo/src/App/Ibc/IbcTransfer.tsx
apps/namadillo/src/atoms/integrations/atoms.ts
apps/namadillo/src/atoms/integrations/services.ts
packages/sdk/src/masp.ts
packages/sdk/src/tx/tx.ts
packages/shared/lib/src/sdk/mod.rs

This PR adds support for IBC deposits to shielded Namada addresses.
Testing instructions are the same as #1162 but running `namadac shielded-sync` is necessary before checking that balance was received.
---
- Re-add source channel input element (since I think we will need to change channels relatively frequently before mainnet)
- Rename `IBCTransferParams` to `IbcTransferParams`
- Support IBC deposits to Namada shielded addresses
- Add SDK methods to get MASP address and to generate IBC shielding memo
- Fix Long value being passed instead of BigInt in `timeoutTimestampNanoseconds`
- I don't think this is what was causing the timeouts over IBC but I'm not 100% sure

feat: add support for IBC deposits to shielded

---

apps/namadillo/src/App/Ibc/IbcTransfer.tsx
apps/namadillo/src/App/Ibc/IbcWithdraw.tsx
apps/namadillo/src/App/Transfer/TransferModule.tsx
apps/namadillo/src/App/Transfer/__tests__/TransferDestination.test.tsx
apps/namadillo/src/registry/namadaAsset.ts

This PR re-enables IBC withdrawals for NAM (other tokens will follow later).
We have a problem where the TransferModule and cosmjs expect amounts to be in the base denom (e.g. namnam), but the Namada SDK expects amounts to be in the display denom (e.g. NAM). This has resulted in some temporary hacky code in this PR to convert between namnam and NAM which I'll remove this once I understand how to handle this properly, but for now the hacky code is enough to switch back on IBC withdrawals for NAM. Related: #1211.
---
- Move available amount fee deduction calculation to TransferModule
- Return `undefined` instead of `0` from available balance calculation when initial balance is undefined.
- Re-enable IBC withdrawals for NAM
- Rename "unam" to "namnam" in Namada asset

feat: re-enable IBC withdrawals for NAM

---

apps/namadillo/src/App/Ibc/IbcTransfer.tsx
apps/namadillo/src/atoms/integrations/atoms.ts
apps/namadillo/src/atoms/integrations/functions.ts
apps/namadillo/src/atoms/integrations/services.ts

This PR adds IBC assets to the asset list even when there is not a registry entry, and stores the hash for IBC tokens. Both of these things will be needed later for Shield All.
There are some UI problems with the IBC assets obscuring the amount input on the IBC transfer page, so for testing I suggest selecting "Cosmos" as the asset, entering the amount, and then switching to the asset you actually want to transfer. We can fix the UI in a later PR.
---
- Store IBC tokens by IBC hash (needed later for sending IBC tokens)
- Display full path for IBC tokens (i.e. including "transfer/channel-0/")
- Increase hardcoded transfer fee to stop transactions failing
- Show IBC tokens in asset list even when there isn't a registry entry

feat: display IBC tokens in IBC asset list

---

apps/namadillo/src/App/Ibc/IbcTransfer.tsx
apps/namadillo/src/App/Ibc/IbcWithdraw.tsx
apps/namadillo/src/App/Ibc/ShieldAllAssetList.tsx
apps/namadillo/src/App/Transfer/TransferModule.tsx
apps/namadillo/src/App/Transfer/TransferTransactionFee.tsx
apps/namadillo/src/App/Transfer/__tests__/TransferDestination.test.tsx
apps/namadillo/src/atoms/integrations/functions.ts
apps/namadillo/src/atoms/integrations/services.ts
apps/namadillo/src/integrations/utils.ts

This PR fixes two bugs that were causing the TransferModule to incorrectly detect that there is not enough balance when the user is performing an IBC transaction. It also changes all amounts in Namadillo to be represented in the display denom (which is what we normally do for non-IBC things), converting to/from the base denom only when we receive or send amounts in the base denom (e.g. when submitting an IBC transfer to cosmjs).
The commits are fairly separate so it might be easier to review commit by commit.
Closes #1211.
---
- Represent all amount values in display denom
- This changes all amounts to be represented in their display denom throughout Namadilllo, converting at the edges when we receive or send amounts represented in the base denom
- Fixes the first of two bugs causing IBC …

IBC: Fix "Not enough balance" bugs + use display denom for amounts

---

apps/namadillo/package.json
apps/namadillo/src/atoms/integrations/functions.ts
yarn.lock

This PR simply upgrades the `@chain-registry/client` version to the latest so we can query and see balances for `osmo-test-5`

Namadillo: Use latest registry to update osmosis-testnet

---

apps/namadillo/src/atoms/integrations/functions.ts

This PR adds support for displaying asset information for IBC assets that have been sent over multiple channels (e.g. Namada -> Cosmos Hub -> Osmosis).
Closes #1219.
I found it a bit difficult to find live relayers for testing this, but I did get it to work with Namada devnet -> Cosmoshub testnet -> Elys testnet.
1. Transfer some NAM from the internal devnet to Cosmoshub testnet using Namadillo
2. Select "Elys Network" in Namadillo to prompt it to be added to Keplr
3. Transfer the NAM from Cosmoshub testnet to Elys testnet using gaiad (Keplr might work too but I've never tried)
4. Refresh Namadillo and select "Elys Network"
5. Your NAM should appear in the asset list with Namada icon and proper denomination handling.
You can also test by sending other assets between multiple chains if …

feat: decode IBC assets sent over multiple channels

---

apps/extension/src/App/Accounts/ViewingKey.tsx
apps/extension/src/Setup/Common/Completion.tsx
apps/extension/src/background/keyring/handler.ts
apps/extension/src/background/keyring/keyring.ts
apps/extension/src/background/keyring/messages.ts
apps/extension/src/background/keyring/service.ts

Resolves #1231 
The confirmation page and `View Keys` views are automatically updated, as the private key account (which seeds the shielded keys) is also treated as a parent.
- Start with a new extension install (Optional)
- Import or generate Mnemonic account (ensure existing functionality remains)
- Import another account from Private Key (can use: `00bebb118517e09c950841d849eb3e07e27e6cb9c59a8e71179220fa570d5d770f`) - should receive a shielded address
- Import mnemonic with custom path (existing functionality)
- Delete private key account, and then `Add Keys` - In the Import Mnemonic page under `Advanced`, set a custom path, then go to `Private Key` and import a private key as usual - this is to ensure that the custom path you entered is ignored when you import from private key (you …

feat/1231: Extension - Generate shielded keys from private key import

---

apps/namadillo/src/App/Ibc/ShieldAllAssetList.tsx
apps/namadillo/src/App/Ibc/ShieldAllPanel.tsx
apps/namadillo/src/atoms/balance/atoms.ts
apps/namadillo/src/atoms/balance/functions.ts
apps/namadillo/src/atoms/integrations/atoms.ts
apps/namadillo/src/atoms/integrations/functions.ts
apps/namadillo/src/hooks/useAssetAmount.tsx
apps/namadillo/src/registry/namadaAsset.ts
apps/namadillo/src/registry/unknownAsset.ts
apps/namadillo/src/types.d.ts

This PR makes sure we use the same method for translating addresses to assets for both Namada and Cosmos chains. It follows on from #1227 and #1228.
This will only work with the internal devnet, but I'll add a PR tomorrow to get it working with housefire too.
I think we still should refactor more, because it is quite confusing to have `namadaTransparentAssetsAtom` (turning Namada addresses into assets with balances), and `transparentTokensAtom` (returning the same thing but also with balances in dollars). I've left the refactoring for now because my goal was just to make sure we use the same code for Namada and Cosmos. There are also other things that could be refactored (e.g. turning BigNumbers back into strings, using `Coin` type even though it is basically the same as the `Balance` …

fix: unify asset decoding for Namada and Cosmos

---

apps/namadillo/package.json
apps/namadillo/src/App/Ibc/IbcTransfer.tsx
apps/namadillo/src/App/Ibc/IbcWithdraw.tsx
apps/namadillo/src/App/Ibc/ShieldAllAssetList.tsx
apps/namadillo/src/App/Ibc/ShieldAllPanel.tsx
apps/namadillo/src/App/Transfer/SelectAssetModal.tsx
apps/namadillo/src/App/Transfer/TransferModule.tsx
apps/namadillo/src/App/Transfer/TransferTransactionFee.tsx
apps/namadillo/src/App/Transfer/__mocks__/assets.tsx
apps/namadillo/src/App/Transfer/__tests__/AssetCard.test.tsx
apps/namadillo/src/App/Transfer/__tests__/SelectAssetModal.test.tsx
apps/namadillo/src/App/Transfer/__tests__/TransferDestination.test.tsx
apps/namadillo/src/atoms/balance/atoms.ts
apps/namadillo/src/atoms/balance/functions.ts
apps/namadillo/src/atoms/integrations/atoms.ts
apps/namadillo/src/atoms/integrations/functions.ts
apps/namadillo/src/atoms/integrations/services.ts
apps/namadillo/src/hooks/useAssetAmount.tsx
apps/namadillo/src/integrations/utils.ts
apps/namadillo/src/registry/namadaAsset.ts
apps/namadillo/src/types.d.ts
yarn.lock

This PR integrates Namadillo with Namada registry, as well as fixing some other things related to decoding addresses to assets. This adds support for holding the same asset from multiple chains. To test, you can transfer some NAM from the internal devnet to cosmoshub testnet to housefire, and you should see both your housefire NAM and your internal devnet NAM listed on your account.
The package.json points to a specific branch of namada-chain-registry, but I can update this as soon as anoma/namada-chain-registry#3 is merged. The code integrating the registry is a bit clunky, but this can be improved as the registry develops.
---
- Use Namada chain registry. Closes #1217
- Index assets by their original address, not by base denom. Fixes #1220
- Also refactor TransferModule accordingly
- …

feat: use namada registry + IBC decoding fixes

---

apps/namadillo/src/App/Ibc/IbcWithdraw.tsx
apps/namadillo/src/atoms/balance/index.ts
apps/namadillo/src/atoms/fees/atoms.ts
apps/namadillo/src/atoms/fees/functions.ts
apps/namadillo/src/atoms/fees/services.ts
apps/namadillo/src/atoms/integrations/atoms.ts
apps/namadillo/src/atoms/integrations/functions.ts
apps/namadillo/src/types.d.ts
apps/namadillo/src/types/events.ts
apps/namadillo/src/types/txKind.ts
packages/integrations/src/Keplr.ts
packages/sdk/docs/classes/Crypto.md
packages/sdk/docs/classes/Ledger.md
packages/sdk/docs/classes/Masp.md
packages/sdk/docs/classes/Mnemonic.md
packages/sdk/docs/classes/Rpc.md
packages/sdk/docs/classes/Sdk.md
packages/sdk/docs/classes/Signing.md
packages/sdk/docs/classes/Tx.md
packages/sdk/docs/enums/KdfType.md
packages/sdk/docs/enums/TxType.md
packages/sdk/docs/modules.md
packages/sdk/src/tx/tx.ts
packages/shared/lib/src/sdk/args.rs
packages/types/src/tx/schema/ibcTransfer.ts

This PR allows IBC withdrawals for all assets, instead of just NAM.
There is still zero indication to the user about whether the transaction failed or succeeded, but for testing this information should be displayed in the console.
---
- Use base denom amounts when building IBC transfers with JS SDK
- Use unknown gas limit value for txs without an indexer type
- Enable IBC withdrawals for all tokens. Closes #1242
- Use same gas limit and price for IBC withdrawal as rest of Namadillo
- Reveal public key if needed for IBC withdrawal. Fixes #1222

feat: enable IBC withdrawals for all tokens

---

apps/namadillo/package.json
apps/namadillo/src/atoms/integrations/functions.ts
yarn.lock

Fixes an issue on Namada Dry-Run net on IBC form where NAM asset is not displayed properly.
This also adds the Osmosis mainnet channels!
Before:
After:

fix: Add missing ibc references, add assets for namadadryrun

---

apps/namadillo/src/App/Ibc/IbcTransfer.tsx
apps/namadillo/src/App/Ibc/IbcWithdraw.tsx
apps/namadillo/src/App/Transfer/TransferModule.tsx
apps/namadillo/src/atoms/integrations/atoms.ts
apps/namadillo/src/atoms/integrations/functions.ts

This PR makes the IBC channels on the IBC Transfer and IBC Withdraw pages be auto-filled when there is a known IBC config, but still supports manually changing the inputs.
Closes #1241.

feat: auto-fill IBC channel inputs

---

apps/namadillo/src/App/Settings/Advanced.tsx

Resolves #1254 
1. Delete `localStorage` values for `settings` (if any)
2. Use the following `config.toml` (or similar)
```toml
indexer_url = "https://indexer.namada-dryrun.tududes.com"
rpc_url = "https://rpc.namada-dryrun.tududes.com"
masp_indexer_url = "https://masp.namada-dryrun.tududes.com"
```
3. Load `Settings` -> `Advanced` - All fields should be present!
4. Change settings, should persist as usual
```bash
https://indexer.knowable.run
https://rpc.knowable.run
https://masp.knowable.run
```
6. Test existing functionality when no `config.toml` is provided

fix/1254 - Namadillo: Show advanced settings when a config.toml is present

---

apps/namadillo/src/App/Governance/VoteInfoCards.tsx
packages/utils/src/crypto.ts
packages/utils/src/index.ts

Resolves #1248 
When a proposal contains wasm data, display the sha256 checksum hash in the UI
Namadillo (Proposal 1 on Dry-run)
CLI (Proposal 1 on Dry-run):

feat/1248: Display Sha256 hash of Proposal Wasm

---

apps/namadillo/src/App/Ibc/IbcTransfer.tsx
apps/namadillo/src/integrations/Keplr.ts
apps/namadillo/src/integrations/types.ts

PR to fix #1267. This makes use of a method described in https://docs.keplr.app/api/#how-to-detect-keplr to detect the Keplr wallet extension.
- This not only checks the `window`-object, but also checks the `document` state before it eventually decides whether Keplr is installed or not.
- Added an install method which opens the keplr download page in a _blank tab.
- Added the `install()` and `get()` functions to the `WalletConnector`-interface as this is likely going to become common among other integrations. But unsure about this, so tell me if this needs to go.
- `getSigner` needed to become an async function due to this detection method.
In my testing I didn't get problems with detecting Keplr anymore, but please double check if it's resolved. I'll also open another PR with a simpler …

fix: robuster way to detect/install keplr (#1267)

---

packages/shared/lib/Cargo.lock
packages/shared/lib/Cargo.toml
packages/shared/lib/src/query.rs

This PR simply updates our `shared` lib to use Namada `v0.46.0`

chore: Bump to namada v0.46.0

---

apps/namadillo/src/App/AccountOverview/MaspBanner.tsx
apps/namadillo/src/App/AccountOverview/TransparentOverviewPanel.tsx
apps/namadillo/src/App/Governance/AllProposalsTable.tsx
apps/namadillo/src/App/Governance/LiveGovernanceProposals.tsx
apps/namadillo/src/App/Governance/ProposalHeader.tsx
apps/namadillo/src/App/Governance/ProposalStatusSummary.tsx
apps/namadillo/src/App/Governance/UpcomingProposals.tsx
apps/namadillo/src/App/Layout/ActiveAccount.tsx
apps/namadillo/src/App/Layout/DisconnectAccountIcon.tsx
apps/namadillo/src/App/Layout/SwitchAccountIcon.tsx
apps/namadillo/src/App/Layout/assets/namada-wallet-icon.svg
apps/namadillo/src/App/Masp/ShieldedFungibleTable.tsx
apps/namadillo/src/App/Masp/ShieldedNFTTable.tsx
apps/namadillo/src/App/Masp/ShieldedOverviewPanel.tsx
apps/namadillo/src/App/Sidebars/ShieldAllBanner.tsx
packages/components/src/CopyToClipboardControl.tsx
packages/components/src/Panel.tsx

Some simple visual and navigation tweaks
closes #1279
closes #1310

feat: visual tweaks

---

apps/namadillo/src/hooks/useRegistryFeatures.tsx

Apparently, the proxy env import was incorrect, but went unnoticed as CORS issues stopped being a prominent issue. This PR fixes the env import, in the event we get blocked by CORS for this request.

fix: Namadillo - import proxy env correctly

---

apps/namadillo/src/App/App.tsx
apps/namadillo/src/App/Masp/ShieldedBalanceChart.tsx
apps/namadillo/src/atoms/balance/atoms.ts
apps/namadillo/src/atoms/balance/services.ts
apps/namadillo/src/workers/ShieldedSyncWorker.ts
packages/sdk/src/index.ts
packages/sdk/src/sdk.ts
packages/shared/lib/Cargo.toml
packages/shared/lib/src/query.rs
packages/shared/lib/src/sdk/args.rs
packages/shared/lib/src/sdk/events.rs
packages/shared/lib/src/sdk/masp/sync.rs
packages/shared/lib/src/sdk/mod.rs
packages/shared/lib/src/sdk/transaction.rs
packages/shared/lib/src/sdk/tx.rs
packages/shared/lib/src/types/masp.rs

feat/1206 - SDK: Adding events to shielded sync

---

apps/namadillo/src/App/Masp/ShieldedBalanceChart.tsx
apps/namadillo/src/atoms/balance/atoms.ts
packages/sdk/src/index.ts
packages/sdk/src/sdk.ts

Relates to #1324 
- Move any `@namada/shared` imports in Namadillo to `@namada/sdk`, as that is the package that will be published

SDK/Namadillo: feat/1324 - Move to SDK Imports

---

apps/namadillo/src/hooks/useTransactionNotifications.tsx

This PR adds the error details to the claim rewards toast and fixes the types so it does not appear as a success toast.
I think we could hide the error details behind the "View details" link, but this seems to not be displayed for error toasts as of #1084. We could probably move the details added in #1084 to the `decription` prop instead of the `details` prop, and then remove the hiding of "View details" for error toasts, but I haven't done it in this PR.
Before: 
After:
---
- Add error details to claim rewards error toast
- Make claim rewards error toast error type instead of success

fix: fix type and add error to claim rewards toast

---

apps/namadillo/package.json

Very simple PR to add git revision var to the `yarn build:only` script on Namadillo (I missed this the first time around)

bug: Namadillo - Add git revision var to build:only script

---

apps/extension/src/Setup/Common/Completion.tsx
apps/extension/src/Setup/Ledger/LedgerImport.tsx
apps/extension/src/Setup/Setup.tsx
apps/extension/src/Setup/index.tsx
apps/extension/src/Setup/query.ts
apps/extension/src/Setup/types.ts

Currently, the `Setup` app within the extension throws errors as the method of invoking React root is out of date. However, doing this introduced a new issue, where the `useEffect` would fire twice (`React.StrictMode`) in development, throwing an error where accounts are attempted to save twice. This has been resolved.
Run extension in development mode: `yarn start:chrome`
- Ensure Generate Mnemonic works
- Ensure Import Mnemonic works (with and without custom path & Bip39 passphrase)
- Ensure Import Private key works
- Ensure everything works from a new install of the extension (or zero accounts, where a password must be set)
- Ensure Ledger HW wallet import works as before
None of these should result in duplicate accounts.

BUG: Extension - Update index of Setup to fix errors & warnings

---

packages/sdk/docs/classes/Crypto.md
packages/sdk/docs/classes/Ledger.md
packages/sdk/docs/classes/Masp.md
packages/sdk/docs/classes/Mnemonic.md
packages/sdk/docs/classes/ProgressBarNames.md
packages/sdk/docs/classes/Rpc.md
packages/sdk/docs/classes/Sdk.md
packages/sdk/docs/classes/Signing.md
packages/sdk/docs/classes/Tx.md
packages/sdk/docs/enums/KdfType.md
packages/sdk/docs/enums/SdkEvents.md
packages/sdk/docs/modules.md
packages/sdk/package.json
packages/shared/lib/Cargo.lock
packages/shared/lib/Cargo.toml

- SDK -> version 0.11.0, needed for this Extension & SDK release
- Rebuild `packages/sdk` docs
- Bump namada to `v0.46.1` in `@namada/shared` lib (no other changes needed!)

chore: Bump SDK version, regenerate docs, bump Namada

---

apps/namadillo/src/atoms/validators/services.ts

We were filtering the `all` validators query by the active ones only. This PR fixes this behavior and possibly closes #1339 .

Namadillo: Displaying all validators

---

apps/extension/FIREFOX_README.md

As we no longer need to specify a chain ID in the extension `.env`, I'm removing this step in the build instructions. This will not be used in the 0.3.3 Firefox release!

chore: Remove unneeded Firefox instruction

---

apps/namadillo/src/App/Common/InlineError.tsx
apps/namadillo/src/atoms/integrations/services.ts

Fixes the way errors on IBC transfers are handled (only from IBC chains to Namada) and rollbacks a change made on #1250 to use `originalAddress` instead of `asset.base`.

Namadillo: handling IBC transfer errors + rolling back `originalAddress` change

---

apps/namadillo/src/App/NamadaTransfer/NamadaTransfer.tsx
apps/namadillo/src/lib/transactions.ts

After the implementation of `minDenomAmount` on the indexer, we've noticed that Namada transfers ended up dealing with the wrong amount. This PR fixes again this issue.

Namadillo: fixing denomination for Namada transfers

---

apps/namadillo/src/App/Staking/BondingAmountOverview.tsx

When the amount you want re-delegate contains some dust, the "Total amount to redelegate" was not showing all decimal places, making hard to proceed. This PR fixes this error.

Namadillo: increasing decimal places on redelegation

---

apps/namadillo/src/App/Setup/ExtensionLoader.tsx

Listen for extension to be enabled.
Useful if the user allow the extension only on click or any other barrier that delay the extension to be loaded
https://github.com/user-attachments/assets/3c85d3aa-99ec-4b64-86b6-76b868f79165

feat: listen for extension

---

apps/namadillo/package.json
apps/namadillo/src/atoms/integrations/functions.ts
apps/namadillo/src/hooks/useRegistryFeatures.tsx
apps/namadillo/src/utils/index.ts
yarn.lock

See registry updates in https://github.com/anoma/namada-chain-registry/pull/17

Registry update for Namada mainnet

---

apps/namadillo/package.json
apps/namadillo/src/hooks/useRegistryFeatures.tsx
package.json

To reproduce this, connect to a mainnet indexer where features = `[]` (no enabled features)
- `https://indexer.namada.tududes.com`
- With this fix, only enabled features are displayed
- Without it, all are displayed because of a logic bug :(

BUG - Namadillo: Fix issue where 0 enabled features returns ALL features

---

apps/namadillo/src/atoms/staking/services.ts
packages/shared/lib/src/sdk/args.rs
packages/shared/lib/src/sdk/tx.rs
packages/types/src/tx/schema/wrapperTx.ts

We have to do this otherwise in the scenario that we have more rewards than balance, the namada_sdk validation will fail with `NotEnoughBalance` error. Forcing bond will still log error in terminal, but we can't do much about it atm.

feat: force bond in the claim and stake flow

---

apps/namadillo/src/lib/transactions.ts

fix: Namadillo - IBC transfer should also not have an empty string memo

---

apps/extension/package.json
apps/extension/src/Approvals/ConfirmSignLedgerTx.tsx
apps/namadillo/package.json
packages/sdk/README.md
packages/sdk/docs/README.md
packages/sdk/package.json
yarn.lock

Resolves #1047 
- If only one Tx is being signed, just display `Approve on your device`
- If more than one needs signing, also display `Tx x of y`
Suggested updated Step 2 text:

feat/1047: Ledger transport updates, Updated Step 2 text

---

apps/namadillo/package.json
apps/namadillo/src/App/Governance/SubmitVote.tsx
apps/namadillo/src/App/Ibc/IbcWithdraw.tsx
apps/namadillo/src/hooks/useTransaction.tsx
apps/namadillo/src/lib/query.ts

Resolves #1047 
_NOTE_ - the major change in this PR was collecting commitments from any number of Txs, such that when we launch the notification, batch Tx & multiple-Txs can be handled the same way.
I'm testing on Housefire, which has 3 validators.
- Faucet: https://faucet.knowable.run
- Indexer: https://indexer.knowable.run
- RPC: https://indexer.knowable.run
- Test Txs with mnemonic/private key Keychain accounts (single & multiple Bond, for example)
- Test single and multiple Ledger HW Wallet Tx (single & multiple Bond, with & without `RevealPK` _NOTE_ If you've already revealed PK on Housefire, simply go to `Add Keys`, and on the Ledger connection page, click `Advanced` and specify a different path, thus generating a different Public Key & Address, then transfer from faucet to that …

bug/1047: Namadillo Ledger Notifications

---

apps/namadillo/src/App/Masp/ShieldedFungibleTable.tsx
apps/namadillo/src/atoms/integrations/functions.ts

Shorten unknown asset symbol to be something like `tnam...zp6h`, instead of the full address, which breaks the UI

feat: shorten unknown asset symbol

---

apps/namadillo/package.json
apps/namadillo/src/hooks/useTransactionNotifications.tsx

Simple bugfix PR - use the correct notification text for `VoteProposal` success & error.
- Use correct text for `VoteProposal` notifications
- Bump Namadillo version

fix: Namadillo - Use correct text for VoteProposal notification event

---

apps/extension/FIREFOX_README.md
apps/extension/webpack.config.js
docker/extension/Dockerfile

Creates a Docker image to build the extension. This ensures compatibility on Firefox builds.
Closes #1412

Extension: docker image and build instructions for firefox

---

apps/namadillo/package.json
apps/namadillo/src/App/Governance/ProposalDescription.tsx

Update proposal description
- Render text until a max-height of 350px
- Enable links and line breaks
We can upgrade the format support for a markdown, for example. But I suggest to discuss this a little bit more before implementing it
closes #1406
https://github.com/user-attachments/assets/12e43fac-bec1-42b3-974e-943cbbc5f9a3

feat: update proposal description

---

apps/namadillo/package.json
apps/namadillo/src/App/Governance/AllProposalsTable.tsx
apps/namadillo/src/App/Governance/LiveGovernanceProposals.tsx
apps/namadillo/src/App/Governance/ProposalHeader.tsx
apps/namadillo/src/App/Governance/VoteInfoCards.tsx
apps/namadillo/src/utils/dates.ts
apps/namadillo/src/utils/index.ts

Add a `title` to proposal times so user can check the timezone
Also, fix the table name that was saying `UTC` while it was a localized value. Now it render the timezone as well
closes #1426
Some sample simulating different cities:

feat: add time title helper

---

apps/namadillo/src/App/AppRoutes.tsx
apps/namadillo/src/App/Masp/ShieldedBalanceChart.tsx
apps/namadillo/src/App/Settings/SettingsMASP.tsx
apps/namadillo/src/App/Settings/SettingsMain.tsx
apps/namadillo/src/App/WorkerTest.tsx
apps/namadillo/src/App/routes.ts
apps/namadillo/src/atoms/balance/atoms.ts
apps/namadillo/src/atoms/balance/services.ts
apps/namadillo/src/atoms/chain/services.ts
apps/namadillo/src/atoms/settings/atoms.ts
apps/namadillo/src/atoms/settings/services.ts
apps/namadillo/src/hooks/useSdk.tsx
apps/namadillo/src/setupTests.ts
apps/namadillo/src/workers/MaspTxWorker.ts
apps/namadillo/src/workers/ShieldedSyncMessages.ts
apps/namadillo/src/workers/ShieldedSyncWorker.ts
packages/sdk/src/masp.ts
packages/sdk/src/rpc/rpc.ts
packages/shared/lib/src/query.rs
packages/shared/lib/src/sdk/masp/masp_node.rs
packages/shared/lib/src/sdk/masp/masp_web.rs
packages/shared/lib/src/sdk/mod.rs
packages/shared/package.json

Resolves #1420 and #1439 
- increase number of concurrent fetches
- add ability to invalidate shielded context
https://github.com/user-attachments/assets/6adbb5b6-da25-4553-93b1-d657ee7aef28
- store shielded context by chain id

feat: shielded sync improvements

---

apps/namadillo/src/App/Common/FixedWarningBanner.tsx
apps/namadillo/src/App/Layout/AppLayout.tsx
apps/namadillo/src/atoms/settings/atoms.ts
apps/namadillo/src/atoms/settings/services.ts
apps/namadillo/src/compatibility.json
apps/namadillo/src/hooks/useCompatibilityErrors.tsx
apps/namadillo/src/types.ts
apps/namadillo/src/utils/compatibility.tsx
apps/namadillo/src/utils/etc.ts

Displays a warning if the version received by the keychain or indexer doesn't match the version defined on `/compatibility.json` file

Namadillo: Checks for indexer and keychain compatibility

---

apps/namadillo/package.json
apps/namadillo/src/hooks/useTransactionNotifications.tsx
apps/namadillo/src/types/events.ts

Add listener for transfer error notification
closes #1297

feat: transfer error notification

---

apps/extension/package.json

bump extension version to 0.3.7

chore: bump extension version to 0.3.7

---

apps/namadillo/src/App/Common/QueryProvider.tsx
apps/namadillo/src/App/Common/StorageProvider.tsx
apps/namadillo/src/atoms/integrations/atoms.ts
apps/namadillo/src/atoms/integrations/functions.ts
apps/namadillo/src/atoms/integrations/services.ts
apps/namadillo/src/index.tsx
apps/namadillo/src/integrations/utils.ts
apps/namadillo/src/types.ts

If we query an RPC endpoint and it fails for whatever reason (timeout, CORS, etc), we should query the next one in the list. 
Closes #1464

Namadillo: querying next rpc if the previous one fails

---

apps/extension/FIREFOX_README.md
apps/extension/webpack.config.js
docker/extension/Dockerfile
packages/crypto/lib/src/crypto/bip39.rs
packages/crypto/src/__tests__/crypto.test.ts
packages/sdk/src/mnemonic.ts
packages/sdk/src/tests/mnemonic.test.ts

Relates to #1476 
[FIREFOX_README.md](https://github.com/anoma/namada-interface/blob/7c3dca3cfcd441a976bccd80eba591962c259636/apps/extension/FIREFOX_README.md)

docs/1476: Keychain: Update Firefox docs

---

apps/namadillo/public/config.toml
apps/namadillo/src/App/Ibc/IbcTransfer.tsx
apps/namadillo/src/App/Ibc/IbcWithdraw.tsx
apps/namadillo/src/atoms/integrations/atoms.ts
apps/namadillo/src/atoms/integrations/functions.ts
apps/namadillo/src/atoms/integrations/services.ts
apps/namadillo/src/lib/chain.ts
apps/namadillo/src/types.ts

Tries to fetch known IBC channels from namada-chain-registry repository, instead of relying on the ibc channels added to Namadillo build. Maybe in the future we can revert these changes, but now we'll need a more dynamic way to fetch the latest changes and info from relayers.
This PR also introduce new config.toml entries:
github_chain_registry_base_url = "https://raw.githubusercontent.com/anoma/namada-chain-registry/refs/heads/main"
github_namada_interface_url = "https://raw.githubusercontent.com/anoma/namada-interface/refs/heads/main"

feat: fetching known ibc channels from github chain-registry repository

---

apps/namadillo/src/hooks/useCompatibilityErrors.tsx
apps/namadillo/src/utils/compatibility.tsx

This PR introduces a feature to verify the interface version for compatibility by dynamically fetching the required version from the remote package.json file hosted on GitHub.
- Introduced checkInterfaceCompatibilityError to handle interface version validation.
- Enhanced the useCompatibilityErrors hook to include this new check.
- The required interface version is fetched dynamically, ensuring accuracy and up-to-date compatibility.
- Displays a warning banner if the interface version is outdated or incompatible.
This update aligns the interface version check with the existing validations for the indexer and keychain, ensuring consistency across compatibility checks.
by 5ElementsNodes

feat: add version warning banner (anoma#1491)

---

apps/namadillo/src/App/Common/TransactionFee.tsx
apps/namadillo/src/App/Common/TransactionFeeButton.tsx
apps/namadillo/src/App/Ibc/IbcTransfer.tsx
apps/namadillo/src/App/Transfer/TransferDestination.tsx
apps/namadillo/src/App/Transfer/TransferModule.tsx
apps/namadillo/src/atoms/fees/atoms.ts

- Fix Namada Transfer fee adding the `txKind` to transfer query key
- Allow changing fee token for Ibc Withdraw
- Update the underline and hover of the <TransactionFee> button
closes #1501
closes #1492

fix: fix fee component on transfers

---

apps/namadillo/src/App/AccountOverview/AccountOverview.tsx
apps/namadillo/src/App/AccountOverview/BalanceOverviewChart.tsx
apps/namadillo/src/App/Masp/MaspLayout.tsx
apps/namadillo/src/App/Masp/ShieldedBalanceChart.tsx
apps/namadillo/src/App/Masp/ShieldedSyncProgress.tsx
apps/namadillo/src/App/Settings/SettingsMASP.tsx
apps/namadillo/src/atoms/balance/atoms.ts
apps/namadillo/src/atoms/balance/functions.ts
apps/namadillo/src/atoms/balance/services.ts
apps/namadillo/src/atoms/settings/atoms.ts
apps/namadillo/src/hooks/useTransactionCallbacks.tsx
apps/namadillo/src/hooks/useTransactionWatcher.tsx

This PR resolves most of the current issues related to the shielded balance
- Re-run the shielded sync and the shielded balance after any successful transfer. 
- The balance is now saved on local storage and we can provide the last cached value
- Added a shielded sync indicator on the sidebar that shows the percentage of the shielded sync on any Masp page and the Overview
- Also, update the indicator text when the shielded sync is converting assets, which currently takes a longer time and we don't have a progress indicator on the sdk side
- Fix the dollar value considering the NAM as zero until it's available on osmosis api. 
- Add a 2h timeout for transfers that do not completed and aren't available on chain for whatever reason
closes #1484
closes #1493
closes #1495
closes #1497 
closes …

feat: fetch shielded balances on transfer

---

apps/namadillo/public/config.toml
apps/namadillo/src/atoms/integrations/atoms.ts
apps/namadillo/src/types.ts
apps/namadillo/src/urls.ts

We introduced two different entries on config.toml that won't be super useful and are causing issues when providers don't upgrade the config.toml after a new Namadillo release. So we're removing this variables and setting them as constants in /url.ts

fix: removing Github configs overrides to avoid upgrade issues

---

apps/namadillo/src/App/Ibc/IbcTransfer.tsx
apps/namadillo/src/App/Transfer/TransferModule.tsx
apps/namadillo/src/atoms/integrations/services.ts
apps/namadillo/src/hooks/useIbcTransaction.tsx
apps/namadillo/src/hooks/useSimulateIbcTransferFee.ts
apps/namadillo/src/hooks/useTransactionNotifications.tsx
apps/namadillo/src/integrations/utils.ts
apps/namadillo/src/utils/gas.ts
apps/namadillo/src/utils/index.ts

First version of estimate gas calculation for IBC shielded transfers. Still requires some minor improvements / tweaks that I'll leave for later PRs, like loading state or refresh button.
I also added 5% more over the estimated gas just to make sure that the transaction will succeed. Maybe we can tweak this percentage using the gas usage selection modal /cc @euharrison
Closes #1486

feat: fixing ibc shielded gas estimate

---

apps/namadillo/src/App/Governance/SubmitVote.tsx
apps/namadillo/src/App/Ibc/IbcWithdraw.tsx
apps/namadillo/src/App/Staking/IncrementBonding.tsx
apps/namadillo/src/App/Staking/ReDelegate.tsx
apps/namadillo/src/App/Staking/StakingRewards.tsx
apps/namadillo/src/App/Staking/Unstake.tsx
apps/namadillo/src/atoms/notifications/functions.ts
apps/namadillo/src/hooks/useIbcTransaction.tsx
apps/namadillo/src/hooks/useTransaction.tsx
apps/namadillo/src/hooks/useTransactionNotifications.tsx
apps/namadillo/src/lib/query.ts

This PR contains a few improvements on IBC withdrawals and also a few refactors and fixes for IBC queries

feat: Improvements on IBC withdrawal

---

packages/shared/lib/src/utils.rs

Enable panic hook in Rust in the event of panics/unreachable so we can determine what is happening in SDK.

fix: SDK: Enable panic hook in SDK Rust for debugging

---

apps/namadillo/package.json
apps/namadillo/src/App/Governance/LiveGovernanceProposals.tsx
apps/namadillo/src/App/Governance/ProposalHeader.tsx
apps/namadillo/src/App/Governance/ProposalLabels.tsx
apps/namadillo/src/App/WorkerTest.tsx
apps/namadillo/src/atoms/api.ts
apps/namadillo/src/atoms/balance/atoms.ts
apps/namadillo/src/atoms/integrations/services.ts
apps/namadillo/src/atoms/proposals/atoms.ts
apps/namadillo/src/atoms/proposals/functions.ts
apps/namadillo/src/atoms/settings/atoms.ts
apps/namadillo/src/atoms/settings/services.ts
apps/namadillo/src/atoms/transfer/atoms.ts
apps/namadillo/src/atoms/transfer/services.ts
apps/namadillo/src/types.ts
apps/namadillo/src/workers/MaspTxMessages.ts
apps/namadillo/src/workers/MaspTxWorker.ts
packages/shared/lib/Cargo.lock
packages/shared/lib/Cargo.toml
packages/types/src/proposals.ts
yarn.lock

- bumps namada_sdk to the latest commit from main
- bumps namada indexer client to 1.1.6
- fixes types errors
- adds "voted unknown" label - this happens when someone voted then redelegated then voted again, this should not happen too often
- unified api configuration - sth changed and we have to override default headers produced by indexer client 
- fixed small problem with shielded sync not running when masp indexer url is not present
- fixed small issue in viewing keys atom which was checking shielded account by alias

chore: bump namada_sdk to current main and indexer client to 1.1.6

---

apps/extension/src/Approvals/ApproveSignTx.tsx
apps/extension/src/Approvals/Commitment.tsx
apps/extension/src/Approvals/types.ts
apps/extension/src/utils/index.ts
packages/sdk/src/tx/tx.ts
packages/shared/lib/src/sdk/args.rs
packages/shared/lib/src/sdk/events.rs
packages/shared/lib/src/sdk/masp/masp_web.rs
packages/shared/lib/src/sdk/transaction.rs
packages/shared/lib/src/sdk/tx.rs
packages/types/src/tx/schema/txDetails.ts
packages/types/src/tx/types.ts

feat/1442 - Extension: Updates to MASP Tx Details

---

apps/namadillo/src/App/Masp/MaspShield.tsx
apps/namadillo/src/App/Masp/MaspUnshield.tsx
apps/namadillo/src/App/NamadaTransfer/NamadaTransfer.tsx
apps/namadillo/src/App/Transfer/TransferModule.tsx
apps/namadillo/src/atoms/accounts/atoms.ts
apps/namadillo/src/atoms/ledger/atoms.ts
apps/namadillo/src/atoms/ledger/index.ts
apps/namadillo/src/types.ts
packages/sdk/src/index.ts
packages/sdk/src/ledger.ts

` quit app -> open app -> unplug device -> plug device in and open app again`
https://github.com/user-attachments/assets/8a5cc3b4-22f3-4f76-9f06-f6bacdd23bd2

feat: disable submit button for masp tx when using disconnected ledger device

---

apps/extension/src/storage/LocalStorage.ts
apps/namadillo/src/atoms/integrations/services.ts
apps/namadillo/src/workers/MaspTxMessages.ts
apps/namadillo/src/workers/MaspTxWorker.ts
packages/shared/lib/Cargo.lock
packages/shared/lib/Cargo.toml
packages/shared/lib/src/sdk/mod.rs

Also bumped namada_sdk to the latest commit.
Diff is mostly Cargo.lock
Seems to work ok:

fix: disposable gas payer timeout & ibc shielding with multicore

---

apps/namadillo/src/App/AccountOverview/NamBalanceContainer.tsx
apps/namadillo/src/App/AccountOverview/__tests__/NamBalanceContainer.test.tsx
apps/namadillo/src/App/Masp/ShieldedNamBalance.tsx
apps/namadillo/src/App/Settings/SettingsMASP.tsx
apps/namadillo/src/atoms/balance/atoms.ts
apps/namadillo/src/atoms/balance/services.ts
packages/sdk/src/rpc/rpc.ts
packages/shared/lib/src/sdk/mod.rs

Resolves #1371
This  integrates the shielded rewards.
~~The downside is that is seems that the endpoint in namada rpc returns some weird values,  so testing might be a bit tricky.
How  it works for me atm is that if I shield a lot of nam and wait one masp epoch I will see some rewards for one masp epoch, but then it will go back to 0.
You can shield more and repeat  the process~~
Not sure if campfire has nam rewards enabled :/ 
Also added a function which can simulate rewards for this:

feat: shielded rewards intergration

---

.github/workflows/build-extension-demo.yml

This PR simply restores the old Extension asset build workflow. This does not affect (or relate to) actual release workflows, this is only used to build ad-hoc demos!
__NOTE__ In the future, we could probably use pre-release tags and utilize release-please for producing assets to be used on Testnets instead of this, at which time, we can permanently remove this workflow!

chore: Adding extension demo build workflow

---

apps/namadillo/src/atoms/balance/atoms.ts

Fix race condition when the user has empty value for rewards

fix: empty reward storage

---

apps/namadillo/src/atoms/integrations/services.ts
apps/namadillo/src/hooks/useSimulateIbcTransferFee.ts
apps/namadillo/src/hooks/useTransaction.tsx
apps/namadillo/src/lib/query.ts

feat: check for ibc timeout if a response was not provided by the chain

---

apps/namadillo/src/App/Common/TransactionFeeButton.tsx
apps/namadillo/src/App/Masp/MaspShield.tsx
apps/namadillo/src/App/Staking/IncrementBonding.tsx
apps/namadillo/src/App/Staking/ReDelegate.tsx
apps/namadillo/src/App/Staking/Unstake.tsx
apps/namadillo/src/App/Transfer/TransferModule.tsx
apps/namadillo/src/atoms/fees/atoms.ts
apps/namadillo/src/atoms/integrations/atoms.ts
apps/namadillo/src/atoms/integrations/functions.ts
apps/namadillo/src/atoms/proposals/functions.ts
apps/namadillo/src/atoms/staking/services.ts
apps/namadillo/src/atoms/transfer/atoms.ts
apps/namadillo/src/atoms/transfer/services.ts
apps/namadillo/src/hooks/useIbcTransaction.tsx
apps/namadillo/src/hooks/useTransaction.tsx
apps/namadillo/src/hooks/useTransactionFee.ts
apps/namadillo/src/hooks/useTransfer.ts
apps/namadillo/src/lib/query.ts
apps/namadillo/src/types.ts
apps/namadillo/src/workers/MaspTxWorker.ts

This PR refactors all the transactions logic separating the build step from the signing step. With this we will be able to improve user experience while waiting for long steps, like the generation of masp params. I've only implemented multiple status on Shielding because we're going to change a few things on the UI in the next PRs.
It also creates a quick workaround to increase gas fees while we improve the indexer api for estimate. The reason behind it is that many transactions were frequently failing because of gas (ex: unstake, re-delegate, etc)

feat: improving masp transactions feedback for users and other gas estimation fixes

---

apps/namadillo/src/App/AccountOverview/AccountOverview.tsx
apps/namadillo/src/App/Governance/GovernanceOverview.tsx
apps/namadillo/src/App/Ibc/IbcTransfersLayout.tsx
apps/namadillo/src/App/Layout/Sidebar.tsx
apps/namadillo/src/App/Masp/MaspLayout.tsx
apps/namadillo/src/App/Masp/ShieldedSyncProgress.tsx
apps/namadillo/src/App/Staking/StakingOverview.tsx
apps/namadillo/src/App/Transfer/TransferLayout.tsx

- Update shielded sync indicator layout
- Create the shared `<Sidebar>` component
Closes: #1551
https://github.com/user-attachments/assets/790fb8fe-1fa4-4253-9c8b-44bc82182570

feat: update shield sync indicator layout

---

.github/workflows/docker.yml

Simple PR to trigger Docker build after a release is made

fix: adding back Docker build on release

---

apps/namadillo/src/hooks/useTransaction.tsx

Fix `broadcast` being called twice

fix: fix duplicated broadcast

---

apps/namadillo/src/App/AccountOverview/MaspBanner.tsx
apps/namadillo/src/App/AccountOverview/NamBalanceContainer.tsx
apps/namadillo/src/App/AccountOverview/__tests__/NamBalanceContainer.test.tsx
apps/namadillo/src/App/Masp/ShieldedBalanceChart.tsx
apps/namadillo/src/App/Masp/ShieldedNamBalance.tsx

Add the pulse animation on balances when shield sync is running
closes #1602
closes #1564
https://github.com/user-attachments/assets/6cd06cb5-9947-4e69-904f-94a58e078111

feat: add shielded balance pulse animation

---

apps/namadillo/src/App/Common/GasFeeModal.tsx
apps/namadillo/src/App/Common/TransactionFee.tsx
apps/namadillo/src/App/Common/TransactionFeeButton.tsx
apps/namadillo/src/App/Ibc/ShieldAllPanel.tsx
apps/namadillo/src/App/Transfer/TransferDestination.tsx
apps/namadillo/src/App/Transfer/TransferModule.tsx
apps/namadillo/src/App/Transfer/__tests__/TransferDestination.test.tsx
apps/namadillo/src/App/Transfer/common.ts
apps/namadillo/src/integrations/utils.ts
apps/namadillo/src/types.ts
apps/namadillo/src/utils/gas.ts

This PR fixes the unit displayed and used to calculate if user has funds to make an IBC transfer.

fix: fixing gas estimate on IBC transfers

---

apps/namadillo/src/atoms/balance/functions.ts
apps/namadillo/src/atoms/prices/functions.ts
apps/namadillo/src/types.ts

We can have more than one channel for the same base denom
For these cases, we need to fetch and map all dollar values to all possible addresses
We also removed the `N/A` in case it's missing a token dollar value for whatever reason. It simplifies how user understand these values and don't looks like buggy
closes #1608

feat: add dollar support for multiple channels

---

apps/namadillo/src/App/Transactions/TransactionCard.tsx
apps/namadillo/src/atoms/balance/atoms.ts
apps/namadillo/src/hooks/useOptimisticTransferUpdate.tsx
apps/namadillo/src/hooks/useTransfer.ts
apps/namadillo/src/lib/transactions.ts

Add optimistic response for shielded transfers
Plus, show more detailed information on transfer history: chain_id in case the name is missing on registry, and target in case of shielded transfers
closes #1553
https://github.com/user-attachments/assets/c2b752ac-b3ed-415b-b734-888eefbb495f

feat: add optimistic response for shielded transfers

---

apps/namadillo/src/App/AccountOverview/MaspBanner.tsx

Add shielded overview label
closes #1629

feat: add shielded overview label

---

apps/namadillo/src/atoms/chain/atoms.ts
apps/namadillo/src/atoms/fees/atoms.ts
apps/namadillo/src/utils/gas.ts
apps/namadillo/src/utils/index.ts

When loading the interface directly on http://localhost:5173/staking/claim-rewards or if you is too fast clicking on the 'Claim' button, the native token asset is not found and the gas is not used as displayAmount, so there is an error
The solution was to add `chainAssetsMap` on the `queryKey` plus changing the type of `chainTokensQuery` to `Record<Address, Asset | undefined>` with the undefined piece, so we can map similar cases better
https://github.com/user-attachments/assets/79f82092-f212-4a82-9419-b964e7c2f100

fix: rewards fee race condition

---

apps/namadillo/src/App/Common/ConnectPanel.tsx
apps/namadillo/src/App/Common/UnshieldAssetsModal.tsx
apps/namadillo/src/App/Masp/MaspLayout.tsx
apps/namadillo/src/App/Masp/ShieldedFungibleTable.tsx
apps/namadillo/src/App/Masp/ShieldedOverviewPanel.tsx

Update masp transfer flow 
- Add the missing modals for Shield/Unshield like we have on TopNavigation
- Temporally removes the IBC Unshield from Shielded Pool while it's not implemented
- Also, add the full banner of extension connect if it's not yet, so we don't show a eternal loading state which confuses the user 
closes https://github.com/anoma/namada-interface/issues/1494
closes https://github.com/anoma/namada-interface/issues/1631
https://github.com/user-attachments/assets/b7fff28d-e664-44af-9581-8dcf3193a194

feat: update shield/unshield navigation flow

---

apps/namadillo/src/App/NamadaTransfer/NamadaTransfer.tsx
apps/namadillo/src/App/Transfer/AssetCard.tsx
apps/namadillo/src/App/Transfer/SelectAssetModal.tsx

We need to block the selection of NAM until phase 5.
Instead of hiding it from the list, which result in empty array until user did some IBC, we simply disable it to improve communication
closes #1622

feat: disable nam on asset selector

---

apps/namadillo/src/atoms/fees/atoms.ts

Due to some re-delegate transactions failing, we're increasing again the amount of gas used based on the value provided by the indexer.

fix: increasing gas usage based on max value provided by indexer

---

apps/namadillo/src/atoms/integrations/services.ts
apps/namadillo/src/hooks/useTransactionWatcher.tsx

Fix pending transactions because the promise for 404 status wasn't handled inside the `switch...case`, then we move it to `handleStandardTransfer` 
Also, update the timeout to 30 minutes to avoid having the spinner for a long time

fix: pending transactions

---

apps/namadillo/src/App/AccountOverview/BalanceOverviewChart.tsx
apps/namadillo/src/App/AccountOverview/MaspBanner.tsx
apps/namadillo/src/App/AccountOverview/TransparentOverviewPanel.tsx
apps/namadillo/src/App/Masp/ShieldedBalanceChart.tsx

Rename `balance` to `value`
Also, replace the `N/A` by `$0` (zero) when there is no dollar value to avoid confusion of user thinking that there is a bug
closes https://github.com/anoma/namada-interface/issues/1614

fix: rename balance to value

---

packages/shared/lib/src/sdk/mod.rs

fix: load shielded context before generating ibc shielding memo

---

apps/namadillo/src/App/AccountOverview/TransparentOverviewPanel.tsx

Hide shield nam button until phase 5 on Transparent Overview panel

feat: hide shield nam button until phase 5

---

apps/namadillo/src/compatibility.json

Requires indexer to be on version 2.0.x

chore: bumping indexer compatibility

---

apps/namadillo/src/compatibility.json

In order to complete last rollout of different releases, we're finally setting the keychain to 0.4.0 and indexer to 2.0.x

fix: bumping namada keychain version (0.4.0) and fixing required indexer version (2.0.x)

---

apps/extension/src/Setup/Common/LedgerApprovalStep.tsx
apps/extension/src/Setup/Ledger/LedgerConnect.tsx
apps/extension/src/Setup/query.ts
apps/extension/src/background/keyring/handler.ts
apps/extension/src/background/keyring/keyring.ts
apps/extension/src/background/keyring/messages.ts
apps/extension/src/background/keyring/service.ts
packages/sdk/src/index.ts
packages/sdk/src/ledger.ts

Resolves #1698 
- Custom paths should be correct in `View Keys` - this is the only view where paths are seen, and only when they are non-default!
- Use 3.0.0+ version of Ledger (latest is `v3.0.1`) - flows should be identical to before with shielded accounts in place
- Custom zip32 paths are now correct (UI to be improved after this PR)
- Downgrade to version in Ledger Live (1.0.5) and go through import flows: You'll see a message that shielded accounts will be enabled in 3.0.0, and it will only import transparent
- Non-shielded Tx work as before

Check Ledger app version before enabling zip32

---

apps/namadillo/README.md
apps/namadillo/package.json
apps/namadillo/vite.config.mjs
docker/namadillo/.gitignore
docker/namadillo/Dockerfile
docker/namadillo/nginx.conf

Resolves #1598 
See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy#credentialless
For an example of how to get multicore working locally with a production build, one can use the following Python script to host the `dist` folder locally (copy into `/dist` after building, then run `python server.py`
```python
from http.server import HTTPServer, SimpleHTTPRequestHandler
class CustomHandler(SimpleHTTPRequestHandler):
def end_headers(self):
self.send_header("Cross-Origin-Opener-Policy", "same-origin")
self.send_header("Cross-Origin-Embedder-Policy", "require-corp")
super().end_headers()
server_address = ("", 8000)
httpd = HTTPServer(server_address, CustomHandler)
print("Serving on http://localhost:8000")
httpd.serve_forever()
```
This seems to be fixed …

fix: Updating docker & nginx configs for multicore

---

.github/workflows/release.yml
apps/namadillo/package.json

- Adding multicore to Namadillo build
- Publishing SDK to NPM repository

feat: adding multicore as default option for Namadillo and publishing sdk packages automatically to npm

---

apps/namadillo/src/App/Transfer/AssetCard.tsx
apps/namadillo/src/hooks/useRegistryFeatures.tsx

fix: truncate long token names in Select Asset modal

---

apps/namadillo/src/App/Staking/StakingRewards.tsx
apps/namadillo/src/App/Staking/__tests__/StakingRewards.test.tsx

Fix claim rewards fee button adding one controller for each transaction
This layout could update in the future to provide a better UX, but this is a quick win for the current claim issue\

fix: fix claim rewards fee button

---

apps/namadillo/src/atoms/balance/atoms.ts
apps/namadillo/src/atoms/balance/functions.ts

Fix missing nam asset on balances
Solution: use the `chainAssetsMapAtom` to map the tokens. This is more reliable because the previous implementation was using the integration search, that is focused on `denom` and `ibc/...` addresses, that is not the reality of how we handle balances based on `tnam...` address. 
This is happening on mainnet only because the `denom` and `ibc/...` addresses use the [chain-registry](https://github.com/cosmos/chain-registry/blob/master/namada/assetlist.json) instead of [namada-chain-resigry](https://github.com/anoma/namada-chain-registry/blob/main/namada/assetlist.json), which is missing the `address` field. We don't have housefire on `chain-registry`

fix: fix missing nam asset on balances

---

apps/namadillo/src/atoms/fees/atoms.ts
apps/namadillo/src/atoms/fees/services.ts

Add fallback for missing gas estimates
To test, you can simulate to stake for 15 validator at once with the network tab open, you will see the indexer returning 502, but the fee still increasing
closes https://github.com/anoma/namada-interface/issues/1734
https://github.com/user-attachments/assets/519c364c-af93-454d-b594-c4bc6c4747d1

fix: add fallback for missing gas estimates

---

apps/namadillo/src/App/Ibc/IbcTransfer.tsx
apps/namadillo/src/atoms/integrations/atoms.ts
apps/namadillo/src/atoms/integrations/functions.ts
apps/namadillo/src/atoms/integrations/services.ts

This PR filters all the available assets of a user to a list of enabled tokens. This list is fetched from `api/v1/ibc/rate-limits` endpoint that provides all the rate limits for enabled tokens.

feat: filter only enabled assets

---

apps/namadillo/package.json
apps/namadillo/src/atoms/fees/services.ts
apps/namadillo/src/compatibility.json
yarn.lock

chore: bump indexer client to 2.2.0

---

apps/namadillo/src/App/AccountOverview/TransparentOverviewPanel.tsx
apps/namadillo/src/App/Masp/MaspShield.tsx
apps/namadillo/src/App/Masp/MaspUnshield.tsx
apps/namadillo/src/App/NamadaTransfer/NamadaTransfer.tsx
apps/namadillo/src/App/routes.ts

Allow predefining transparent source for transfers
It fixes the transfer button on Overview
ref: https://github.com/anoma/namada-interface/issues/1612

fix: allow predefining transparent source for transfers

---

apps/namadillo/src/hooks/useSimulateIbcTransferFee.ts

Some IBC transactions were failing with the previous value. We're now increasing it a bit more, and of course it can be tweaked on Keplr's modal.

fix: increasing additional gas to avoid some ibc transactions failing

---

build-webapp.sh

See #1338 for background
The Laconic Network coordinates jurisdictionally diverse webapp deployments, via independent Service Providers running k8s on bare metal. The tooling operated by Service Providers automatically builds and deploys webapps published to the Laconic Network.
Example Namadillo deployments that use this script and were deployed via Laconic:
- https://namadillo.pwa.mekonglabs.xyz
- https://namadillo.apps.vaasl.io
[This PR](https://git.vdb.to/LaconicNetwork/hosted-frontends/pulls/1) will make cron job in that workflow file target the anoma repo, rather than my fork. Then, any new release cut from the anoma repo will trigger a deployment to: https://namadillo.apps.vaasl.io

Add build file to facilitate deploying Namadillo to Service Providers on the Laconic Network

---

apps/extension/src/App/Accounts/ParentAccounts.tsx
apps/extension/src/App/Accounts/SpendingKey.tsx
apps/extension/src/App/Accounts/ViewAccount.tsx
apps/extension/src/App/AppContent.tsx
apps/extension/src/App/routes.ts
apps/extension/src/Setup/ImportAccount/SeedPhraseImport.tsx
apps/extension/src/Setup/Setup.tsx
apps/extension/src/background/keyring/handler.ts
apps/extension/src/background/keyring/init.ts
apps/extension/src/background/keyring/keyring.ts
apps/extension/src/background/keyring/messages.ts
apps/extension/src/background/keyring/service.ts
apps/extension/src/background/keyring/types.ts
apps/extension/src/context/AccountContext.tsx
apps/extension/src/provider/InjectedNamada.ts
apps/extension/src/provider/Namada.ts
apps/extension/src/utils/index.ts
apps/namadillo/src/App/SwitchAccount/SwitchAccountPanel.tsx
apps/namadillo/src/atoms/accounts/atoms.ts
apps/namadillo/src/atoms/accounts/services.ts
packages/components/src/RadioGroup.tsx
packages/sdk/src/keys/keys.ts
packages/shared/lib/src/types/masp.rs
packages/types/src/account.ts
packages/types/src/namada.ts

Resolves #1720
__NOTE__ I think it's a good idea while running this locally, to take an existing dev extension installation based on `main` (or older), then loading it with this branch, just to simulate an upgrade. I didn't change any values in storage for this branch, but I think it's good to confirm the logic in place is correct for all existing accounts! That's a good practice for any Keychain update.
We want to make sure that the viewing key (and default address) we _derived_ from a mnemonic matches what is imported when we import the spending key directly. Also, and most critically, we need to ensure that this works with previous extension data in place, and doesn't affect the normal account flows in any way!
Since the PR introduces "Access Spending Key", we can test with any …

feat: Extension - Add view and import Spending Key

---

apps/namadillo/src/App/SwitchAccount/SwitchAccountPanel.tsx

Hide shielded keys on switch account panel

fix: hide shielded keys on switch account panel

---

apps/namadillo/src/App/Ibc/IbcWithdraw.tsx
apps/namadillo/src/App/Transfer/SelectedChain.tsx
apps/namadillo/src/App/Transfer/__tests__/TransferDestination.test.tsx
apps/namadillo/src/App/Transfer/__tests__/TransferSource.test.tsx
apps/namadillo/src/atoms/integrations/functions.ts

The target chain on Withdrawal should always be the original chain of the selected asset.
Fixes #1747

feat: limit ibc withdrawal of assets only for the same chain

---

apps/extension/src/Approvals/Approvals.tsx
apps/extension/src/Approvals/ApproveSignTx.tsx
apps/extension/src/Approvals/ConfirmSignTx.tsx

If user has a "stranded" transparent account (for example, they imported a mnemonic, but did not specify a unique zip32 path and detection prevented the duplicate shielded account from being saved), it fails to sign, as it _always_ sends a `SignMaspMsg`.
- Perform detection of commitment type (if it's a `TxType.Transfer`), and check before invoking masp signing.
- Enable only for `Unshielding` and `Shielded` transfers

fix: Signing without shielded account present

---

apps/namadillo/src/App/SwitchAccount/SwitchAccountPanel.tsx

This PR simply reverts the change to the `SwitchAccountPanel` filter used on latest Namadillo release.
- Spending key imports should display and able to be switched to in Namadillo

Revert change to SwitchAccountPanel filter

---

apps/namadillo/src/App/Masp/MaspLayout.tsx
apps/namadillo/src/App/Sidebars/MaspAssetRewards.tsx
apps/namadillo/src/atoms/chain/atoms.ts
apps/namadillo/src/atoms/chain/services.ts
apps/namadillo/src/types.ts
packages/sdk/src/rpc/rpc.ts
packages/sdk/src/rpc/types.ts
packages/shared/lib/src/query.rs
packages/shared/lib/src/types/query.rs

This PR adds the related methods to the sdk and shared packages to load global masp asset rewards from the RPC, and also implements the sidebar panel enumerating the rewards.
Closes #1334

feat: adding masp asset rewards panel info

---

apps/extension/src/Approvals/Approvals.tsx
apps/extension/src/Approvals/ConfirmSignArbitrary.tsx
apps/extension/src/Approvals/ConfirmSignLedgerTx.tsx
apps/extension/src/Approvals/ConfirmSignTx.tsx
apps/extension/src/Approvals/StatusBox.tsx
apps/extension/src/Approvals/types.ts
apps/extension/src/background/vault/handler.ts
apps/extension/src/background/vault/init.ts
apps/extension/src/background/vault/messages.ts
apps/extension/src/background/vault/service.ts
apps/extension/src/background/vault/tests/service.test.ts
apps/extension/src/background/vault/types.ts
apps/extension/src/test/init.ts
packages/storage/src/store/SessionKVStore.ts

Resolves #1411
**NOTE** The timeout period is set to 5 minutes.
- With this Keychain, unlock and submit a transaction
- You should not need to enter your password
- Check Chrome service worker (if testing on Chrome) - wait for it to go `Inactive`, then submit another Tx (~1 minute, make sure you don't have service worker dev tools open! This causes the service worker to stay running)
- If it's been under 5 minutes since you last entered your password, you should not be prompted for it when signing
- This test is just to demonstrate that an inactive Chrome service worker preserves the existing session and shouldn't have any effect on this feature
- After 5 minutes since you last entered your password, submit a Tx (you can change this line to like one minute if it's too annoying to wait): …

feat: Keychain signing - only require password on session timeout

---

apps/namadillo/src/App/Layout/SyncIndicator.tsx
apps/namadillo/src/atoms/chain/atoms.ts
apps/namadillo/src/atoms/settings/services.ts
apps/namadillo/src/atoms/syncStatus/atoms.ts
apps/namadillo/src/types.ts

With this change the "status dot" will turn red if one of indexers services - chain, pos, parameters or transactions lags behind.
This skips checks for rewards and governance as they do not update timestamps fast enough(computation can take a while). I plan to change this but first we need to update the indexer.
I think the best way to test it is to use different indexers and see if dot is turning red :D

feat: use indexer services timestamps in status check

---

apps/namadillo/src/App/App.tsx
apps/namadillo/src/App/Settings/SettingsMASP.tsx
apps/namadillo/src/atoms/settings/atoms.ts
apps/namadillo/src/hooks/useInvalidateShieldedContext.ts
apps/namadillo/src/hooks/useSdk.tsx
apps/namadillo/src/hooks/useShouldInvalidateShieldedContext.ts

Save the indexer version (per chain) when invalidating the shielded context. 
Then uses this saved version to compare with the minimum accepted indexer version:
- in case the saved version is below the minimum accepted
- and the indexer version is greater then the minimum accepted
- execute a new context invalidation saving the new indexer version
Closes: https://github.com/anoma/namada-interface/issues/1845
https://github.com/user-attachments/assets/ad9404d2-b032-4a57-8ce8-420d23cce06d

feat: invalidate shielded context based on indexer version

---

apps/namadillo/src/App/Layout/TopNavigation.tsx

Resolves #1789 
As Ledger HW Wallet does not have a _sign arbitrary data_ feature, we shouldn't display the sign-arbitrary button.
- Enable Sign Arbitrary in Settings
- With a non-Ledger account selected in Keychain, you should see the sign-arbitrary button in the top navigation
- With a Ledger account selected, even with Sign-Arbitrary enabled, you should not see the button

fix: Namadillo - If account is a Ledger, don't show sign arbitrary button

---

apps/namadillo/src/App/Common/BugReport.tsx
apps/namadillo/src/App/Settings/SettingsMain.tsx
apps/namadillo/src/atoms/settings/atoms.ts
apps/namadillo/src/atoms/settings/services.ts
apps/namadillo/src/atoms/syncStatus/atoms.ts
apps/namadillo/src/hooks/useInvalidateShieldedContext.ts
apps/namadillo/src/hooks/useShouldInvalidateShieldedContext.ts

Add masp indexer version and update all places related to it
Also, update the auto invalidate shielded context based on the **masp** indexer version, instead of the indexer version
Closes https://github.com/anoma/namada-interface/issues/1857

feat: add masp indexer version

---

apps/namadillo/src/App/AccountOverview/TransparentOverviewPanel.tsx
apps/namadillo/src/App/Ibc/IbcTransfer.tsx
apps/namadillo/src/App/Ibc/IbcWithdraw.tsx
apps/namadillo/src/App/Masp/MaspShield.tsx
apps/namadillo/src/App/Masp/MaspUnshield.tsx
apps/namadillo/src/App/NamadaTransfer/NamadaTransfer.tsx
apps/namadillo/src/hooks/useUrlState.ts

Fix link for ibc asset withdraw
Create the hook `useUrlState` as a helper to manipulate a state that exists on `URLSearchParams` and apply to all forms related to the transfers
Closes https://github.com/anoma/namada-interface/issues/1846
Closes https://github.com/anoma/namada-interface/issues/1612
https://github.com/user-attachments/assets/9a1ff373-a57d-4a6a-b5ca-fddba581a4c9

fix: fix link for ibc asset withdraw

---

apps/namadillo/src/App/Settings/Advanced.tsx
apps/namadillo/src/App/Sidebars/EpochInformation.tsx
apps/namadillo/src/atoms/integrations/atoms.ts
apps/namadillo/src/types.ts

This PR introduces an "advanced mode" for Namadillo. For version 2 of the interface, we're planning to hide a few features to make UX more clean and straightforward for regular users. As a starting point, this PR also hides Epoch info and closes #1851 .

feat: starting the advanced mode feature on Namadillo

---

apps/namadillo/src/App/Layout/AccountIconButton.tsx
apps/namadillo/src/App/Layout/NamadaAccount.tsx

On hover the account name, shows the account addresses to be copied
Also, hide the switch button in case the user has only one account (accounts with the same alias)
It also support shielded only accounts imported with spending key
Closes https://github.com/anoma/namada-interface/issues/1589
Closes https://github.com/anoma/namada-interface/issues/1554

feat: add button to copy shielded address

---

packages/crypto/lib/.cargo/config.toml
packages/crypto/lib/src/crypto/aes.rs
packages/crypto/lib/src/crypto/bip32.rs
packages/crypto/lib/src/crypto/pointer_types.rs
packages/crypto/lib/src/crypto/zip32.rs
packages/crypto/package.json
packages/shared/lib/.cargo/config.toml
packages/shared/lib/Cargo.toml
packages/shared/lib/src/sdk/args.rs
packages/shared/lib/src/sdk/mod.rs
packages/shared/lib/src/sdk/tx.rs
packages/shared/lib/src/types/masp.rs
packages/shared/lib/src/types/query.rs
packages/shared/package.json
packages/shared/scripts/build.js

- fixed clippy warnings
- added build target to `.cargo/config.toml`
- set `"web"` as default feature and added `--no-default-features` in build script, because of that:
- LSP correctly displays clippy warnings in code
- I had to add `--no-default-features` so we do not build both web and node at the same time
- for developing node features we can temporarily replace "web" with "node" in `Cargo.toml` - this only affects LSP code highlighting/checking

chore: fix clippy warnings

---

apps/extension/src/Approvals/ApproveConnection.tsx

Relates to #1791 
- To test - Lock keychain, and _from Namadillo_, from an approved domain/chain ID, click `Connect Keychain` - upon successful authentication, you shouldn't see the `Approve Connection` form flash before popup closes (this now displays only if the check approved site has happened before determining if anything should be displayed)
- Remove Site in keychain (unapprove it), lock keychain, then connect again from Namadillo - should see the form as expected

FIX: Keychain - Don't display approve connection form if already approved

---

apps/namadillo/src/lib/query.ts
packages/sdk/src/rpc/rpc.ts
packages/sdk/src/tx/tx.ts
packages/shared/lib/src/sdk/mod.rs
packages/shared/lib/src/sdk/tx.rs
packages/types/src/errors.ts
packages/types/src/index.ts
packages/types/src/tx/schema/txResponse.ts
packages/types/src/tx/types.ts

Resolves #1898 
See `ResultCode` definition at:
https://github.com/anoma/namada/blob/427a57cab8c93a18f293b00e9f54e6e9da5ac147/crates/tx/src/data/mod.rs#L42-L90
To update these error messages, we simply need to make the change here: https://github.com/anoma/namada-interface/blob/1f1962bd14f7134c25a8bd6739f53937eae79ac1/packages/types/src/tx/types.ts#L102-L116
Broadcast error messages returned from Namada SDK can now be parsed as JSON. The response before was being formatted in `broadcast_tx` in Namada SDK, so we'd end up with an error like this:
```
Encountered error while broadcasting transaction: StringTracer: server error: {"codespace":"","code":8,"data":"","log":"Mempool validation failed: Wrapper transaction exceeds its gas limit","hash":"11AE6D481A56ABB762509198DE7F5088EF1772A281F0FFC …
```

feat: SDK - Add lookup for TxResponse result codes

---

apps/extension/src/Setup/Ledger/LedgerConnect.tsx
packages/sdk/src/index.ts
packages/sdk/src/ledger.ts
packages/sdk/src/tests/ledger.test.ts

Resolves #1952 
Build/install extension from this branch, then, assuming you are on > v3.0.0 of the Namada App:
Nano S:
- In setup, import your Ledger
- You should see the warning in the screenshot below
- You should be able to successfully import just the transparent keys
Not-Nano S:
- In setup, import your Ledger
- You should not see any warning
- You are guided through 3 steps: Transparent import, Viewing key import, Proof Gen / Auth key import
See: https://github.com/LedgerHQ/ledger-live/blob/06cfbf04e2d99e4e7916ace7a10cff8d37c5c38a/libs/ledgerjs/packages/types-devices/src/index.ts#L4
Ledger Live has enumerated the available device IDs here:
```typescript
/**
* DeviceModelId is a unique identifier to identify the model of a Ledger hardware wallet.
*/
export enum DeviceModelId {
blue = …
```

bug: Keychain - Disable shielded key import for nano S

---

apps/namadillo/src/App/Transfer/TransferModule.tsx

Transparent transfers were checking for custom chains per [this](https://github.com/anoma/namada-interface/pull/1945) PR, but that's only necessary on IBC transfers *FROM* Namada

fix: update logic for ibc transfers from NAM

---

apps/extension/src/App/Settings/Network.tsx
apps/extension/src/Approvals/Approvals.tsx
apps/extension/src/Approvals/ApproveConnection.tsx
apps/extension/src/Approvals/ApproveSignArbitrary.tsx
apps/extension/src/Approvals/ApproveSignTx.tsx
apps/extension/src/background/approvals/handler.ts
apps/extension/src/background/approvals/service.test.ts
apps/extension/src/background/approvals/service.ts
packages/types/src/chain.ts

Resolves #1923 
If `chainId` is known (mainnet or long-running testnet) display name, otherwise, just chain ID, and show origin (the origin that issues the call to the keychain) on signing approvals.
**NOTE** The reason I added `chainIds` as as `string[]` to `ApproveSignTx` is because, in the case of Ledger, it is _possible_ to submit multiple Txs with different chain IDs, so this will display all of them (this should never really happen, but if say another interface attempts to submit it this way, we will display them). 
- Approve Connection: With an unapproved chain/domain, connect to keychain - should see the chain name if it is one of the three known networks, otherwise, just the chain ID
- Submit transactions for signing - should see origin & chain ID
- Also test Ledger with multiple …

feat: Keychain - Display chain name for known chains

---

apps/namadillo/src/App/Common/MaspSyncCover.tsx
apps/namadillo/src/App/Layout/AppLayout.tsx
apps/namadillo/src/App/Staking/MyValidatorsTable.tsx
apps/namadillo/src/App/Staking/StakingOverview.tsx
apps/namadillo/src/App/Staking/WithdrawalButton.tsx
packages/components/src/Panel.tsx

- Fix z-index of Shielded Sync overlay
- Fix hit area conflict on Staking buttons because of position relative/absolute conflicts
- Fix left nav top of 113px (instead of 112px)
https://github.com/user-attachments/assets/ffda4e9c-d3f3-4374-8c14-42bc48f27af0

fix: fix z index

---

packages/sdk/package.json
yarn.lock

Testing the packaged Firefox extension source, I found that it cannot build without Namadillo being in the repo (which provides this dependency). This explicitly includes it in the SDK package, and should be added before submitting the extension with source.
Context: For Firefox extension submissions only, we submit the source code related to the extension build, in the case that they choose to recreate the submitted extension (usually this is not needed). There are file-size limits on the submission, so we prune a bit of the repo as needed (mostly this is to remove Namadillo and `.git` which takes up the most space, along with any other unneeded files).
- Clone repo, delete `apps/namadillo`
- Run `yarn` to install deps
- In `apps/extension`, `yarn wasm:build && yarn build:firefox` - this …

SDK - fix missing type dependency in SDK

---

.github/workflows/verify-pull-request.yml
apps/namadillo/package.json
apps/namadillo/src/atoms/chain/atoms.ts
apps/namadillo/src/atoms/chain/services.ts
packages/shared/lib/Cargo.lock
packages/shared/lib/Cargo.toml
packages/shared/lib/rust-toolchain.toml
packages/shared/lib/src/sdk/mod.rs
yarn.lock

Updates introduced:
- Toolchain version: 1.85.1
- `rust-toolchain.toml` - nightly-2025-03-27
- `namada_tx` = libs-v0.149.1
- `namada_sdk` = libs-v0.149.1
- `tendermind-config` = 0.40.4
These are needed to support the latest MASP-indexer on the testnets!
We need an update in the Indexer client with the updated type for `checksums` in `Parameters`. I bumped the version, but it still does not contain the new fields, so I introduced a temporary type to cast it as.
This PR also fixes issue with blank Keychain approval:

SDK: Updating toolchain, SDK, Namadillo chain params

---

apps/namadillo/package.json
yarn.lock

This updates the mainnet maintenance branch indexer to version 2.5.4. This version includes the deducting of claimed staking rewards to show a proper Unclaimed Staking Rewards balance.

fix: update maintenance branch indexer

---

.github/actions/prepare-build/action.yml

This should fix the build issues when releasing via CI

fix: Prepare build action should have correct rust toolchain

---

apps/namadillo/package.json
apps/namadillo/src/App/Transfer/TransferModule.tsx
apps/namadillo/src/atoms/chain/atoms.ts
apps/namadillo/src/atoms/integrations/atoms.ts
apps/namadillo/src/atoms/integrations/functions.ts
apps/namadillo/src/utils/assets.ts
apps/namadillo/src/utils/index.ts
yarn.lock

Fix the new tokens missing from the chain/asset selector when executing a transfer.
- Add the missing chains
- Update the `namada-chain-registry` to pull the new assets from there, instead of merging with the osmosis one
- Rename some variables to help to understand the code
- Penumbra is out of this PR because they have another issue. They are listed as `non-cosmos` chain and they don't have a `chain.json` file. We need to handle this differently. https://github.com/cosmos/chain-registry/tree/master/_non-cosmos/penumbra
https://github.com/user-attachments/assets/5c8750f6-7dc6-4937-9a67-3afbe00a36cc

fix: fix new ibc tokens not showing

---

apps/namadillo/src/App/Common/Toast.tsx
apps/namadillo/src/utils/index.ts
packages/shared/lib/src/sdk/io.rs
packages/shared/lib/src/sdk/masp/masp_web.rs
packages/shared/lib/src/sdk/mod.rs
packages/shared/lib/src/sdk/tx.rs
packages/shared/lib/src/utils.rs

Often tx time out without any specific reason. It looks like `ControlFlow` logic  from `namada_sdk` does not work well with wasm/browser target. I moved loop from namada_sdk to shared and used promise based sleep.
Ah, also fixed clippy errors and ran fmt that's why there are more files changed.

feat: change query tx status loop

---

.github/actions/prepare-build/action.yml

Cuz action is failing: https://github.com/anoma/namada-interface/actions/runs/15207513436/job/42773978172

fix: missing shell in gh action

---

.github/actions/release-project/action.yml

We're removing the last part failing, cause we won't stable branch for now

ci: removing stable branch integration

---

apps/namadillo/public/manifest.json

fix: namada beeing installable

---

packages/sdk/package.json
packages/shared/package.json
yarn.lock

- Bump `@namada/shared`
- Specify version in `@namada/sdk` dependencies
- Include changes for https://github.com/anoma/namada-interface/pull/2075

feat: Bump SDK for Namada libs v0.150.1

---

apps/namadillo/src/App/Common/AssetsModalCard.tsx

This PR fixes this error on Firefox:

fix: images on AssetsModalCard not appearing on Firefox

---

apps/extension/src/App/Accounts/ParentAccounts.tsx
apps/extension/src/App/Accounts/UpdateRequired.tsx

Imported Ledger accounts which are outdated (i.e., missing shielded keys) should display a warning similar to the warning we use to re-import pre-modified zip32 shielded keys.
If you don't have an outdated Ledger to test with:
- In https://github.com/anoma/namada-interface/blob/1b3f4b9cc12034ffdc20de9908d3bc1367fcb019/apps/extension/src/Setup/Ledger/LedgerConnect.tsx#L62 set `const isMaspSupported = false;`
- Import from Ledger - it will not import shielded keys, then opening the app, the check will nag you about re-importing
- Revert changes to `LedgerConnect.tsx`, delete the account, then re-import. You will not see the warning.
If you do have an oudated Ledger:
- Import Ledger (if you haven't already) - you should see the banner and warning icon
- Update Ledger firmware & Namada app to …

feat: Mark Ledger accounts missing shielded account as outdated

---

.release-please-manifest.json

fix: Bump existing release please manifest for extension

---

apps/namadillo/src/App/Transfer/TransferModule.tsx

Resolves #2107
- enabled `transparent<->shielded` to  custom addresses
- added validation for `target == destination`
validation

feat: enable transfers between shielded and transparent addresses in the

---

apps/namadillo/src/App/Transfer/TransferModule.tsx

Closes #2105 
- makes sure fee is taken into account
- makes sure the rest of the component is aware of the selected asset

fix: automagically select first available asset when selecting a chain

---

apps/extension/src/background/vault/service.ts

This PR simply changes the session timeout from 5 minutes to 30 minutes. 
As shielded Tx take quite a long time to build, it would be nice if password wasn't required so quickly.

feat: Keychain - Increase session timeout from 5 to 30 minutes

---

apps/namadillo/src/App/Transactions/TransactionCard.tsx
apps/namadillo/src/App/Transactions/TransactionHistory.tsx

fix: update txn amounts for shielding/unshielding transfers

---

apps/namadillo/src/App/Governance/AllProposalsTable.tsx
apps/namadillo/src/App/Governance/ProposalLabels.tsx
apps/namadillo/src/App/Governance/ProposalsSummary.tsx
apps/namadillo/src/atoms/proposals/functions.ts
apps/namadillo/src/utils/index.ts
packages/types/src/proposals.ts

Resolves #2141 
"passed" and "rejected" were migrated to "executedPassed" and "executedRejected" in the indexer
How to test?
Try filtering in the governance view
Check if number of proposal in sidebar is correct
Indexer will be fixed by removing unused statuses from query

fix: proposal statuses filters

---

apps/namadillo/src/App/Masp/ShieldedFungibleTable.tsx

On home, show the comma separator for Shielded balance
Before
After

fix: shielded balance comma separator

---

apps/namadillo/src/App/AccountOverview/ShieldedAssetsOverview.tsx

Hide masp rewards box until phase 4
Before
After

fix: hide masp rewards box until phase 4

---

apps/extension/src/Approvals/ConfirmSignLedgerTx.tsx
apps/extension/src/background/approvals/messages.ts
apps/extension/src/background/approvals/service.test.ts
apps/extension/src/background/approvals/service.ts
apps/extension/src/background/keyring/keyring.ts
apps/extension/src/background/keyring/messages.ts
apps/extension/src/background/keyring/service.ts
packages/sdk/src/masp/masp.ts
packages/sdk/src/tx/tx.ts
packages/shared/lib/src/sdk/mod.rs

How to test signing inputs:
- try to unshield some nam
- during confirmation click on details and see if `maspTxIn` array has more than one entry:
```
"maspTxIn": [
{
"token": "tnam1q9gr66cvu4hrzm0sd5kmlnjje82gs3xlfg3v6nu7",
"value": "10",
"owner": "zvknam1qve5s2ayqqqqpqph2fygt2qa35f0gjz2qcfmcw8wejugyr4vlgrgxd4d05yg3ugskh7vwuzsgelfkffg7y9fal39xxafknv8wted2r8zlaxpfs2gnvuazr4x5cjpngx2p047zjrtmk9fgs6v3uk8h03nf23jdqdpzjq7udphuefful5u3nm5yx5xnxc8n4rtm09kn9e2z7jpe42t0jvaljc8fj6ncufdy7eq2g4u3rxpax9wqh6ye9s7qc6vd44nhp6e4hgafads95csqxwzn"
},
{
"token": "tnam1q9gr66cvu4hrzm0sd5kmlnjje82gs3xlfg3v6nu7",
"value": "86.7463",
"owner": "zvknam1qve5s2ayqqqqpqph2fygt2qa35f0gjz2qcfmcw8wejugyr4vlgrgxd4d05yg3ugskh7vwuzsgelfkffg7y9fal39xxafknv8wted2r8zlaxpfs2gnvuazr4x5cjpngx2p047zjrtmk9fgs6v3uk8h03nf23jdqdpzjq7 …
```

fix: use correct derivation path for masp signs using ledger AND sign all sapling inputs

---

apps/namadillo/src/atoms/integrations/atoms.ts
apps/namadillo/src/atoms/integrations/functions.ts
apps/namadillo/src/atoms/integrations/temp-assets.ts

Fix missing nam on mainnet ibc deposit
This PR rolls back https://github.com/anoma/namada-interface/pull/2182 and add the hardcoded asset nam
This is a hack, we should fix asap on chain-registry package
Also, notice this will only show mainnet NAMs, not housefire ones

fix: missing nam on mainnet ibc deposit

---

apps/namadillo/src/App/Ibc/IbcWithdraw.tsx
apps/namadillo/src/atoms/integrations/services.ts
apps/namadillo/src/hooks/useTransactionCallbacks.tsx
apps/namadillo/src/hooks/useTransactionNotifications.tsx
apps/namadillo/src/types/events.ts

Added ShieldedIbcWithdraw event type
How to test:
`#1`
- go to ibc transparent withdraw view
- set target to some non existent address like `osmo18st0wqx85av8y6xdlss9d6m2nepyqwj6n3q7js`
- you should see generic red toast(after long time probably, cuz of timeout)
`#2 `
- go to ibc shielded withdraw view
- set target to some non existent address like `osmo18st0wqx85av8y6xdlss9d6m2nepyqwj6n3q7js`
- you should see red toast with refund target info(after long time probably, cuz of timeout)

fix: do not display refund target error for transparent ibc withdrawals

---

apps/namadillo/src/atoms/integrations/functions.ts

One line PR's are so silly. Should fix NYM not being selectable, see #2256.
PS: you could scratch this and edit it in a new PR if I screwed something up wrt the contribution guidelines!

fix: changed supported asset from NYX to NYM

---

docker/faucet/Dockerfile
docker/namadillo/Dockerfile

Otherwise we get this:
```
#26 88.19 Caused by: `cargo metadata` exited with an error:     Updating crates.io index
#26 88.19     Updating git repository `https://github.com/namada-net/namada`
#26 88.19 error: failed to get `namada_sdk` as a dependency of package `shared v0.1.0 (/app/packages/shared/lib)`
#26 88.19 
#26 88.19 Caused by:
#26 88.19   failed to load source for dependency `namada_sdk`
#26 88.19 
#26 88.19 Caused by:
#26 88.19   Unable to update https://github.com/namada-net/namada?tag=libs-v0.251.1#9785a72d
#26 88.19 
#26 88.19 Caused by:
#26 88.19   failed to parse manifest at `/usr/local/cargo/git/checkouts/namada-a7dd000410f87378/9785a72/wasm/tx_bond/Cargo.toml`
#26 88.19 
#26 88.19 Caused by:
#26 88.19   feature `edition2024` is required
#26 88.19 
#26 88.19   The package …
```

chore: update rust version in dockerfiles

---

apps/namadillo/src/App/AccountOverview/ShieldedAssetsOverview.tsx
apps/namadillo/src/App/AccountOverview/TotalBalanceBanner.tsx
apps/namadillo/src/App/AccountOverview/UnshieldedAssetsOverview.tsx
apps/namadillo/src/atoms/balance/atoms.ts
apps/namadillo/src/hooks/useAmountsInFiat.tsx

This makes it so that when we don't have prices for tokens the users can still see their tokens. 
Also prevents the UI from being too wonky when prices aren't available.

chore: only show dollar based balances if the dollar balances are available
